-- ============================================================================
-- Migration: 20260919163000_seed_features_and_permissions
-- Description: Seed Master Features Catalog, System Permissions, System Default Roles,
--              Role Permissions, and backfill Company Feature Entitlements.
-- ============================================================================

-- ขั้นตอนที่ 1: Seed Master Feature Catalog (ตาราง "feature")
-- ----------------------------------------------------------------------------
INSERT INTO "feature" ("id", "code", "name", "description", "category", "is_active", "created_at", "updated_at")
VALUES
  (gen_random_uuid(), 'ATTENDANCE_MANAGEMENT', 'Attendance Management', 'Attendance logs and check-in schedules', 'HR', true, now(), now()),
  (gen_random_uuid(), 'LEAVE_MANAGEMENT', 'Leave Management', 'Leave types, quotas and requests', 'HR', true, now(), now()),
  (gen_random_uuid(), 'COMPANY_MANAGEMENT', 'Company Management', 'Companies and branches', 'ORGANIZATION', true, now(), now()),
  (gen_random_uuid(), 'ROLE_PERMISSION_MANAGEMENT', 'Access Control & Roles', 'Roles, permissions and feature access', 'SECURITY', true, now(), now()),
  (gen_random_uuid(), 'EMPLOYEE_MANAGEMENT', 'Employee Directory', 'Users and company members', 'HR', true, now(), now()),
  (gen_random_uuid(), 'FORM_MANAGEMENT', 'Form Management', 'Form templates, submissions and reviews', 'OPERATIONS', true, now(), now())
ON CONFLICT ("code") DO UPDATE SET
  "name" = EXCLUDED."name",
  "description" = EXCLUDED."description",
  "category" = EXCLUDED."category",
  "is_active" = EXCLUDED."is_active",
  "updated_at" = now();

--> statement-breakpoint

-- ขั้นตอนที่ 2: Seed Permissions (ตาราง "permission")
-- ----------------------------------------------------------------------------
INSERT INTO "permission" ("id", "action", "module", "description", "feature_id", "created_at", "updated_at")
SELECT gen_random_uuid(), v.action, v.module, v.description, f.id, now(), now()
FROM (VALUES
  ('attendance:check_in', 'attendance', 'attendance check in', 'ATTENDANCE_MANAGEMENT'),
  ('attendance:manage', 'attendance', 'attendance manage', 'ATTENDANCE_MANAGEMENT'),
  ('attendance:read', 'attendance', 'attendance read', 'ATTENDANCE_MANAGEMENT'),
  ('attendance_schedule:manage', 'attendance_schedule', 'attendance schedule manage', 'ATTENDANCE_MANAGEMENT'),
  ('attendance_schedule:read', 'attendance_schedule', 'attendance schedule read', 'ATTENDANCE_MANAGEMENT'),
  ('company:create', 'company', 'company create', 'COMPANY_MANAGEMENT'),
  ('company:delete', 'company', 'company delete', 'COMPANY_MANAGEMENT'),
  ('company:read', 'company', 'company read', 'COMPANY_MANAGEMENT'),
  ('company:update', 'company', 'company update', 'COMPANY_MANAGEMENT'),
  ('company_branch:create', 'company_branch', 'company branch create', 'COMPANY_MANAGEMENT'),
  ('company_branch:delete', 'company_branch', 'company branch delete', 'COMPANY_MANAGEMENT'),
  ('company_branch:read', 'company_branch', 'company branch read', 'COMPANY_MANAGEMENT'),
  ('company_branch:update', 'company_branch', 'company branch update', 'COMPANY_MANAGEMENT'),
  ('company_feature:create', 'company_feature', 'company feature create', 'ROLE_PERMISSION_MANAGEMENT'),
  ('company_feature:delete', 'company_feature', 'company feature delete', 'ROLE_PERMISSION_MANAGEMENT'),
  ('company_feature:read', 'company_feature', 'company feature read', 'ROLE_PERMISSION_MANAGEMENT'),
  ('company_feature:toggle', 'company_feature', 'company feature toggle', 'ROLE_PERMISSION_MANAGEMENT'),
  ('company_member:create', 'company_member', 'company member create', 'EMPLOYEE_MANAGEMENT'),
  ('company_member:delete', 'company_member', 'company member delete', 'EMPLOYEE_MANAGEMENT'),
  ('company_member:read', 'company_member', 'company member read', 'EMPLOYEE_MANAGEMENT'),
  ('company_member:update', 'company_member', 'company member update', 'EMPLOYEE_MANAGEMENT'),
  ('feature:create', 'feature', 'feature create', 'ROLE_PERMISSION_MANAGEMENT'),
  ('feature:read', 'feature', 'feature read', 'ROLE_PERMISSION_MANAGEMENT'),
  ('feature:toggle', 'feature', 'feature toggle', 'ROLE_PERMISSION_MANAGEMENT'),
  ('feature:update', 'feature', 'feature update', 'ROLE_PERMISSION_MANAGEMENT'),
  ('form_plan:manage', 'form_plan', 'Create and manage form plans and schedules', 'FORM_MANAGEMENT'),
  ('form_plan:read', 'form_plan', 'View form plans and occurrences', 'FORM_MANAGEMENT'),
  ('form_review:answer', 'form_review', 'Review individual answers (PASS/NEEDS_CHANGES)', 'FORM_MANAGEMENT'),
  ('form_review:finalize', 'form_review', 'Finalize submission review (APPROVE/RETURN)', 'FORM_MANAGEMENT'),
  ('form_review:read', 'form_review', 'View review entries and history', 'FORM_MANAGEMENT'),
  ('form_review:section', 'form_review', 'Review form sections (PASS/NEEDS_CHANGES)', 'FORM_MANAGEMENT'),
  ('form_review:self', 'form_review', 'Allow reviewing own submissions (requires another review permission)', 'FORM_MANAGEMENT'),
  ('form_submission:create', 'form_submission', 'form submission create', 'FORM_MANAGEMENT'),
  ('form_submission:read', 'form_submission', 'form submission read', 'FORM_MANAGEMENT'),
  ('form_submission:review', 'form_submission', 'form submission review', 'FORM_MANAGEMENT'),
  ('form_submission:submit', 'form_submission', 'form submission submit', 'FORM_MANAGEMENT'),
  ('form_submission:update', 'form_submission', 'form submission update', 'FORM_MANAGEMENT'),
  ('form_template:create', 'form_template', 'form template create', 'FORM_MANAGEMENT'),
  ('form_template:manage', 'form_template', 'Manage form templates (edit, archive, publish)', 'FORM_MANAGEMENT'),
  ('form_template:publish', 'form_template', 'form template publish', 'FORM_MANAGEMENT'),
  ('form_template:read', 'form_template', 'form template read', 'FORM_MANAGEMENT'),
  ('form_template:update', 'form_template', 'form template update', 'FORM_MANAGEMENT'),
  ('leave_quota:manage', 'leave', 'leave quota manage', 'LEAVE_MANAGEMENT'),
  ('leave_quota:read', 'leave', 'leave quota read', 'LEAVE_MANAGEMENT'),
  ('leave_request:approve', 'leave', 'leave request approve', 'LEAVE_MANAGEMENT'),
  ('leave_request:cancel', 'leave', 'leave request cancel', 'LEAVE_MANAGEMENT'),
  ('leave_request:create', 'leave', 'leave request create', 'LEAVE_MANAGEMENT'),
  ('leave_request:read', 'leave', 'leave request read', 'LEAVE_MANAGEMENT'),
  ('leave_type:manage', 'leave', 'leave type manage', 'LEAVE_MANAGEMENT'),
  ('leave_type:read', 'leave', 'leave type read', 'LEAVE_MANAGEMENT'),
  ('location:manage', 'location', 'location manage', 'ATTENDANCE_MANAGEMENT'),
  ('location:read', 'location', 'location read', 'ATTENDANCE_MANAGEMENT'),
  ('permission:assign', 'permission', 'permission assign', 'ROLE_PERMISSION_MANAGEMENT'),
  ('permission:create', 'permission', 'permission create', 'ROLE_PERMISSION_MANAGEMENT'),
  ('permission:delete', 'permission', 'permission delete', 'ROLE_PERMISSION_MANAGEMENT'),
  ('permission:read', 'permission', 'permission read', 'ROLE_PERMISSION_MANAGEMENT'),
  ('permission:revoke', 'permission', 'permission revoke', 'ROLE_PERMISSION_MANAGEMENT'),
  ('permission:update', 'permission', 'permission update', 'ROLE_PERMISSION_MANAGEMENT'),
  ('role:create', 'role', 'role create', 'ROLE_PERMISSION_MANAGEMENT'),
  ('role:delete', 'role', 'role delete', 'ROLE_PERMISSION_MANAGEMENT'),
  ('role:read', 'role', 'role read', 'ROLE_PERMISSION_MANAGEMENT'),
  ('role:update', 'role', 'role update', 'ROLE_PERMISSION_MANAGEMENT'),
  ('role_feature:check', 'role_feature', 'role feature check', 'ROLE_PERMISSION_MANAGEMENT'),
  ('role_feature:create', 'role_feature', 'role feature create', 'ROLE_PERMISSION_MANAGEMENT'),
  ('role_feature:delete', 'role_feature', 'role feature delete', 'ROLE_PERMISSION_MANAGEMENT'),
  ('role_feature:read', 'role_feature', 'role feature read', 'ROLE_PERMISSION_MANAGEMENT'),
  ('role_feature:toggle', 'role_feature', 'role feature toggle', 'ROLE_PERMISSION_MANAGEMENT'),
  ('user:create', 'user', 'user create', 'EMPLOYEE_MANAGEMENT'),
  ('user:delete', 'user', 'user delete', 'EMPLOYEE_MANAGEMENT'),
  ('user:read', 'user', 'user read', 'EMPLOYEE_MANAGEMENT'),
  ('user:update', 'user', 'user update', 'EMPLOYEE_MANAGEMENT')
) AS v(action, module, description, feature_code)
JOIN "feature" f ON f.code = v.feature_code
ON CONFLICT ("action") DO UPDATE SET
  "module" = EXCLUDED."module",
  "description" = EXCLUDED."description",
  "feature_id" = EXCLUDED."feature_id",
  "updated_at" = now();

--> statement-breakpoint

-- ขั้นตอนที่ 3: Seed System Default Roles (ตาราง "role")
-- ----------------------------------------------------------------------------
INSERT INTO "role" (
  "id", "company_id", "name", "description", "role_type",
  "is_system_default", "created_at", "updated_at"
)
SELECT gen_random_uuid(), NULL, v.name, v.description, v.role_type::role_type,
       true, now(), now()
FROM (VALUES
  ('SUPER_ADMIN', 'Super Admin', 'Platform administrator'),
  ('OWNER', 'Owner', 'Company owner'),
  ('ADMIN', 'Admin', 'Company administrator'),
  ('MEMBER', 'Member', 'Company member'),
  ('VIEWER', 'Viewer', 'Company viewer')
) AS v(role_type, name, description)
WHERE NOT EXISTS (
  SELECT 1 FROM "role" r
  WHERE r.role_type = v.role_type::role_type
    AND r.company_id IS NULL
    AND r.is_system_default = true
);

--> statement-breakpoint

-- ขั้นตอนที่ 4: Map Permissions สู่ System Default Roles (ตาราง "role_permission")
-- ----------------------------------------------------------------------------
INSERT INTO "role_permission" ("id", "role_id", "permission_id", "created_at", "updated_at")
SELECT gen_random_uuid(), r.id, p.id, now(), now()
FROM (VALUES
  ('SUPER_ADMIN', 'attendance:check_in'),
  ('SUPER_ADMIN', 'attendance:manage'),
  ('SUPER_ADMIN', 'attendance:read'),
  ('SUPER_ADMIN', 'attendance_schedule:manage'),
  ('SUPER_ADMIN', 'attendance_schedule:read'),
  ('SUPER_ADMIN', 'company:create'),
  ('SUPER_ADMIN', 'company:delete'),
  ('SUPER_ADMIN', 'company:read'),
  ('SUPER_ADMIN', 'company:update'),
  ('SUPER_ADMIN', 'company_branch:create'),
  ('SUPER_ADMIN', 'company_branch:delete'),
  ('SUPER_ADMIN', 'company_branch:read'),
  ('SUPER_ADMIN', 'company_branch:update'),
  ('SUPER_ADMIN', 'company_feature:create'),
  ('SUPER_ADMIN', 'company_feature:delete'),
  ('SUPER_ADMIN', 'company_feature:read'),
  ('SUPER_ADMIN', 'company_feature:toggle'),
  ('SUPER_ADMIN', 'company_member:create'),
  ('SUPER_ADMIN', 'company_member:delete'),
  ('SUPER_ADMIN', 'company_member:read'),
  ('SUPER_ADMIN', 'company_member:update'),
  ('SUPER_ADMIN', 'feature:create'),
  ('SUPER_ADMIN', 'feature:read'),
  ('SUPER_ADMIN', 'feature:toggle'),
  ('SUPER_ADMIN', 'feature:update'),
  ('SUPER_ADMIN', 'form_plan:manage'),
  ('SUPER_ADMIN', 'form_plan:read'),
  ('SUPER_ADMIN', 'form_review:answer'),
  ('SUPER_ADMIN', 'form_review:finalize'),
  ('SUPER_ADMIN', 'form_review:read'),
  ('SUPER_ADMIN', 'form_review:section'),
  ('SUPER_ADMIN', 'form_review:self'),
  ('SUPER_ADMIN', 'form_submission:create'),
  ('SUPER_ADMIN', 'form_submission:read'),
  ('SUPER_ADMIN', 'form_submission:review'),
  ('SUPER_ADMIN', 'form_submission:submit'),
  ('SUPER_ADMIN', 'form_submission:update'),
  ('SUPER_ADMIN', 'form_template:create'),
  ('SUPER_ADMIN', 'form_template:manage'),
  ('SUPER_ADMIN', 'form_template:publish'),
  ('SUPER_ADMIN', 'form_template:read'),
  ('SUPER_ADMIN', 'form_template:update'),
  ('SUPER_ADMIN', 'leave_quota:manage'),
  ('SUPER_ADMIN', 'leave_quota:read'),
  ('SUPER_ADMIN', 'leave_request:approve'),
  ('SUPER_ADMIN', 'leave_request:cancel'),
  ('SUPER_ADMIN', 'leave_request:create'),
  ('SUPER_ADMIN', 'leave_request:read'),
  ('SUPER_ADMIN', 'leave_type:manage'),
  ('SUPER_ADMIN', 'leave_type:read'),
  ('SUPER_ADMIN', 'location:manage'),
  ('SUPER_ADMIN', 'location:read'),
  ('SUPER_ADMIN', 'permission:assign'),
  ('SUPER_ADMIN', 'permission:create'),
  ('SUPER_ADMIN', 'permission:delete'),
  ('SUPER_ADMIN', 'permission:read'),
  ('SUPER_ADMIN', 'permission:revoke'),
  ('SUPER_ADMIN', 'permission:update'),
  ('SUPER_ADMIN', 'role:create'),
  ('SUPER_ADMIN', 'role:delete'),
  ('SUPER_ADMIN', 'role:read'),
  ('SUPER_ADMIN', 'role:update'),
  ('SUPER_ADMIN', 'role_feature:check'),
  ('SUPER_ADMIN', 'role_feature:create'),
  ('SUPER_ADMIN', 'role_feature:delete'),
  ('SUPER_ADMIN', 'role_feature:read'),
  ('SUPER_ADMIN', 'role_feature:toggle'),
  ('SUPER_ADMIN', 'user:create'),
  ('SUPER_ADMIN', 'user:delete'),
  ('SUPER_ADMIN', 'user:read'),
  ('SUPER_ADMIN', 'user:update'),
  ('OWNER', 'attendance:check_in'),
  ('OWNER', 'attendance:manage'),
  ('OWNER', 'attendance:read'),
  ('OWNER', 'attendance_schedule:manage'),
  ('OWNER', 'attendance_schedule:read'),
  ('OWNER', 'company:read'),
  ('OWNER', 'company:update'),
  ('OWNER', 'company_branch:create'),
  ('OWNER', 'company_branch:delete'),
  ('OWNER', 'company_branch:read'),
  ('OWNER', 'company_branch:update'),
  ('OWNER', 'company_feature:read'),
  ('OWNER', 'company_member:create'),
  ('OWNER', 'company_member:delete'),
  ('OWNER', 'company_member:read'),
  ('OWNER', 'company_member:update'),
  ('OWNER', 'feature:read'),
  ('OWNER', 'form_plan:manage'),
  ('OWNER', 'form_plan:read'),
  ('OWNER', 'form_review:answer'),
  ('OWNER', 'form_review:finalize'),
  ('OWNER', 'form_review:read'),
  ('OWNER', 'form_review:section'),
  ('OWNER', 'form_review:self'),
  ('OWNER', 'form_submission:create'),
  ('OWNER', 'form_submission:read'),
  ('OWNER', 'form_submission:review'),
  ('OWNER', 'form_submission:submit'),
  ('OWNER', 'form_submission:update'),
  ('OWNER', 'form_template:create'),
  ('OWNER', 'form_template:manage'),
  ('OWNER', 'form_template:publish'),
  ('OWNER', 'form_template:read'),
  ('OWNER', 'form_template:update'),
  ('OWNER', 'leave_quota:manage'),
  ('OWNER', 'leave_quota:read'),
  ('OWNER', 'leave_request:approve'),
  ('OWNER', 'leave_request:cancel'),
  ('OWNER', 'leave_request:create'),
  ('OWNER', 'leave_request:read'),
  ('OWNER', 'leave_type:manage'),
  ('OWNER', 'leave_type:read'),
  ('OWNER', 'location:manage'),
  ('OWNER', 'location:read'),
  ('OWNER', 'permission:assign'),
  ('OWNER', 'permission:read'),
  ('OWNER', 'permission:revoke'),
  ('OWNER', 'role:create'),
  ('OWNER', 'role:delete'),
  ('OWNER', 'role:read'),
  ('OWNER', 'role:update'),
  ('OWNER', 'role_feature:check'),
  ('OWNER', 'role_feature:create'),
  ('OWNER', 'role_feature:delete'),
  ('OWNER', 'role_feature:read'),
  ('OWNER', 'role_feature:toggle'),
  ('OWNER', 'user:read'),
  ('OWNER', 'user:update'),
  ('ADMIN', 'attendance:check_in'),
  ('ADMIN', 'attendance:manage'),
  ('ADMIN', 'attendance:read'),
  ('ADMIN', 'attendance_schedule:manage'),
  ('ADMIN', 'attendance_schedule:read'),
  ('ADMIN', 'company:read'),
  ('ADMIN', 'company:update'),
  ('ADMIN', 'company_branch:create'),
  ('ADMIN', 'company_branch:delete'),
  ('ADMIN', 'company_branch:read'),
  ('ADMIN', 'company_branch:update'),
  ('ADMIN', 'company_feature:read'),
  ('ADMIN', 'company_member:create'),
  ('ADMIN', 'company_member:delete'),
  ('ADMIN', 'company_member:read'),
  ('ADMIN', 'company_member:update'),
  ('ADMIN', 'feature:read'),
  ('ADMIN', 'form_plan:manage'),
  ('ADMIN', 'form_plan:read'),
  ('ADMIN', 'form_review:answer'),
  ('ADMIN', 'form_review:finalize'),
  ('ADMIN', 'form_review:read'),
  ('ADMIN', 'form_review:section'),
  ('ADMIN', 'form_review:self'),
  ('ADMIN', 'form_submission:create'),
  ('ADMIN', 'form_submission:read'),
  ('ADMIN', 'form_submission:submit'),
  ('ADMIN', 'form_submission:update'),
  ('ADMIN', 'form_template:create'),
  ('ADMIN', 'form_template:manage'),
  ('ADMIN', 'form_template:publish'),
  ('ADMIN', 'form_template:read'),
  ('ADMIN', 'form_template:update'),
  ('ADMIN', 'leave_quota:manage'),
  ('ADMIN', 'leave_quota:read'),
  ('ADMIN', 'leave_request:approve'),
  ('ADMIN', 'leave_request:cancel'),
  ('ADMIN', 'leave_request:create'),
  ('ADMIN', 'leave_request:read'),
  ('ADMIN', 'leave_type:manage'),
  ('ADMIN', 'leave_type:read'),
  ('ADMIN', 'location:manage'),
  ('ADMIN', 'location:read'),
  ('ADMIN', 'permission:assign'),
  ('ADMIN', 'permission:read'),
  ('ADMIN', 'permission:revoke'),
  ('ADMIN', 'role:create'),
  ('ADMIN', 'role:delete'),
  ('ADMIN', 'role:read'),
  ('ADMIN', 'role:update'),
  ('ADMIN', 'role_feature:check'),
  ('ADMIN', 'role_feature:create'),
  ('ADMIN', 'role_feature:delete'),
  ('ADMIN', 'role_feature:read'),
  ('ADMIN', 'role_feature:toggle'),
  ('ADMIN', 'user:read'),
  ('ADMIN', 'user:update'),
  ('MEMBER', 'attendance:read'),
  ('MEMBER', 'attendance_schedule:read'),
  ('MEMBER', 'company:read'),
  ('MEMBER', 'company_branch:read'),
  ('MEMBER', 'company_feature:read'),
  ('MEMBER', 'company_member:read'),
  ('MEMBER', 'feature:read'),
  ('MEMBER', 'form_review:read'),
  ('MEMBER', 'form_submission:read'),
  ('MEMBER', 'form_template:read'),
  ('MEMBER', 'leave_quota:read'),
  ('MEMBER', 'leave_request:read'),
  ('MEMBER', 'leave_type:read'),
  ('MEMBER', 'location:read'),
  ('MEMBER', 'permission:read'),
  ('MEMBER', 'role:read'),
  ('MEMBER', 'role_feature:check'),
  ('MEMBER', 'role_feature:read'),
  ('MEMBER', 'user:read'),
  ('MEMBER', 'attendance:check_in'),
  ('MEMBER', 'leave_request:create'),
  ('MEMBER', 'leave_request:cancel'),
  ('MEMBER', 'form_submission:create'),
  ('MEMBER', 'form_submission:update'),
  ('MEMBER', 'form_submission:submit'),
  ('VIEWER', 'attendance:read'),
  ('VIEWER', 'attendance_schedule:read'),
  ('VIEWER', 'company:read'),
  ('VIEWER', 'company_branch:read'),
  ('VIEWER', 'company_feature:read'),
  ('VIEWER', 'company_member:read'),
  ('VIEWER', 'feature:read'),
  ('VIEWER', 'form_review:read'),
  ('VIEWER', 'form_submission:read'),
  ('VIEWER', 'form_template:read'),
  ('VIEWER', 'leave_quota:read'),
  ('VIEWER', 'leave_request:read'),
  ('VIEWER', 'leave_type:read'),
  ('VIEWER', 'location:read'),
  ('VIEWER', 'permission:read'),
  ('VIEWER', 'role:read'),
  ('VIEWER', 'role_feature:check'),
  ('VIEWER', 'role_feature:read'),
  ('VIEWER', 'user:read')
) AS v(role_type, action)
JOIN "role" r ON r.role_type = v.role_type::role_type AND r.company_id IS NULL AND r.is_system_default = true
JOIN "permission" p ON p.action = v.action
WHERE NOT EXISTS (
  SELECT 1 FROM "role_permission" rp WHERE rp.role_id = r.id AND rp.permission_id = p.id
);

--> statement-breakpoint

-- ขั้นตอนที่ 5: Backfill Company Entitlements (ตาราง "company_feature")
-- ----------------------------------------------------------------------------
INSERT INTO "company_feature" ("id", "company_id", "feature_id", "is_enabled", "created_at", "updated_at")
SELECT gen_random_uuid(), c.id, f.id, true, now(), now()
FROM "company" c
CROSS JOIN "feature" f
WHERE f.is_active = true
  AND NOT EXISTS (
    SELECT 1 FROM "company_feature" cf WHERE cf.company_id = c.id AND cf.feature_id = f.id
  );
