-- Global default roles only. Preserve existing IDs, names and assignments.
-- Identify a default by role_type + NULL company_id + is_system_default,
-- not by display name, which administrators may rename.
INSERT INTO "role" (
  "id", "company_id", "name", "description", "role_type",
  "is_system_default", "created_at", "updated_at"
)
SELECT gen_random_uuid(), NULL, v.name, v.description, v.role_type::role_type,
       true, now(), now()
FROM (VALUES
  ('SUPER_ADMIN', 'Super Admin', 'Platform administrator'),
  ('OWNER', 'Owner', 'Company owner'),
  ('ADMIN', 'Admin', 'Company administrator'),
  ('MEMBER', 'Member', 'Company member'),
  ('VIEWER', 'Viewer', 'Company viewer')
) AS v(role_type, name, description)
WHERE NOT EXISTS (
  SELECT 1 FROM "role" r
  WHERE r.role_type = v.role_type::role_type
    AND r.company_id IS NULL
    AND r.is_system_default = true
);

--> statement-breakpoint

-- Explicit defaults matching SYSTEM_DEFAULT_ROLE_PERMISSIONS in domains.
-- Grant only known actions to global system roles; preserve existing grants.
-- Platform catalog writes and company entitlements remain SUPER_ADMIN defaults.
-- Form review is reserved for OWNER among tenant role defaults.
INSERT INTO "role_permission" ("id", "role_id", "permission_id", "created_at", "updated_at")
SELECT gen_random_uuid(), r.id, p.id, now(), now()
FROM (VALUES
  ('SUPER_ADMIN', 'attendance:check_in'),
  ('SUPER_ADMIN', 'attendance:manage'),
  ('SUPER_ADMIN', 'attendance:read'),
  ('SUPER_ADMIN', 'attendance_schedule:manage'),
  ('SUPER_ADMIN', 'attendance_schedule:read'),
  ('SUPER_ADMIN', 'company:create'),
  ('SUPER_ADMIN', 'company:delete'),
  ('SUPER_ADMIN', 'company:read'),
  ('SUPER_ADMIN', 'company:update'),
  ('SUPER_ADMIN', 'company_branch:create'),
  ('SUPER_ADMIN', 'company_branch:delete'),
  ('SUPER_ADMIN', 'company_branch:read'),
  ('SUPER_ADMIN', 'company_branch:update'),
  ('SUPER_ADMIN', 'company_feature:create'),
  ('SUPER_ADMIN', 'company_feature:delete'),
  ('SUPER_ADMIN', 'company_feature:read'),
  ('SUPER_ADMIN', 'company_feature:toggle'),
  ('SUPER_ADMIN', 'company_member:create'),
  ('SUPER_ADMIN', 'company_member:delete'),
  ('SUPER_ADMIN', 'company_member:read'),
  ('SUPER_ADMIN', 'company_member:update'),
  ('SUPER_ADMIN', 'feature:create'),
  ('SUPER_ADMIN', 'feature:read'),
  ('SUPER_ADMIN', 'feature:toggle'),
  ('SUPER_ADMIN', 'feature:update'),
  ('SUPER_ADMIN', 'form_submission:create'),
  ('SUPER_ADMIN', 'form_submission:read'),
  ('SUPER_ADMIN', 'form_submission:review'),
  ('SUPER_ADMIN', 'form_submission:submit'),
  ('SUPER_ADMIN', 'form_submission:update'),
  ('SUPER_ADMIN', 'form_template:create'),
  ('SUPER_ADMIN', 'form_template:publish'),
  ('SUPER_ADMIN', 'form_template:read'),
  ('SUPER_ADMIN', 'form_template:update'),
  ('SUPER_ADMIN', 'leave_quota:manage'),
  ('SUPER_ADMIN', 'leave_quota:read'),
  ('SUPER_ADMIN', 'leave_request:approve'),
  ('SUPER_ADMIN', 'leave_request:cancel'),
  ('SUPER_ADMIN', 'leave_request:create'),
  ('SUPER_ADMIN', 'leave_request:read'),
  ('SUPER_ADMIN', 'leave_type:manage'),
  ('SUPER_ADMIN', 'leave_type:read'),
  ('SUPER_ADMIN', 'permission:assign'),
  ('SUPER_ADMIN', 'permission:create'),
  ('SUPER_ADMIN', 'permission:delete'),
  ('SUPER_ADMIN', 'permission:read'),
  ('SUPER_ADMIN', 'permission:revoke'),
  ('SUPER_ADMIN', 'permission:update'),
  ('SUPER_ADMIN', 'role:create'),
  ('SUPER_ADMIN', 'role:delete'),
  ('SUPER_ADMIN', 'role:read'),
  ('SUPER_ADMIN', 'role:update'),
  ('SUPER_ADMIN', 'role_feature:check'),
  ('SUPER_ADMIN', 'role_feature:create'),
  ('SUPER_ADMIN', 'role_feature:delete'),
  ('SUPER_ADMIN', 'role_feature:read'),
  ('SUPER_ADMIN', 'role_feature:toggle'),
  ('SUPER_ADMIN', 'user:create'),
  ('SUPER_ADMIN', 'user:delete'),
  ('SUPER_ADMIN', 'user:read'),
  ('SUPER_ADMIN', 'user:update'),
  ('OWNER', 'attendance:check_in'),
  ('OWNER', 'attendance:manage'),
  ('OWNER', 'attendance:read'),
  ('OWNER', 'attendance_schedule:manage'),
  ('OWNER', 'attendance_schedule:read'),
  ('OWNER', 'company:read'),
  ('OWNER', 'company:update'),
  ('OWNER', 'company_branch:create'),
  ('OWNER', 'company_branch:delete'),
  ('OWNER', 'company_branch:read'),
  ('OWNER', 'company_branch:update'),
  ('OWNER', 'company_feature:read'),
  ('OWNER', 'company_member:create'),
  ('OWNER', 'company_member:delete'),
  ('OWNER', 'company_member:read'),
  ('OWNER', 'company_member:update'),
  ('OWNER', 'feature:read'),
  ('OWNER', 'form_submission:create'),
  ('OWNER', 'form_submission:read'),
  ('OWNER', 'form_submission:review'),
  ('OWNER', 'form_submission:submit'),
  ('OWNER', 'form_submission:update'),
  ('OWNER', 'form_template:create'),
  ('OWNER', 'form_template:publish'),
  ('OWNER', 'form_template:read'),
  ('OWNER', 'form_template:update'),
  ('OWNER', 'leave_quota:manage'),
  ('OWNER', 'leave_quota:read'),
  ('OWNER', 'leave_request:approve'),
  ('OWNER', 'leave_request:cancel'),
  ('OWNER', 'leave_request:create'),
  ('OWNER', 'leave_request:read'),
  ('OWNER', 'leave_type:manage'),
  ('OWNER', 'leave_type:read'),
  ('OWNER', 'permission:assign'),
  ('OWNER', 'permission:read'),
  ('OWNER', 'permission:revoke'),
  ('OWNER', 'role:create'),
  ('OWNER', 'role:delete'),
  ('OWNER', 'role:read'),
  ('OWNER', 'role:update'),
  ('OWNER', 'role_feature:check'),
  ('OWNER', 'role_feature:create'),
  ('OWNER', 'role_feature:delete'),
  ('OWNER', 'role_feature:read'),
  ('OWNER', 'role_feature:toggle'),
  ('OWNER', 'user:read'),
  ('OWNER', 'user:update'),
  ('ADMIN', 'attendance:check_in'),
  ('ADMIN', 'attendance:manage'),
  ('ADMIN', 'attendance:read'),
  ('ADMIN', 'attendance_schedule:manage'),
  ('ADMIN', 'attendance_schedule:read'),
  ('ADMIN', 'company:read'),
  ('ADMIN', 'company:update'),
  ('ADMIN', 'company_branch:create'),
  ('ADMIN', 'company_branch:delete'),
  ('ADMIN', 'company_branch:read'),
  ('ADMIN', 'company_branch:update'),
  ('ADMIN', 'company_feature:read'),
  ('ADMIN', 'company_member:create'),
  ('ADMIN', 'company_member:delete'),
  ('ADMIN', 'company_member:read'),
  ('ADMIN', 'company_member:update'),
  ('ADMIN', 'feature:read'),
  ('ADMIN', 'form_submission:create'),
  ('ADMIN', 'form_submission:read'),
  ('ADMIN', 'form_submission:submit'),
  ('ADMIN', 'form_submission:update'),
  ('ADMIN', 'form_template:create'),
  ('ADMIN', 'form_template:publish'),
  ('ADMIN', 'form_template:read'),
  ('ADMIN', 'form_template:update'),
  ('ADMIN', 'leave_quota:manage'),
  ('ADMIN', 'leave_quota:read'),
  ('ADMIN', 'leave_request:approve'),
  ('ADMIN', 'leave_request:cancel'),
  ('ADMIN', 'leave_request:create'),
  ('ADMIN', 'leave_request:read'),
  ('ADMIN', 'leave_type:manage'),
  ('ADMIN', 'leave_type:read'),
  ('ADMIN', 'permission:assign'),
  ('ADMIN', 'permission:read'),
  ('ADMIN', 'permission:revoke'),
  ('ADMIN', 'role:create'),
  ('ADMIN', 'role:delete'),
  ('ADMIN', 'role:read'),
  ('ADMIN', 'role:update'),
  ('ADMIN', 'role_feature:check'),
  ('ADMIN', 'role_feature:create'),
  ('ADMIN', 'role_feature:delete'),
  ('ADMIN', 'role_feature:read'),
  ('ADMIN', 'role_feature:toggle'),
  ('ADMIN', 'user:read'),
  ('ADMIN', 'user:update'),
  ('MEMBER', 'attendance:read'),
  ('MEMBER', 'attendance_schedule:read'),
  ('MEMBER', 'company:read'),
  ('MEMBER', 'company_branch:read'),
  ('MEMBER', 'company_feature:read'),
  ('MEMBER', 'company_member:read'),
  ('MEMBER', 'feature:read'),
  ('MEMBER', 'form_submission:read'),
  ('MEMBER', 'form_template:read'),
  ('MEMBER', 'leave_quota:read'),
  ('MEMBER', 'leave_request:read'),
  ('MEMBER', 'leave_type:read'),
  ('MEMBER', 'permission:read'),
  ('MEMBER', 'role:read'),
  ('MEMBER', 'role_feature:check'),
  ('MEMBER', 'role_feature:read'),
  ('MEMBER', 'user:read'),
  ('MEMBER', 'attendance:check_in'),
  ('MEMBER', 'leave_request:create'),
  ('MEMBER', 'leave_request:cancel'),
  ('MEMBER', 'form_submission:create'),
  ('MEMBER', 'form_submission:update'),
  ('MEMBER', 'form_submission:submit'),
  ('VIEWER', 'attendance:read'),
  ('VIEWER', 'attendance_schedule:read'),
  ('VIEWER', 'company:read'),
  ('VIEWER', 'company_branch:read'),
  ('VIEWER', 'company_feature:read'),
  ('VIEWER', 'company_member:read'),
  ('VIEWER', 'feature:read'),
  ('VIEWER', 'form_submission:read'),
  ('VIEWER', 'form_template:read'),
  ('VIEWER', 'leave_quota:read'),
  ('VIEWER', 'leave_request:read'),
  ('VIEWER', 'leave_type:read'),
  ('VIEWER', 'permission:read'),
  ('VIEWER', 'role:read'),
  ('VIEWER', 'role_feature:check'),
  ('VIEWER', 'role_feature:read'),
  ('VIEWER', 'user:read')
) AS v(role_type, action)
JOIN "role" r ON r.role_type = v.role_type::role_type
  AND r.company_id IS NULL AND r.is_system_default = true
JOIN "permission" p ON p.action = v.action
WHERE NOT EXISTS (
  SELECT 1 FROM "role_permission" rp
  WHERE rp.role_id = r.id AND rp.permission_id = p.id
);
