// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import {
  companyServicesAddCompanyMember,
  companyServicesCreateCompany,
  companyServicesDeleteCompany,
  companyServicesGetCompanies,
  companyServicesGetCompany,
  companyServicesGetCompanyBySlug,
  companyServicesGetCompanyMembers,
  companyServicesRemoveCompanyMember,
  companyServicesUpdateCompany,
  companyServicesUpdateCompanyMember,
  type Options,
  permissionServicesCreatePermission,
  permissionServicesDeletePermission,
  permissionServicesGetMyPermissions,
  permissionServicesGetPermissions,
  permissionServicesUpdatePermission,
  roleServicesAssignPermissionToRole,
  roleServicesCreateRole,
  roleServicesDeleteRole,
  roleServicesGetCompanyRoles,
  roleServicesGetRole,
  roleServicesGetRolePermissions,
  roleServicesGetSystemDefaultRoles,
  roleServicesRevokePermissionFromRole,
  roleServicesUpdateRole,
  userServicesCreateUser,
  userServicesDeleteUser,
  userServicesGetUser,
  userServicesGetUsers,
  userServicesUpdateUser,
} from '../sdk.gen';
import type {
  CompanyServicesAddCompanyMemberData,
  CompanyServicesAddCompanyMemberError,
  CompanyServicesAddCompanyMemberResponse,
  CompanyServicesCreateCompanyData,
  CompanyServicesCreateCompanyError,
  CompanyServicesCreateCompanyResponse,
  CompanyServicesDeleteCompanyData,
  CompanyServicesDeleteCompanyError,
  CompanyServicesDeleteCompanyResponse,
  CompanyServicesGetCompaniesData,
  CompanyServicesGetCompaniesError,
  CompanyServicesGetCompaniesResponse,
  CompanyServicesGetCompanyBySlugData,
  CompanyServicesGetCompanyBySlugError,
  CompanyServicesGetCompanyBySlugResponse,
  CompanyServicesGetCompanyData,
  CompanyServicesGetCompanyError,
  CompanyServicesGetCompanyMembersData,
  CompanyServicesGetCompanyMembersError,
  CompanyServicesGetCompanyMembersResponse,
  CompanyServicesGetCompanyResponse,
  CompanyServicesRemoveCompanyMemberData,
  CompanyServicesRemoveCompanyMemberError,
  CompanyServicesRemoveCompanyMemberResponse,
  CompanyServicesUpdateCompanyData,
  CompanyServicesUpdateCompanyError,
  CompanyServicesUpdateCompanyMemberData,
  CompanyServicesUpdateCompanyMemberError,
  CompanyServicesUpdateCompanyMemberResponse,
  CompanyServicesUpdateCompanyResponse,
  PermissionServicesCreatePermissionData,
  PermissionServicesCreatePermissionError,
  PermissionServicesCreatePermissionResponse,
  PermissionServicesDeletePermissionData,
  PermissionServicesDeletePermissionError,
  PermissionServicesDeletePermissionResponse,
  PermissionServicesGetMyPermissionsData,
  PermissionServicesGetMyPermissionsError,
  PermissionServicesGetMyPermissionsResponse,
  PermissionServicesGetPermissionsData,
  PermissionServicesGetPermissionsError,
  PermissionServicesGetPermissionsResponse,
  PermissionServicesUpdatePermissionData,
  PermissionServicesUpdatePermissionError,
  PermissionServicesUpdatePermissionResponse,
  RoleServicesAssignPermissionToRoleData,
  RoleServicesAssignPermissionToRoleError,
  RoleServicesAssignPermissionToRoleResponse,
  RoleServicesCreateRoleData,
  RoleServicesCreateRoleError,
  RoleServicesCreateRoleResponse,
  RoleServicesDeleteRoleData,
  RoleServicesDeleteRoleError,
  RoleServicesDeleteRoleResponse,
  RoleServicesGetCompanyRolesData,
  RoleServicesGetCompanyRolesError,
  RoleServicesGetCompanyRolesResponse,
  RoleServicesGetRoleData,
  RoleServicesGetRoleError,
  RoleServicesGetRolePermissionsData,
  RoleServicesGetRolePermissionsError,
  RoleServicesGetRolePermissionsResponse,
  RoleServicesGetRoleResponse,
  RoleServicesGetSystemDefaultRolesData,
  RoleServicesGetSystemDefaultRolesError,
  RoleServicesGetSystemDefaultRolesResponse,
  RoleServicesRevokePermissionFromRoleData,
  RoleServicesRevokePermissionFromRoleError,
  RoleServicesRevokePermissionFromRoleResponse,
  RoleServicesUpdateRoleData,
  RoleServicesUpdateRoleError,
  RoleServicesUpdateRoleResponse,
  UserServicesCreateUserData,
  UserServicesCreateUserError,
  UserServicesCreateUserResponse,
  UserServicesDeleteUserData,
  UserServicesDeleteUserError,
  UserServicesDeleteUserResponse,
  UserServicesGetUserData,
  UserServicesGetUserError,
  UserServicesGetUserResponse,
  UserServicesGetUsersData,
  UserServicesGetUsersError,
  UserServicesGetUsersResponse,
  UserServicesUpdateUserData,
  UserServicesUpdateUserError,
  UserServicesUpdateUserResponse,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL:
      options?.baseURL || (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const companyServicesGetCompaniesQueryKey = (
  options?: Options<CompanyServicesGetCompaniesData>,
) => createQueryKey('companyServicesGetCompanies', options);

/**
 * Get all companies
 */
export const companyServicesGetCompaniesOptions = (
  options?: Options<CompanyServicesGetCompaniesData>,
) =>
  queryOptions<
    CompanyServicesGetCompaniesResponse,
    AxiosError<CompanyServicesGetCompaniesError>,
    CompanyServicesGetCompaniesResponse,
    ReturnType<typeof companyServicesGetCompaniesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await companyServicesGetCompanies({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: companyServicesGetCompaniesQueryKey(options),
  });

/**
 * Create new company
 */
export const companyServicesCreateCompanyMutation = (
  options?: Partial<Options<CompanyServicesCreateCompanyData>>,
): UseMutationOptions<
  CompanyServicesCreateCompanyResponse,
  AxiosError<CompanyServicesCreateCompanyError>,
  Options<CompanyServicesCreateCompanyData>
> => {
  const mutationOptions: UseMutationOptions<
    CompanyServicesCreateCompanyResponse,
    AxiosError<CompanyServicesCreateCompanyError>,
    Options<CompanyServicesCreateCompanyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await companyServicesCreateCompany({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Add company member
 */
export const companyServicesAddCompanyMemberMutation = (
  options?: Partial<Options<CompanyServicesAddCompanyMemberData>>,
): UseMutationOptions<
  CompanyServicesAddCompanyMemberResponse,
  AxiosError<CompanyServicesAddCompanyMemberError>,
  Options<CompanyServicesAddCompanyMemberData>
> => {
  const mutationOptions: UseMutationOptions<
    CompanyServicesAddCompanyMemberResponse,
    AxiosError<CompanyServicesAddCompanyMemberError>,
    Options<CompanyServicesAddCompanyMemberData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await companyServicesAddCompanyMember({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Remove company member
 */
export const companyServicesRemoveCompanyMemberMutation = (
  options?: Partial<Options<CompanyServicesRemoveCompanyMemberData>>,
): UseMutationOptions<
  CompanyServicesRemoveCompanyMemberResponse,
  AxiosError<CompanyServicesRemoveCompanyMemberError>,
  Options<CompanyServicesRemoveCompanyMemberData>
> => {
  const mutationOptions: UseMutationOptions<
    CompanyServicesRemoveCompanyMemberResponse,
    AxiosError<CompanyServicesRemoveCompanyMemberError>,
    Options<CompanyServicesRemoveCompanyMemberData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await companyServicesRemoveCompanyMember({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update company member
 */
export const companyServicesUpdateCompanyMemberMutation = (
  options?: Partial<Options<CompanyServicesUpdateCompanyMemberData>>,
): UseMutationOptions<
  CompanyServicesUpdateCompanyMemberResponse,
  AxiosError<CompanyServicesUpdateCompanyMemberError>,
  Options<CompanyServicesUpdateCompanyMemberData>
> => {
  const mutationOptions: UseMutationOptions<
    CompanyServicesUpdateCompanyMemberResponse,
    AxiosError<CompanyServicesUpdateCompanyMemberError>,
    Options<CompanyServicesUpdateCompanyMemberData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await companyServicesUpdateCompanyMember({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const companyServicesGetCompanyBySlugQueryKey = (
  options: Options<CompanyServicesGetCompanyBySlugData>,
) => createQueryKey('companyServicesGetCompanyBySlug', options);

/**
 * Get company by slug
 */
export const companyServicesGetCompanyBySlugOptions = (
  options: Options<CompanyServicesGetCompanyBySlugData>,
) =>
  queryOptions<
    CompanyServicesGetCompanyBySlugResponse,
    AxiosError<CompanyServicesGetCompanyBySlugError>,
    CompanyServicesGetCompanyBySlugResponse,
    ReturnType<typeof companyServicesGetCompanyBySlugQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await companyServicesGetCompanyBySlug({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: companyServicesGetCompanyBySlugQueryKey(options),
  });

export const companyServicesGetCompanyMembersQueryKey = (
  options: Options<CompanyServicesGetCompanyMembersData>,
) => createQueryKey('companyServicesGetCompanyMembers', options);

/**
 * Get company members
 */
export const companyServicesGetCompanyMembersOptions = (
  options: Options<CompanyServicesGetCompanyMembersData>,
) =>
  queryOptions<
    CompanyServicesGetCompanyMembersResponse,
    AxiosError<CompanyServicesGetCompanyMembersError>,
    CompanyServicesGetCompanyMembersResponse,
    ReturnType<typeof companyServicesGetCompanyMembersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await companyServicesGetCompanyMembers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: companyServicesGetCompanyMembersQueryKey(options),
  });

/**
 * Delete company
 */
export const companyServicesDeleteCompanyMutation = (
  options?: Partial<Options<CompanyServicesDeleteCompanyData>>,
): UseMutationOptions<
  CompanyServicesDeleteCompanyResponse,
  AxiosError<CompanyServicesDeleteCompanyError>,
  Options<CompanyServicesDeleteCompanyData>
> => {
  const mutationOptions: UseMutationOptions<
    CompanyServicesDeleteCompanyResponse,
    AxiosError<CompanyServicesDeleteCompanyError>,
    Options<CompanyServicesDeleteCompanyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await companyServicesDeleteCompany({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const companyServicesGetCompanyQueryKey = (
  options: Options<CompanyServicesGetCompanyData>,
) => createQueryKey('companyServicesGetCompany', options);

/**
 * Get company by ID
 */
export const companyServicesGetCompanyOptions = (
  options: Options<CompanyServicesGetCompanyData>,
) =>
  queryOptions<
    CompanyServicesGetCompanyResponse,
    AxiosError<CompanyServicesGetCompanyError>,
    CompanyServicesGetCompanyResponse,
    ReturnType<typeof companyServicesGetCompanyQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await companyServicesGetCompany({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: companyServicesGetCompanyQueryKey(options),
  });

/**
 * Update company
 */
export const companyServicesUpdateCompanyMutation = (
  options?: Partial<Options<CompanyServicesUpdateCompanyData>>,
): UseMutationOptions<
  CompanyServicesUpdateCompanyResponse,
  AxiosError<CompanyServicesUpdateCompanyError>,
  Options<CompanyServicesUpdateCompanyData>
> => {
  const mutationOptions: UseMutationOptions<
    CompanyServicesUpdateCompanyResponse,
    AxiosError<CompanyServicesUpdateCompanyError>,
    Options<CompanyServicesUpdateCompanyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await companyServicesUpdateCompany({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const permissionServicesGetPermissionsQueryKey = (
  options?: Options<PermissionServicesGetPermissionsData>,
) => createQueryKey('permissionServicesGetPermissions', options);

/**
 * Get all permissions
 */
export const permissionServicesGetPermissionsOptions = (
  options?: Options<PermissionServicesGetPermissionsData>,
) =>
  queryOptions<
    PermissionServicesGetPermissionsResponse,
    AxiosError<PermissionServicesGetPermissionsError>,
    PermissionServicesGetPermissionsResponse,
    ReturnType<typeof permissionServicesGetPermissionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await permissionServicesGetPermissions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: permissionServicesGetPermissionsQueryKey(options),
  });

/**
 * Create permission
 */
export const permissionServicesCreatePermissionMutation = (
  options?: Partial<Options<PermissionServicesCreatePermissionData>>,
): UseMutationOptions<
  PermissionServicesCreatePermissionResponse,
  AxiosError<PermissionServicesCreatePermissionError>,
  Options<PermissionServicesCreatePermissionData>
> => {
  const mutationOptions: UseMutationOptions<
    PermissionServicesCreatePermissionResponse,
    AxiosError<PermissionServicesCreatePermissionError>,
    Options<PermissionServicesCreatePermissionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await permissionServicesCreatePermission({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const permissionServicesGetMyPermissionsQueryKey = (
  options?: Options<PermissionServicesGetMyPermissionsData>,
) => createQueryKey('permissionServicesGetMyPermissions', options);

/**
 * Get current user permissions
 */
export const permissionServicesGetMyPermissionsOptions = (
  options?: Options<PermissionServicesGetMyPermissionsData>,
) =>
  queryOptions<
    PermissionServicesGetMyPermissionsResponse,
    AxiosError<PermissionServicesGetMyPermissionsError>,
    PermissionServicesGetMyPermissionsResponse,
    ReturnType<typeof permissionServicesGetMyPermissionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await permissionServicesGetMyPermissions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: permissionServicesGetMyPermissionsQueryKey(options),
  });

/**
 * Create role
 */
export const roleServicesCreateRoleMutation = (
  options?: Partial<Options<RoleServicesCreateRoleData>>,
): UseMutationOptions<
  RoleServicesCreateRoleResponse,
  AxiosError<RoleServicesCreateRoleError>,
  Options<RoleServicesCreateRoleData>
> => {
  const mutationOptions: UseMutationOptions<
    RoleServicesCreateRoleResponse,
    AxiosError<RoleServicesCreateRoleError>,
    Options<RoleServicesCreateRoleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await roleServicesCreateRole({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const roleServicesGetCompanyRolesQueryKey = (
  options: Options<RoleServicesGetCompanyRolesData>,
) => createQueryKey('roleServicesGetCompanyRoles', options);

/**
 * Get roles by company
 */
export const roleServicesGetCompanyRolesOptions = (
  options: Options<RoleServicesGetCompanyRolesData>,
) =>
  queryOptions<
    RoleServicesGetCompanyRolesResponse,
    AxiosError<RoleServicesGetCompanyRolesError>,
    RoleServicesGetCompanyRolesResponse,
    ReturnType<typeof roleServicesGetCompanyRolesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await roleServicesGetCompanyRoles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: roleServicesGetCompanyRolesQueryKey(options),
  });

/**
 * Assign permission to role
 */
export const roleServicesAssignPermissionToRoleMutation = (
  options?: Partial<Options<RoleServicesAssignPermissionToRoleData>>,
): UseMutationOptions<
  RoleServicesAssignPermissionToRoleResponse,
  AxiosError<RoleServicesAssignPermissionToRoleError>,
  Options<RoleServicesAssignPermissionToRoleData>
> => {
  const mutationOptions: UseMutationOptions<
    RoleServicesAssignPermissionToRoleResponse,
    AxiosError<RoleServicesAssignPermissionToRoleError>,
    Options<RoleServicesAssignPermissionToRoleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await roleServicesAssignPermissionToRole({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const roleServicesGetSystemDefaultRolesQueryKey = (
  options?: Options<RoleServicesGetSystemDefaultRolesData>,
) => createQueryKey('roleServicesGetSystemDefaultRoles', options);

/**
 * Get system default roles
 */
export const roleServicesGetSystemDefaultRolesOptions = (
  options?: Options<RoleServicesGetSystemDefaultRolesData>,
) =>
  queryOptions<
    RoleServicesGetSystemDefaultRolesResponse,
    AxiosError<RoleServicesGetSystemDefaultRolesError>,
    RoleServicesGetSystemDefaultRolesResponse,
    ReturnType<typeof roleServicesGetSystemDefaultRolesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await roleServicesGetSystemDefaultRoles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: roleServicesGetSystemDefaultRolesQueryKey(options),
  });

/**
 * Delete role
 */
export const roleServicesDeleteRoleMutation = (
  options?: Partial<Options<RoleServicesDeleteRoleData>>,
): UseMutationOptions<
  RoleServicesDeleteRoleResponse,
  AxiosError<RoleServicesDeleteRoleError>,
  Options<RoleServicesDeleteRoleData>
> => {
  const mutationOptions: UseMutationOptions<
    RoleServicesDeleteRoleResponse,
    AxiosError<RoleServicesDeleteRoleError>,
    Options<RoleServicesDeleteRoleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await roleServicesDeleteRole({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const roleServicesGetRoleQueryKey = (
  options: Options<RoleServicesGetRoleData>,
) => createQueryKey('roleServicesGetRole', options);

/**
 * Get role by ID
 */
export const roleServicesGetRoleOptions = (
  options: Options<RoleServicesGetRoleData>,
) =>
  queryOptions<
    RoleServicesGetRoleResponse,
    AxiosError<RoleServicesGetRoleError>,
    RoleServicesGetRoleResponse,
    ReturnType<typeof roleServicesGetRoleQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await roleServicesGetRole({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: roleServicesGetRoleQueryKey(options),
  });

/**
 * Update role
 */
export const roleServicesUpdateRoleMutation = (
  options?: Partial<Options<RoleServicesUpdateRoleData>>,
): UseMutationOptions<
  RoleServicesUpdateRoleResponse,
  AxiosError<RoleServicesUpdateRoleError>,
  Options<RoleServicesUpdateRoleData>
> => {
  const mutationOptions: UseMutationOptions<
    RoleServicesUpdateRoleResponse,
    AxiosError<RoleServicesUpdateRoleError>,
    Options<RoleServicesUpdateRoleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await roleServicesUpdateRole({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const roleServicesGetRolePermissionsQueryKey = (
  options: Options<RoleServicesGetRolePermissionsData>,
) => createQueryKey('roleServicesGetRolePermissions', options);

/**
 * Get role permissions
 */
export const roleServicesGetRolePermissionsOptions = (
  options: Options<RoleServicesGetRolePermissionsData>,
) =>
  queryOptions<
    RoleServicesGetRolePermissionsResponse,
    AxiosError<RoleServicesGetRolePermissionsError>,
    RoleServicesGetRolePermissionsResponse,
    ReturnType<typeof roleServicesGetRolePermissionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await roleServicesGetRolePermissions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: roleServicesGetRolePermissionsQueryKey(options),
  });

/**
 * Revoke permission from role
 */
export const roleServicesRevokePermissionFromRoleMutation = (
  options?: Partial<Options<RoleServicesRevokePermissionFromRoleData>>,
): UseMutationOptions<
  RoleServicesRevokePermissionFromRoleResponse,
  AxiosError<RoleServicesRevokePermissionFromRoleError>,
  Options<RoleServicesRevokePermissionFromRoleData>
> => {
  const mutationOptions: UseMutationOptions<
    RoleServicesRevokePermissionFromRoleResponse,
    AxiosError<RoleServicesRevokePermissionFromRoleError>,
    Options<RoleServicesRevokePermissionFromRoleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await roleServicesRevokePermissionFromRole({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete permission
 */
export const permissionServicesDeletePermissionMutation = (
  options?: Partial<Options<PermissionServicesDeletePermissionData>>,
): UseMutationOptions<
  PermissionServicesDeletePermissionResponse,
  AxiosError<PermissionServicesDeletePermissionError>,
  Options<PermissionServicesDeletePermissionData>
> => {
  const mutationOptions: UseMutationOptions<
    PermissionServicesDeletePermissionResponse,
    AxiosError<PermissionServicesDeletePermissionError>,
    Options<PermissionServicesDeletePermissionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await permissionServicesDeletePermission({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update permission
 */
export const permissionServicesUpdatePermissionMutation = (
  options?: Partial<Options<PermissionServicesUpdatePermissionData>>,
): UseMutationOptions<
  PermissionServicesUpdatePermissionResponse,
  AxiosError<PermissionServicesUpdatePermissionError>,
  Options<PermissionServicesUpdatePermissionData>
> => {
  const mutationOptions: UseMutationOptions<
    PermissionServicesUpdatePermissionResponse,
    AxiosError<PermissionServicesUpdatePermissionError>,
    Options<PermissionServicesUpdatePermissionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await permissionServicesUpdatePermission({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const userServicesGetUsersQueryKey = (
  options?: Options<UserServicesGetUsersData>,
) => createQueryKey('userServicesGetUsers', options);

/**
 * Get all users
 */
export const userServicesGetUsersOptions = (
  options?: Options<UserServicesGetUsersData>,
) =>
  queryOptions<
    UserServicesGetUsersResponse,
    AxiosError<UserServicesGetUsersError>,
    UserServicesGetUsersResponse,
    ReturnType<typeof userServicesGetUsersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userServicesGetUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: userServicesGetUsersQueryKey(options),
  });

/**
 * Create new user
 */
export const userServicesCreateUserMutation = (
  options?: Partial<Options<UserServicesCreateUserData>>,
): UseMutationOptions<
  UserServicesCreateUserResponse,
  AxiosError<UserServicesCreateUserError>,
  Options<UserServicesCreateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    UserServicesCreateUserResponse,
    AxiosError<UserServicesCreateUserError>,
    Options<UserServicesCreateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await userServicesCreateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete user
 */
export const userServicesDeleteUserMutation = (
  options?: Partial<Options<UserServicesDeleteUserData>>,
): UseMutationOptions<
  UserServicesDeleteUserResponse,
  AxiosError<UserServicesDeleteUserError>,
  Options<UserServicesDeleteUserData>
> => {
  const mutationOptions: UseMutationOptions<
    UserServicesDeleteUserResponse,
    AxiosError<UserServicesDeleteUserError>,
    Options<UserServicesDeleteUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await userServicesDeleteUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const userServicesGetUserQueryKey = (
  options: Options<UserServicesGetUserData>,
) => createQueryKey('userServicesGetUser', options);

/**
 * Get user by ID
 */
export const userServicesGetUserOptions = (
  options: Options<UserServicesGetUserData>,
) =>
  queryOptions<
    UserServicesGetUserResponse,
    AxiosError<UserServicesGetUserError>,
    UserServicesGetUserResponse,
    ReturnType<typeof userServicesGetUserQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await userServicesGetUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: userServicesGetUserQueryKey(options),
  });

/**
 * Update user
 */
export const userServicesUpdateUserMutation = (
  options?: Partial<Options<UserServicesUpdateUserData>>,
): UseMutationOptions<
  UserServicesUpdateUserResponse,
  AxiosError<UserServicesUpdateUserError>,
  Options<UserServicesUpdateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    UserServicesUpdateUserResponse,
    AxiosError<UserServicesUpdateUserError>,
    Options<UserServicesUpdateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await userServicesUpdateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
