// ── Module Permission Constants ────────────────────────────────────────────────
export {
  USER_PERMISSIONS,
  USER_PERMISSION_DEFINITIONS,
} from './user';

export {
  COMPANY_PERMISSIONS,
  COMPANY_PERMISSION_DEFINITIONS,
  COMPANY_BRANCH_PERMISSIONS,
  COMPANY_BRANCH_PERMISSION_DEFINITIONS,
  COMPANY_MEMBER_PERMISSIONS,
  COMPANY_MEMBER_PERMISSION_DEFINITIONS,
} from './company';

export { ROLE_PERMISSIONS, ROLE_PERMISSION_DEFINITIONS } from './role';

export {
  PERMISSION_PERMISSIONS,
  PERMISSION_PERMISSION_DEFINITIONS,
} from './permission';

export {
  FEATURE_PERMISSIONS,
  FEATURE_PERMISSION_DEFINITIONS,
  COMPANY_FEATURE_PERMISSIONS,
  COMPANY_FEATURE_PERMISSION_DEFINITIONS,
  ROLE_FEATURE_PERMISSIONS,
  ROLE_FEATURE_PERMISSION_DEFINITIONS,
} from './feature';

export {
  WORK_SCHEDULE_PERMISSIONS,
  WORK_SCHEDULE_PERMISSION_DEFINITIONS,
  WORK_SHIFT_PERMISSIONS,
  WORK_SHIFT_PERMISSION_DEFINITIONS,
  ATTENDANCE_POLICY_PERMISSIONS,
  ATTENDANCE_POLICY_PERMISSION_DEFINITIONS,
  ATTENDANCE_CHECKPOINT_PERMISSIONS,
  ATTENDANCE_CHECKPOINT_PERMISSION_DEFINITIONS,
  ATTENDANCE_LOCATION_PERMISSIONS,
  ATTENDANCE_LOCATION_PERMISSION_DEFINITIONS,
  ROLE_WORK_SCHEDULE_PERMISSIONS,
  ROLE_WORK_SCHEDULE_PERMISSION_DEFINITIONS,
  ATTENDANCE_RECORD_PERMISSIONS,
  ATTENDANCE_RECORD_PERMISSION_DEFINITIONS,
  ATTENDANCE_LOG_PERMISSIONS,
  ATTENDANCE_LOG_PERMISSION_DEFINITIONS,
} from './attendance';

export {
  LEAVE_REQUEST_PERMISSIONS,
  LEAVE_REQUEST_PERMISSION_DEFINITIONS,
} from './leave';

export { DEFAULT_ROLE_PERMISSIONS } from './role-mappings';
export type { PermissionDefinition, RolePermissionMapping } from './types';

// ── Aggregated Namespace & Union Array ────────────────────────────────────────

import {
  USER_PERMISSIONS,
  USER_PERMISSION_DEFINITIONS,
} from './user';
import {
  COMPANY_PERMISSIONS,
  COMPANY_PERMISSION_DEFINITIONS,
  COMPANY_BRANCH_PERMISSIONS,
  COMPANY_BRANCH_PERMISSION_DEFINITIONS,
  COMPANY_MEMBER_PERMISSIONS,
  COMPANY_MEMBER_PERMISSION_DEFINITIONS,
} from './company';
import { ROLE_PERMISSIONS, ROLE_PERMISSION_DEFINITIONS } from './role';
import {
  PERMISSION_PERMISSIONS,
  PERMISSION_PERMISSION_DEFINITIONS,
} from './permission';
import {
  FEATURE_PERMISSIONS,
  FEATURE_PERMISSION_DEFINITIONS,
  COMPANY_FEATURE_PERMISSIONS,
  COMPANY_FEATURE_PERMISSION_DEFINITIONS,
  ROLE_FEATURE_PERMISSIONS,
  ROLE_FEATURE_PERMISSION_DEFINITIONS,
} from './feature';
import {
  WORK_SCHEDULE_PERMISSIONS,
  WORK_SCHEDULE_PERMISSION_DEFINITIONS,
  WORK_SHIFT_PERMISSIONS,
  WORK_SHIFT_PERMISSION_DEFINITIONS,
  ATTENDANCE_POLICY_PERMISSIONS,
  ATTENDANCE_POLICY_PERMISSION_DEFINITIONS,
  ATTENDANCE_CHECKPOINT_PERMISSIONS,
  ATTENDANCE_CHECKPOINT_PERMISSION_DEFINITIONS,
  ATTENDANCE_LOCATION_PERMISSIONS,
  ATTENDANCE_LOCATION_PERMISSION_DEFINITIONS,
  ROLE_WORK_SCHEDULE_PERMISSIONS,
  ROLE_WORK_SCHEDULE_PERMISSION_DEFINITIONS,
  ATTENDANCE_RECORD_PERMISSIONS,
  ATTENDANCE_RECORD_PERMISSION_DEFINITIONS,
  ATTENDANCE_LOG_PERMISSIONS,
  ATTENDANCE_LOG_PERMISSION_DEFINITIONS,
} from './attendance';
import {
  LEAVE_REQUEST_PERMISSIONS,
  LEAVE_REQUEST_PERMISSION_DEFINITIONS,
} from './leave';

/**
 * Unified namespace of all module permission action constants.
 *
 * @example
 * import { PERMISSIONS } from '@repo/domains/constants';
 * const action = PERMISSIONS.USER.READ; // 'user:read'
 */
export const PERMISSIONS = {
  USER: USER_PERMISSIONS,
  COMPANY: COMPANY_PERMISSIONS,
  COMPANY_BRANCH: COMPANY_BRANCH_PERMISSIONS,
  COMPANY_MEMBER: COMPANY_MEMBER_PERMISSIONS,
  ROLE: ROLE_PERMISSIONS,
  PERMISSION: PERMISSION_PERMISSIONS,
  FEATURE: FEATURE_PERMISSIONS,
  COMPANY_FEATURE: COMPANY_FEATURE_PERMISSIONS,
  ROLE_FEATURE: ROLE_FEATURE_PERMISSIONS,
  WORK_SCHEDULE: WORK_SCHEDULE_PERMISSIONS,
  WORK_SHIFT: WORK_SHIFT_PERMISSIONS,
  ATTENDANCE_POLICY: ATTENDANCE_POLICY_PERMISSIONS,
  ATTENDANCE_CHECKPOINT: ATTENDANCE_CHECKPOINT_PERMISSIONS,
  ATTENDANCE_LOCATION: ATTENDANCE_LOCATION_PERMISSIONS,
  ROLE_WORK_SCHEDULE: ROLE_WORK_SCHEDULE_PERMISSIONS,
  ATTENDANCE_RECORD: ATTENDANCE_RECORD_PERMISSIONS,
  ATTENDANCE_LOG: ATTENDANCE_LOG_PERMISSIONS,
  LEAVE_REQUEST: LEAVE_REQUEST_PERMISSIONS,
} as const;

/**
 * Array of every permission definition across all modules (80 total).
 * Useful for seeding the database or building UI permission pickers.
 */
export const ALL_PERMISSIONS = [
  ...USER_PERMISSION_DEFINITIONS,
  ...COMPANY_PERMISSION_DEFINITIONS,
  ...COMPANY_BRANCH_PERMISSION_DEFINITIONS,
  ...COMPANY_MEMBER_PERMISSION_DEFINITIONS,
  ...ROLE_PERMISSION_DEFINITIONS,
  ...PERMISSION_PERMISSION_DEFINITIONS,
  ...FEATURE_PERMISSION_DEFINITIONS,
  ...COMPANY_FEATURE_PERMISSION_DEFINITIONS,
  ...ROLE_FEATURE_PERMISSION_DEFINITIONS,
  ...WORK_SCHEDULE_PERMISSION_DEFINITIONS,
  ...WORK_SHIFT_PERMISSION_DEFINITIONS,
  ...ATTENDANCE_POLICY_PERMISSION_DEFINITIONS,
  ...ATTENDANCE_CHECKPOINT_PERMISSION_DEFINITIONS,
  ...ATTENDANCE_LOCATION_PERMISSION_DEFINITIONS,
  ...ROLE_WORK_SCHEDULE_PERMISSION_DEFINITIONS,
  ...ATTENDANCE_RECORD_PERMISSION_DEFINITIONS,
  ...ATTENDANCE_LOG_PERMISSION_DEFINITIONS,
  ...LEAVE_REQUEST_PERMISSION_DEFINITIONS,
] as const;

/**
 * Union of all valid permission action strings in the system.
 * Use this as the type for `action` parameters in authorization checks.
 */
export type PermissionAction = (typeof ALL_PERMISSIONS)[number]['action'];
