import type { RolePermissionMapping } from './types';
import { USER_PERMISSIONS } from './user';
import {
  COMPANY_PERMISSIONS,
  COMPANY_BRANCH_PERMISSIONS,
  COMPANY_MEMBER_PERMISSIONS,
} from './company';
import { ROLE_PERMISSIONS } from './role';
import { PERMISSION_PERMISSIONS } from './permission';
import {
  FEATURE_PERMISSIONS,
  COMPANY_FEATURE_PERMISSIONS,
  ROLE_FEATURE_PERMISSIONS,
} from './feature';
import {
  WORK_SCHEDULE_PERMISSIONS,
  WORK_SHIFT_PERMISSIONS,
  ATTENDANCE_POLICY_PERMISSIONS,
  ATTENDANCE_CHECKPOINT_PERMISSIONS,
  ATTENDANCE_LOCATION_PERMISSIONS,
  ROLE_WORK_SCHEDULE_PERMISSIONS,
  ATTENDANCE_RECORD_PERMISSIONS,
  ATTENDANCE_LOG_PERMISSIONS,
} from './attendance';
import { LEAVE_REQUEST_PERMISSIONS } from './leave';

// ============================================================
// DEFAULT ROLE ↔ PERMISSION MAPPINGS
// ============================================================

/**
 * SUPER_ADMIN — Full access to every permission in the system.
 */
const SUPER_ADMIN_PERMISSIONS: readonly string[] = [
  // User
  USER_PERMISSIONS.CREATE,
  USER_PERMISSIONS.READ,
  USER_PERMISSIONS.UPDATE,
  USER_PERMISSIONS.DELETE,

  // Company
  COMPANY_PERMISSIONS.CREATE,
  COMPANY_PERMISSIONS.READ,
  COMPANY_PERMISSIONS.UPDATE,
  COMPANY_PERMISSIONS.DELETE,

  // Company Branch
  COMPANY_BRANCH_PERMISSIONS.CREATE,
  COMPANY_BRANCH_PERMISSIONS.READ,
  COMPANY_BRANCH_PERMISSIONS.UPDATE,
  COMPANY_BRANCH_PERMISSIONS.DELETE,

  // Company Member
  COMPANY_MEMBER_PERMISSIONS.CREATE,
  COMPANY_MEMBER_PERMISSIONS.READ,
  COMPANY_MEMBER_PERMISSIONS.UPDATE,
  COMPANY_MEMBER_PERMISSIONS.DELETE,

  // Role
  ROLE_PERMISSIONS.CREATE,
  ROLE_PERMISSIONS.READ,
  ROLE_PERMISSIONS.UPDATE,
  ROLE_PERMISSIONS.DELETE,

  // Permission
  PERMISSION_PERMISSIONS.CREATE,
  PERMISSION_PERMISSIONS.READ,
  PERMISSION_PERMISSIONS.UPDATE,
  PERMISSION_PERMISSIONS.DELETE,
  PERMISSION_PERMISSIONS.ASSIGN,
  PERMISSION_PERMISSIONS.REVOKE,

  // Feature
  FEATURE_PERMISSIONS.CREATE,
  FEATURE_PERMISSIONS.READ,
  FEATURE_PERMISSIONS.UPDATE,
  FEATURE_PERMISSIONS.DELETE,
  FEATURE_PERMISSIONS.TOGGLE,

  // Company Feature
  COMPANY_FEATURE_PERMISSIONS.CREATE,
  COMPANY_FEATURE_PERMISSIONS.READ,
  COMPANY_FEATURE_PERMISSIONS.UPDATE,
  COMPANY_FEATURE_PERMISSIONS.DELETE,
  COMPANY_FEATURE_PERMISSIONS.TOGGLE,

  // Role Feature
  ROLE_FEATURE_PERMISSIONS.CREATE,
  ROLE_FEATURE_PERMISSIONS.READ,
  ROLE_FEATURE_PERMISSIONS.UPDATE,
  ROLE_FEATURE_PERMISSIONS.DELETE,
  ROLE_FEATURE_PERMISSIONS.TOGGLE,
  ROLE_FEATURE_PERMISSIONS.CHECK,

  // Work Schedule
  WORK_SCHEDULE_PERMISSIONS.CREATE,
  WORK_SCHEDULE_PERMISSIONS.READ,
  WORK_SCHEDULE_PERMISSIONS.UPDATE,
  WORK_SCHEDULE_PERMISSIONS.DELETE,

  // Work Shift
  WORK_SHIFT_PERMISSIONS.CREATE,
  WORK_SHIFT_PERMISSIONS.READ,
  WORK_SHIFT_PERMISSIONS.UPDATE,
  WORK_SHIFT_PERMISSIONS.DELETE,

  // Attendance Policy
  ATTENDANCE_POLICY_PERMISSIONS.CREATE,
  ATTENDANCE_POLICY_PERMISSIONS.READ,
  ATTENDANCE_POLICY_PERMISSIONS.UPDATE,
  ATTENDANCE_POLICY_PERMISSIONS.DELETE,

  // Attendance Checkpoint
  ATTENDANCE_CHECKPOINT_PERMISSIONS.CREATE,
  ATTENDANCE_CHECKPOINT_PERMISSIONS.READ,
  ATTENDANCE_CHECKPOINT_PERMISSIONS.UPDATE,
  ATTENDANCE_CHECKPOINT_PERMISSIONS.DELETE,

  // Attendance Location
  ATTENDANCE_LOCATION_PERMISSIONS.CREATE,
  ATTENDANCE_LOCATION_PERMISSIONS.READ,
  ATTENDANCE_LOCATION_PERMISSIONS.UPDATE,
  ATTENDANCE_LOCATION_PERMISSIONS.DELETE,

  // Role Work Schedule
  ROLE_WORK_SCHEDULE_PERMISSIONS.CREATE,
  ROLE_WORK_SCHEDULE_PERMISSIONS.READ,
  ROLE_WORK_SCHEDULE_PERMISSIONS.UPDATE,
  ROLE_WORK_SCHEDULE_PERMISSIONS.DELETE,

  // Attendance Record
  ATTENDANCE_RECORD_PERMISSIONS.CREATE,
  ATTENDANCE_RECORD_PERMISSIONS.READ,
  ATTENDANCE_RECORD_PERMISSIONS.UPDATE,
  ATTENDANCE_RECORD_PERMISSIONS.DELETE,
  ATTENDANCE_RECORD_PERMISSIONS.APPROVE,

  // Attendance Log
  ATTENDANCE_LOG_PERMISSIONS.CREATE,
  ATTENDANCE_LOG_PERMISSIONS.READ,
  ATTENDANCE_LOG_PERMISSIONS.DELETE,
  ATTENDANCE_LOG_PERMISSIONS.MANUAL_CHECK,

  // Leave Request
  LEAVE_REQUEST_PERMISSIONS.CREATE,
  LEAVE_REQUEST_PERMISSIONS.READ,
  LEAVE_REQUEST_PERMISSIONS.UPDATE,
  LEAVE_REQUEST_PERMISSIONS.DELETE,
  LEAVE_REQUEST_PERMISSIONS.APPROVE,
] as const;

/**
 * OWNER — Full company administrative access.
 * Excludes: platform-level feature admin (feature:create/update/delete/toggle).
 */
const OWNER_PERMISSIONS: readonly string[] = [
  // User (full)
  USER_PERMISSIONS.CREATE,
  USER_PERMISSIONS.READ,
  USER_PERMISSIONS.UPDATE,
  USER_PERMISSIONS.DELETE,

  // Company (full)
  COMPANY_PERMISSIONS.CREATE,
  COMPANY_PERMISSIONS.READ,
  COMPANY_PERMISSIONS.UPDATE,
  COMPANY_PERMISSIONS.DELETE,

  // Company Branch (full)
  COMPANY_BRANCH_PERMISSIONS.CREATE,
  COMPANY_BRANCH_PERMISSIONS.READ,
  COMPANY_BRANCH_PERMISSIONS.UPDATE,
  COMPANY_BRANCH_PERMISSIONS.DELETE,

  // Company Member (full)
  COMPANY_MEMBER_PERMISSIONS.CREATE,
  COMPANY_MEMBER_PERMISSIONS.READ,
  COMPANY_MEMBER_PERMISSIONS.UPDATE,
  COMPANY_MEMBER_PERMISSIONS.DELETE,

  // Role (full)
  ROLE_PERMISSIONS.CREATE,
  ROLE_PERMISSIONS.READ,
  ROLE_PERMISSIONS.UPDATE,
  ROLE_PERMISSIONS.DELETE,

  // Permission (read + assign + revoke — no modify)
  PERMISSION_PERMISSIONS.READ,
  PERMISSION_PERMISSIONS.ASSIGN,
  PERMISSION_PERMISSIONS.REVOKE,

  // Feature (read only)
  FEATURE_PERMISSIONS.READ,

  // Company Feature (read only)
  COMPANY_FEATURE_PERMISSIONS.READ,

  // Role Feature (full)
  ROLE_FEATURE_PERMISSIONS.CREATE,
  ROLE_FEATURE_PERMISSIONS.READ,
  ROLE_FEATURE_PERMISSIONS.UPDATE,
  ROLE_FEATURE_PERMISSIONS.DELETE,
  ROLE_FEATURE_PERMISSIONS.TOGGLE,
  ROLE_FEATURE_PERMISSIONS.CHECK,

  // Work Schedule (full)
  WORK_SCHEDULE_PERMISSIONS.CREATE,
  WORK_SCHEDULE_PERMISSIONS.READ,
  WORK_SCHEDULE_PERMISSIONS.UPDATE,
  WORK_SCHEDULE_PERMISSIONS.DELETE,

  // Work Shift (full)
  WORK_SHIFT_PERMISSIONS.CREATE,
  WORK_SHIFT_PERMISSIONS.READ,
  WORK_SHIFT_PERMISSIONS.UPDATE,
  WORK_SHIFT_PERMISSIONS.DELETE,

  // Attendance Policy (full)
  ATTENDANCE_POLICY_PERMISSIONS.CREATE,
  ATTENDANCE_POLICY_PERMISSIONS.READ,
  ATTENDANCE_POLICY_PERMISSIONS.UPDATE,
  ATTENDANCE_POLICY_PERMISSIONS.DELETE,

  // Attendance Checkpoint (full)
  ATTENDANCE_CHECKPOINT_PERMISSIONS.CREATE,
  ATTENDANCE_CHECKPOINT_PERMISSIONS.READ,
  ATTENDANCE_CHECKPOINT_PERMISSIONS.UPDATE,
  ATTENDANCE_CHECKPOINT_PERMISSIONS.DELETE,

  // Attendance Location (full)
  ATTENDANCE_LOCATION_PERMISSIONS.CREATE,
  ATTENDANCE_LOCATION_PERMISSIONS.READ,
  ATTENDANCE_LOCATION_PERMISSIONS.UPDATE,
  ATTENDANCE_LOCATION_PERMISSIONS.DELETE,

  // Role Work Schedule (full)
  ROLE_WORK_SCHEDULE_PERMISSIONS.CREATE,
  ROLE_WORK_SCHEDULE_PERMISSIONS.READ,
  ROLE_WORK_SCHEDULE_PERMISSIONS.UPDATE,
  ROLE_WORK_SCHEDULE_PERMISSIONS.DELETE,

  // Attendance Record (full)
  ATTENDANCE_RECORD_PERMISSIONS.CREATE,
  ATTENDANCE_RECORD_PERMISSIONS.READ,
  ATTENDANCE_RECORD_PERMISSIONS.UPDATE,
  ATTENDANCE_RECORD_PERMISSIONS.DELETE,
  ATTENDANCE_RECORD_PERMISSIONS.APPROVE,

  // Attendance Log (full)
  ATTENDANCE_LOG_PERMISSIONS.CREATE,
  ATTENDANCE_LOG_PERMISSIONS.READ,
  ATTENDANCE_LOG_PERMISSIONS.DELETE,
  ATTENDANCE_LOG_PERMISSIONS.MANUAL_CHECK,

  // Leave Request (full)
  LEAVE_REQUEST_PERMISSIONS.CREATE,
  LEAVE_REQUEST_PERMISSIONS.READ,
  LEAVE_REQUEST_PERMISSIONS.UPDATE,
  LEAVE_REQUEST_PERMISSIONS.DELETE,
  LEAVE_REQUEST_PERMISSIONS.APPROVE,
] as const;

/**
 * ADMIN — Administrative access with management privileges.
 * Excludes: company:create/delete, platform feature admin.
 */
const ADMIN_PERMISSIONS: readonly string[] = [
  // User (read only)
  USER_PERMISSIONS.READ,

  // Company (read + update — no create/delete)
  COMPANY_PERMISSIONS.READ,
  COMPANY_PERMISSIONS.UPDATE,

  // Company Branch (full)
  COMPANY_BRANCH_PERMISSIONS.CREATE,
  COMPANY_BRANCH_PERMISSIONS.READ,
  COMPANY_BRANCH_PERMISSIONS.UPDATE,
  COMPANY_BRANCH_PERMISSIONS.DELETE,

  // Company Member (full)
  COMPANY_MEMBER_PERMISSIONS.CREATE,
  COMPANY_MEMBER_PERMISSIONS.READ,
  COMPANY_MEMBER_PERMISSIONS.UPDATE,
  COMPANY_MEMBER_PERMISSIONS.DELETE,

  // Role (read only)
  ROLE_PERMISSIONS.READ,

  // Permission (read only)
  PERMISSION_PERMISSIONS.READ,

  // Feature (read only)
  FEATURE_PERMISSIONS.READ,

  // Company Feature (read only)
  COMPANY_FEATURE_PERMISSIONS.READ,

  // Role Feature (full)
  ROLE_FEATURE_PERMISSIONS.CREATE,
  ROLE_FEATURE_PERMISSIONS.READ,
  ROLE_FEATURE_PERMISSIONS.UPDATE,
  ROLE_FEATURE_PERMISSIONS.DELETE,
  ROLE_FEATURE_PERMISSIONS.TOGGLE,
  ROLE_FEATURE_PERMISSIONS.CHECK,

  // Work Schedule (full)
  WORK_SCHEDULE_PERMISSIONS.CREATE,
  WORK_SCHEDULE_PERMISSIONS.READ,
  WORK_SCHEDULE_PERMISSIONS.UPDATE,
  WORK_SCHEDULE_PERMISSIONS.DELETE,

  // Work Shift (full)
  WORK_SHIFT_PERMISSIONS.CREATE,
  WORK_SHIFT_PERMISSIONS.READ,
  WORK_SHIFT_PERMISSIONS.UPDATE,
  WORK_SHIFT_PERMISSIONS.DELETE,

  // Attendance Policy (full)
  ATTENDANCE_POLICY_PERMISSIONS.CREATE,
  ATTENDANCE_POLICY_PERMISSIONS.READ,
  ATTENDANCE_POLICY_PERMISSIONS.UPDATE,
  ATTENDANCE_POLICY_PERMISSIONS.DELETE,

  // Attendance Checkpoint (full)
  ATTENDANCE_CHECKPOINT_PERMISSIONS.CREATE,
  ATTENDANCE_CHECKPOINT_PERMISSIONS.READ,
  ATTENDANCE_CHECKPOINT_PERMISSIONS.UPDATE,
  ATTENDANCE_CHECKPOINT_PERMISSIONS.DELETE,

  // Attendance Location (full)
  ATTENDANCE_LOCATION_PERMISSIONS.CREATE,
  ATTENDANCE_LOCATION_PERMISSIONS.READ,
  ATTENDANCE_LOCATION_PERMISSIONS.UPDATE,
  ATTENDANCE_LOCATION_PERMISSIONS.DELETE,

  // Role Work Schedule (full)
  ROLE_WORK_SCHEDULE_PERMISSIONS.CREATE,
  ROLE_WORK_SCHEDULE_PERMISSIONS.READ,
  ROLE_WORK_SCHEDULE_PERMISSIONS.UPDATE,
  ROLE_WORK_SCHEDULE_PERMISSIONS.DELETE,

  // Attendance Record (full)
  ATTENDANCE_RECORD_PERMISSIONS.CREATE,
  ATTENDANCE_RECORD_PERMISSIONS.READ,
  ATTENDANCE_RECORD_PERMISSIONS.UPDATE,
  ATTENDANCE_RECORD_PERMISSIONS.DELETE,
  ATTENDANCE_RECORD_PERMISSIONS.APPROVE,

  // Attendance Log (full)
  ATTENDANCE_LOG_PERMISSIONS.CREATE,
  ATTENDANCE_LOG_PERMISSIONS.READ,
  ATTENDANCE_LOG_PERMISSIONS.DELETE,
  ATTENDANCE_LOG_PERMISSIONS.MANUAL_CHECK,

  // Leave Request (full)
  LEAVE_REQUEST_PERMISSIONS.CREATE,
  LEAVE_REQUEST_PERMISSIONS.READ,
  LEAVE_REQUEST_PERMISSIONS.UPDATE,
  LEAVE_REQUEST_PERMISSIONS.DELETE,
  LEAVE_REQUEST_PERMISSIONS.APPROVE,
] as const;

/**
 * MEMBER — Standard member access with self-service attendance and leave.
 */
const MEMBER_PERMISSIONS: readonly string[] = [
  // User (read)
  USER_PERMISSIONS.READ,

  // Company (read)
  COMPANY_PERMISSIONS.READ,

  // Company Branch (read)
  COMPANY_BRANCH_PERMISSIONS.READ,

  // Company Member (read)
  COMPANY_MEMBER_PERMISSIONS.READ,

  // Role (read)
  ROLE_PERMISSIONS.READ,

  // Permission (read)
  PERMISSION_PERMISSIONS.READ,

  // Feature (read)
  FEATURE_PERMISSIONS.READ,

  // Company Feature (read)
  COMPANY_FEATURE_PERMISSIONS.READ,

  // Role Feature (read + check)
  ROLE_FEATURE_PERMISSIONS.READ,
  ROLE_FEATURE_PERMISSIONS.CHECK,

  // Work Schedule (read)
  WORK_SCHEDULE_PERMISSIONS.READ,

  // Work Shift (read)
  WORK_SHIFT_PERMISSIONS.READ,

  // Attendance Policy (read)
  ATTENDANCE_POLICY_PERMISSIONS.READ,

  // Attendance Checkpoint (read)
  ATTENDANCE_CHECKPOINT_PERMISSIONS.READ,

  // Attendance Location (read)
  ATTENDANCE_LOCATION_PERMISSIONS.READ,

  // Role Work Schedule (read)
  ROLE_WORK_SCHEDULE_PERMISSIONS.READ,

  // Attendance Record (read)
  ATTENDANCE_RECORD_PERMISSIONS.READ,

  // Attendance Log (create + read)
  ATTENDANCE_LOG_PERMISSIONS.CREATE,
  ATTENDANCE_LOG_PERMISSIONS.READ,

  // Leave Request (create + read + update + delete — no approve)
  LEAVE_REQUEST_PERMISSIONS.CREATE,
  LEAVE_REQUEST_PERMISSIONS.READ,
  LEAVE_REQUEST_PERMISSIONS.UPDATE,
  LEAVE_REQUEST_PERMISSIONS.DELETE,
] as const;

/**
 * VIEWER — Read-only access to all company resources.
 */
const VIEWER_PERMISSIONS: readonly string[] = [
  // User (read)
  USER_PERMISSIONS.READ,

  // Company (read)
  COMPANY_PERMISSIONS.READ,

  // Company Branch (read)
  COMPANY_BRANCH_PERMISSIONS.READ,

  // Company Member (read)
  COMPANY_MEMBER_PERMISSIONS.READ,

  // Role (read)
  ROLE_PERMISSIONS.READ,

  // Permission (read)
  PERMISSION_PERMISSIONS.READ,

  // Feature (read)
  FEATURE_PERMISSIONS.READ,

  // Company Feature (read)
  COMPANY_FEATURE_PERMISSIONS.READ,

  // Role Feature (read)
  ROLE_FEATURE_PERMISSIONS.READ,

  // Work Schedule (read)
  WORK_SCHEDULE_PERMISSIONS.READ,

  // Work Shift (read)
  WORK_SHIFT_PERMISSIONS.READ,

  // Attendance Policy (read)
  ATTENDANCE_POLICY_PERMISSIONS.READ,

  // Attendance Checkpoint (read)
  ATTENDANCE_CHECKPOINT_PERMISSIONS.READ,

  // Attendance Location (read)
  ATTENDANCE_LOCATION_PERMISSIONS.READ,

  // Role Work Schedule (read)
  ROLE_WORK_SCHEDULE_PERMISSIONS.READ,

  // Attendance Record (read)
  ATTENDANCE_RECORD_PERMISSIONS.READ,

  // Attendance Log (read)
  ATTENDANCE_LOG_PERMISSIONS.READ,

  // Leave Request (read)
  LEAVE_REQUEST_PERMISSIONS.READ,
] as const;

// ============================================================
// EXPORTED MAPPINGS
// ============================================================

export const DEFAULT_ROLE_PERMISSIONS: readonly RolePermissionMapping[] = [
  { roleType: 'SUPER_ADMIN', actions: SUPER_ADMIN_PERMISSIONS },
  { roleType: 'OWNER', actions: OWNER_PERMISSIONS },
  { roleType: 'ADMIN', actions: ADMIN_PERMISSIONS },
  { roleType: 'MEMBER', actions: MEMBER_PERMISSIONS },
  { roleType: 'VIEWER', actions: VIEWER_PERMISSIONS },
];
