// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from './client';
import { client } from './client.gen';
import type {
  CompanyServicesAddCompanyMemberData,
  CompanyServicesAddCompanyMemberErrors,
  CompanyServicesAddCompanyMemberResponses,
  CompanyServicesCreateCompanyBranchData,
  CompanyServicesCreateCompanyBranchErrors,
  CompanyServicesCreateCompanyBranchResponses,
  CompanyServicesCreateCompanyData,
  CompanyServicesCreateCompanyErrors,
  CompanyServicesCreateCompanyResponses,
  CompanyServicesDeleteCompanyBranchData,
  CompanyServicesDeleteCompanyBranchErrors,
  CompanyServicesDeleteCompanyBranchResponses,
  CompanyServicesDeleteCompanyData,
  CompanyServicesDeleteCompanyErrors,
  CompanyServicesDeleteCompanyResponses,
  CompanyServicesGetCompaniesData,
  CompanyServicesGetCompaniesErrors,
  CompanyServicesGetCompaniesResponses,
  CompanyServicesGetCompanyBranchData,
  CompanyServicesGetCompanyBranchErrors,
  CompanyServicesGetCompanyBranchesData,
  CompanyServicesGetCompanyBranchesErrors,
  CompanyServicesGetCompanyBranchesResponses,
  CompanyServicesGetCompanyBranchResponses,
  CompanyServicesGetCompanyBySlugData,
  CompanyServicesGetCompanyBySlugErrors,
  CompanyServicesGetCompanyBySlugResponses,
  CompanyServicesGetCompanyData,
  CompanyServicesGetCompanyErrors,
  CompanyServicesGetCompanyMembersData,
  CompanyServicesGetCompanyMembersErrors,
  CompanyServicesGetCompanyMembersResponses,
  CompanyServicesGetCompanyResponses,
  CompanyServicesRemoveCompanyMemberData,
  CompanyServicesRemoveCompanyMemberErrors,
  CompanyServicesRemoveCompanyMemberResponses,
  CompanyServicesSwitchActiveCompanyData,
  CompanyServicesSwitchActiveCompanyErrors,
  CompanyServicesSwitchActiveCompanyResponses,
  CompanyServicesUpdateCompanyBranchData,
  CompanyServicesUpdateCompanyBranchErrors,
  CompanyServicesUpdateCompanyBranchResponses,
  CompanyServicesUpdateCompanyData,
  CompanyServicesUpdateCompanyErrors,
  CompanyServicesUpdateCompanyMemberData,
  CompanyServicesUpdateCompanyMemberErrors,
  CompanyServicesUpdateCompanyMemberResponses,
  CompanyServicesUpdateCompanyResponses,
  FeatureServicesAssignCompanyFeatureData,
  FeatureServicesAssignCompanyFeatureErrors,
  FeatureServicesAssignCompanyFeatureResponses,
  FeatureServicesAssignRoleFeatureData,
  FeatureServicesAssignRoleFeatureErrors,
  FeatureServicesAssignRoleFeatureResponses,
  FeatureServicesCheckRoleFeatureAccessData,
  FeatureServicesCheckRoleFeatureAccessErrors,
  FeatureServicesCheckRoleFeatureAccessResponses,
  FeatureServicesCreateFeatureData,
  FeatureServicesCreateFeatureErrors,
  FeatureServicesCreateFeatureResponses,
  FeatureServicesGetCompanyAvailableFeaturesData,
  FeatureServicesGetCompanyAvailableFeaturesErrors,
  FeatureServicesGetCompanyAvailableFeaturesResponses,
  FeatureServicesGetCompanyFeaturesData,
  FeatureServicesGetCompanyFeaturesErrors,
  FeatureServicesGetCompanyFeaturesResponses,
  FeatureServicesGetCompanyRoleFeaturesData,
  FeatureServicesGetCompanyRoleFeaturesErrors,
  FeatureServicesGetCompanyRoleFeaturesResponses,
  FeatureServicesGetFeatureData,
  FeatureServicesGetFeatureErrors,
  FeatureServicesGetFeatureResponses,
  FeatureServicesGetFeaturesData,
  FeatureServicesGetFeaturesErrors,
  FeatureServicesGetFeaturesResponses,
  FeatureServicesGetRoleFeaturesData,
  FeatureServicesGetRoleFeaturesErrors,
  FeatureServicesGetRoleFeaturesResponses,
  FeatureServicesRemoveCompanyFeatureData,
  FeatureServicesRemoveCompanyFeatureErrors,
  FeatureServicesRemoveCompanyFeatureResponses,
  FeatureServicesRevokeRoleFeatureData,
  FeatureServicesRevokeRoleFeatureErrors,
  FeatureServicesRevokeRoleFeatureResponses,
  FeatureServicesToggleCompanyFeatureData,
  FeatureServicesToggleCompanyFeatureErrors,
  FeatureServicesToggleCompanyFeatureResponses,
  FeatureServicesToggleFeatureData,
  FeatureServicesToggleFeatureErrors,
  FeatureServicesToggleFeatureResponses,
  FeatureServicesToggleRoleFeatureData,
  FeatureServicesToggleRoleFeatureErrors,
  FeatureServicesToggleRoleFeatureResponses,
  FeatureServicesUpdateFeatureData,
  FeatureServicesUpdateFeatureErrors,
  FeatureServicesUpdateFeatureResponses,
  PermissionServicesCreatePermissionData,
  PermissionServicesCreatePermissionErrors,
  PermissionServicesCreatePermissionResponses,
  PermissionServicesDeletePermissionData,
  PermissionServicesDeletePermissionErrors,
  PermissionServicesDeletePermissionResponses,
  PermissionServicesGetMyPermissionsData,
  PermissionServicesGetMyPermissionsErrors,
  PermissionServicesGetMyPermissionsResponses,
  PermissionServicesGetPermissionsData,
  PermissionServicesGetPermissionsErrors,
  PermissionServicesGetPermissionsResponses,
  PermissionServicesUpdatePermissionData,
  PermissionServicesUpdatePermissionErrors,
  PermissionServicesUpdatePermissionResponses,
  RoleServicesAssignPermissionToRoleData,
  RoleServicesAssignPermissionToRoleErrors,
  RoleServicesAssignPermissionToRoleResponses,
  RoleServicesCreateRoleData,
  RoleServicesCreateRoleErrors,
  RoleServicesCreateRoleResponses,
  RoleServicesDeleteRoleData,
  RoleServicesDeleteRoleErrors,
  RoleServicesDeleteRoleResponses,
  RoleServicesGetCompanyRolesData,
  RoleServicesGetCompanyRolesErrors,
  RoleServicesGetCompanyRolesResponses,
  RoleServicesGetRoleData,
  RoleServicesGetRoleErrors,
  RoleServicesGetRolePermissionsData,
  RoleServicesGetRolePermissionsErrors,
  RoleServicesGetRolePermissionsResponses,
  RoleServicesGetRoleResponses,
  RoleServicesGetSystemDefaultRolesData,
  RoleServicesGetSystemDefaultRolesErrors,
  RoleServicesGetSystemDefaultRolesResponses,
  RoleServicesRevokePermissionFromRoleData,
  RoleServicesRevokePermissionFromRoleErrors,
  RoleServicesRevokePermissionFromRoleResponses,
  RoleServicesUpdateRoleData,
  RoleServicesUpdateRoleErrors,
  RoleServicesUpdateRoleResponses,
  UserServicesCreateUserData,
  UserServicesCreateUserErrors,
  UserServicesCreateUserResponses,
  UserServicesDeleteUserData,
  UserServicesDeleteUserErrors,
  UserServicesDeleteUserResponses,
  UserServicesGetUserData,
  UserServicesGetUserErrors,
  UserServicesGetUserResponses,
  UserServicesGetUsersData,
  UserServicesGetUsersErrors,
  UserServicesGetUsersResponses,
  UserServicesUpdateUserData,
  UserServicesUpdateUserErrors,
  UserServicesUpdateUserResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get all companies
 */
export const companyServicesGetCompanies = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<CompanyServicesGetCompaniesData, ThrowOnError>,
): RequestResult<
  CompanyServicesGetCompaniesResponses,
  CompanyServicesGetCompaniesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    CompanyServicesGetCompaniesResponses,
    CompanyServicesGetCompaniesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/companies/',
    ...options,
  });

/**
 * Create new company
 */
export const companyServicesCreateCompany = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CompanyServicesCreateCompanyData, ThrowOnError>,
): RequestResult<
  CompanyServicesCreateCompanyResponses,
  CompanyServicesCreateCompanyErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CompanyServicesCreateCompanyResponses,
    CompanyServicesCreateCompanyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/companies/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create company branch
 */
export const companyServicesCreateCompanyBranch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CompanyServicesCreateCompanyBranchData, ThrowOnError>,
): RequestResult<
  CompanyServicesCreateCompanyBranchResponses,
  CompanyServicesCreateCompanyBranchErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CompanyServicesCreateCompanyBranchResponses,
    CompanyServicesCreateCompanyBranchErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/companies/branches',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete company branch
 */
export const companyServicesDeleteCompanyBranch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CompanyServicesDeleteCompanyBranchData, ThrowOnError>,
): RequestResult<
  CompanyServicesDeleteCompanyBranchResponses,
  CompanyServicesDeleteCompanyBranchErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    CompanyServicesDeleteCompanyBranchResponses,
    CompanyServicesDeleteCompanyBranchErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/companies/branches/{id}',
    ...options,
  });

/**
 * Get company branch by ID
 */
export const companyServicesGetCompanyBranch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CompanyServicesGetCompanyBranchData, ThrowOnError>,
): RequestResult<
  CompanyServicesGetCompanyBranchResponses,
  CompanyServicesGetCompanyBranchErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    CompanyServicesGetCompanyBranchResponses,
    CompanyServicesGetCompanyBranchErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/companies/branches/{id}',
    ...options,
  });

/**
 * Update company branch
 */
export const companyServicesUpdateCompanyBranch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CompanyServicesUpdateCompanyBranchData, ThrowOnError>,
): RequestResult<
  CompanyServicesUpdateCompanyBranchResponses,
  CompanyServicesUpdateCompanyBranchErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    CompanyServicesUpdateCompanyBranchResponses,
    CompanyServicesUpdateCompanyBranchErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/companies/branches/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Add company member
 */
export const companyServicesAddCompanyMember = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CompanyServicesAddCompanyMemberData, ThrowOnError>,
): RequestResult<
  CompanyServicesAddCompanyMemberResponses,
  CompanyServicesAddCompanyMemberErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CompanyServicesAddCompanyMemberResponses,
    CompanyServicesAddCompanyMemberErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/companies/members',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove company member
 */
export const companyServicesRemoveCompanyMember = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CompanyServicesRemoveCompanyMemberData, ThrowOnError>,
): RequestResult<
  CompanyServicesRemoveCompanyMemberResponses,
  CompanyServicesRemoveCompanyMemberErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    CompanyServicesRemoveCompanyMemberResponses,
    CompanyServicesRemoveCompanyMemberErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/companies/members/{id}',
    ...options,
  });

/**
 * Update company member
 */
export const companyServicesUpdateCompanyMember = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CompanyServicesUpdateCompanyMemberData, ThrowOnError>,
): RequestResult<
  CompanyServicesUpdateCompanyMemberResponses,
  CompanyServicesUpdateCompanyMemberErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    CompanyServicesUpdateCompanyMemberResponses,
    CompanyServicesUpdateCompanyMemberErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/companies/members/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get company by slug
 */
export const companyServicesGetCompanyBySlug = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CompanyServicesGetCompanyBySlugData, ThrowOnError>,
): RequestResult<
  CompanyServicesGetCompanyBySlugResponses,
  CompanyServicesGetCompanyBySlugErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    CompanyServicesGetCompanyBySlugResponses,
    CompanyServicesGetCompanyBySlugErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/companies/slug/{slug}',
    ...options,
  });

/**
 * Get company branches
 */
export const companyServicesGetCompanyBranches = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CompanyServicesGetCompanyBranchesData, ThrowOnError>,
): RequestResult<
  CompanyServicesGetCompanyBranchesResponses,
  CompanyServicesGetCompanyBranchesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    CompanyServicesGetCompanyBranchesResponses,
    CompanyServicesGetCompanyBranchesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/companies/{companyId}/branches',
    ...options,
  });

/**
 * Get company members
 */
export const companyServicesGetCompanyMembers = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CompanyServicesGetCompanyMembersData, ThrowOnError>,
): RequestResult<
  CompanyServicesGetCompanyMembersResponses,
  CompanyServicesGetCompanyMembersErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    CompanyServicesGetCompanyMembersResponses,
    CompanyServicesGetCompanyMembersErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/companies/{companyId}/members',
    ...options,
  });

/**
 * Delete company
 */
export const companyServicesDeleteCompany = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CompanyServicesDeleteCompanyData, ThrowOnError>,
): RequestResult<
  CompanyServicesDeleteCompanyResponses,
  CompanyServicesDeleteCompanyErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    CompanyServicesDeleteCompanyResponses,
    CompanyServicesDeleteCompanyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/companies/{id}',
    ...options,
  });

/**
 * Get company by ID
 */
export const companyServicesGetCompany = <ThrowOnError extends boolean = false>(
  options: Options<CompanyServicesGetCompanyData, ThrowOnError>,
): RequestResult<
  CompanyServicesGetCompanyResponses,
  CompanyServicesGetCompanyErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    CompanyServicesGetCompanyResponses,
    CompanyServicesGetCompanyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/companies/{id}',
    ...options,
  });

/**
 * Update company
 */
export const companyServicesUpdateCompany = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CompanyServicesUpdateCompanyData, ThrowOnError>,
): RequestResult<
  CompanyServicesUpdateCompanyResponses,
  CompanyServicesUpdateCompanyErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    CompanyServicesUpdateCompanyResponses,
    CompanyServicesUpdateCompanyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/companies/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Switch active company for the current session
 */
export const companyServicesSwitchActiveCompany = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CompanyServicesSwitchActiveCompanyData, ThrowOnError>,
): RequestResult<
  CompanyServicesSwitchActiveCompanyResponses,
  CompanyServicesSwitchActiveCompanyErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CompanyServicesSwitchActiveCompanyResponses,
    CompanyServicesSwitchActiveCompanyErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/companies/{id}/switch',
    ...options,
  });

/**
 * Get all features
 */
export const featureServicesGetFeatures = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<FeatureServicesGetFeaturesData, ThrowOnError>,
): RequestResult<
  FeatureServicesGetFeaturesResponses,
  FeatureServicesGetFeaturesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    FeatureServicesGetFeaturesResponses,
    FeatureServicesGetFeaturesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/features/',
    ...options,
  });

/**
 * Create feature
 */
export const featureServicesCreateFeature = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FeatureServicesCreateFeatureData, ThrowOnError>,
): RequestResult<
  FeatureServicesCreateFeatureResponses,
  FeatureServicesCreateFeatureErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    FeatureServicesCreateFeatureResponses,
    FeatureServicesCreateFeatureErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/features/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get company features
 */
export const featureServicesGetCompanyFeatures = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FeatureServicesGetCompanyFeaturesData, ThrowOnError>,
): RequestResult<
  FeatureServicesGetCompanyFeaturesResponses,
  FeatureServicesGetCompanyFeaturesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    FeatureServicesGetCompanyFeaturesResponses,
    FeatureServicesGetCompanyFeaturesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/features/companies/{companyId}',
    ...options,
  });

/**
 * Assign feature to company
 */
export const featureServicesAssignCompanyFeature = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FeatureServicesAssignCompanyFeatureData, ThrowOnError>,
): RequestResult<
  FeatureServicesAssignCompanyFeatureResponses,
  FeatureServicesAssignCompanyFeatureErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    FeatureServicesAssignCompanyFeatureResponses,
    FeatureServicesAssignCompanyFeatureErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/features/companies/{companyId}/assign',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get available features for company
 */
export const featureServicesGetCompanyAvailableFeatures = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    FeatureServicesGetCompanyAvailableFeaturesData,
    ThrowOnError
  >,
): RequestResult<
  FeatureServicesGetCompanyAvailableFeaturesResponses,
  FeatureServicesGetCompanyAvailableFeaturesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    FeatureServicesGetCompanyAvailableFeaturesResponses,
    FeatureServicesGetCompanyAvailableFeaturesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/features/companies/{companyId}/available',
    ...options,
  });

/**
 * Remove feature from company
 */
export const featureServicesRemoveCompanyFeature = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FeatureServicesRemoveCompanyFeatureData, ThrowOnError>,
): RequestResult<
  FeatureServicesRemoveCompanyFeatureResponses,
  FeatureServicesRemoveCompanyFeatureErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    FeatureServicesRemoveCompanyFeatureResponses,
    FeatureServicesRemoveCompanyFeatureErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/features/companies/{companyId}/features/{featureId}',
    ...options,
  });

/**
 * Get role features for company
 */
export const featureServicesGetCompanyRoleFeatures = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FeatureServicesGetCompanyRoleFeaturesData, ThrowOnError>,
): RequestResult<
  FeatureServicesGetCompanyRoleFeaturesResponses,
  FeatureServicesGetCompanyRoleFeaturesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    FeatureServicesGetCompanyRoleFeaturesResponses,
    FeatureServicesGetCompanyRoleFeaturesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/features/companies/{companyId}/roles',
    ...options,
  });

/**
 * Check role feature access
 */
export const featureServicesCheckRoleFeatureAccess = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FeatureServicesCheckRoleFeatureAccessData, ThrowOnError>,
): RequestResult<
  FeatureServicesCheckRoleFeatureAccessResponses,
  FeatureServicesCheckRoleFeatureAccessErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    FeatureServicesCheckRoleFeatureAccessResponses,
    FeatureServicesCheckRoleFeatureAccessErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/features/companies/{companyId}/roles/{roleId}/access/{featureCode}',
    ...options,
  });

/**
 * Toggle company feature
 */
export const featureServicesToggleCompanyFeature = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FeatureServicesToggleCompanyFeatureData, ThrowOnError>,
): RequestResult<
  FeatureServicesToggleCompanyFeatureResponses,
  FeatureServicesToggleCompanyFeatureErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    FeatureServicesToggleCompanyFeatureResponses,
    FeatureServicesToggleCompanyFeatureErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/features/companies/{companyId}/toggle',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get features for a role
 */
export const featureServicesGetRoleFeatures = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FeatureServicesGetRoleFeaturesData, ThrowOnError>,
): RequestResult<
  FeatureServicesGetRoleFeaturesResponses,
  FeatureServicesGetRoleFeaturesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    FeatureServicesGetRoleFeaturesResponses,
    FeatureServicesGetRoleFeaturesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/features/roles/{roleId}',
    ...options,
  });

/**
 * Assign feature to role
 */
export const featureServicesAssignRoleFeature = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FeatureServicesAssignRoleFeatureData, ThrowOnError>,
): RequestResult<
  FeatureServicesAssignRoleFeatureResponses,
  FeatureServicesAssignRoleFeatureErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    FeatureServicesAssignRoleFeatureResponses,
    FeatureServicesAssignRoleFeatureErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/features/roles/{roleId}/assign',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Revoke feature from role
 */
export const featureServicesRevokeRoleFeature = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FeatureServicesRevokeRoleFeatureData, ThrowOnError>,
): RequestResult<
  FeatureServicesRevokeRoleFeatureResponses,
  FeatureServicesRevokeRoleFeatureErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    FeatureServicesRevokeRoleFeatureResponses,
    FeatureServicesRevokeRoleFeatureErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/features/roles/{roleId}/features/{featureId}',
    ...options,
  });

/**
 * Toggle role feature
 */
export const featureServicesToggleRoleFeature = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FeatureServicesToggleRoleFeatureData, ThrowOnError>,
): RequestResult<
  FeatureServicesToggleRoleFeatureResponses,
  FeatureServicesToggleRoleFeatureErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    FeatureServicesToggleRoleFeatureResponses,
    FeatureServicesToggleRoleFeatureErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/features/roles/{roleId}/toggle',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get feature by id
 */
export const featureServicesGetFeature = <ThrowOnError extends boolean = false>(
  options: Options<FeatureServicesGetFeatureData, ThrowOnError>,
): RequestResult<
  FeatureServicesGetFeatureResponses,
  FeatureServicesGetFeatureErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    FeatureServicesGetFeatureResponses,
    FeatureServicesGetFeatureErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/features/{id}',
    ...options,
  });

/**
 * Update feature
 */
export const featureServicesUpdateFeature = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FeatureServicesUpdateFeatureData, ThrowOnError>,
): RequestResult<
  FeatureServicesUpdateFeatureResponses,
  FeatureServicesUpdateFeatureErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    FeatureServicesUpdateFeatureResponses,
    FeatureServicesUpdateFeatureErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/features/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Toggle feature active state
 */
export const featureServicesToggleFeature = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FeatureServicesToggleFeatureData, ThrowOnError>,
): RequestResult<
  FeatureServicesToggleFeatureResponses,
  FeatureServicesToggleFeatureErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    FeatureServicesToggleFeatureResponses,
    FeatureServicesToggleFeatureErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/features/{id}/toggle',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get all permissions
 */
export const permissionServicesGetPermissions = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PermissionServicesGetPermissionsData, ThrowOnError>,
): RequestResult<
  PermissionServicesGetPermissionsResponses,
  PermissionServicesGetPermissionsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    PermissionServicesGetPermissionsResponses,
    PermissionServicesGetPermissionsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/permissions/',
    ...options,
  });

/**
 * Create permission
 */
export const permissionServicesCreatePermission = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PermissionServicesCreatePermissionData, ThrowOnError>,
): RequestResult<
  PermissionServicesCreatePermissionResponses,
  PermissionServicesCreatePermissionErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PermissionServicesCreatePermissionResponses,
    PermissionServicesCreatePermissionErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/permissions/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get current user permissions
 */
export const permissionServicesGetMyPermissions = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PermissionServicesGetMyPermissionsData, ThrowOnError>,
): RequestResult<
  PermissionServicesGetMyPermissionsResponses,
  PermissionServicesGetMyPermissionsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    PermissionServicesGetMyPermissionsResponses,
    PermissionServicesGetMyPermissionsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/permissions/me',
    ...options,
  });

/**
 * Create role
 */
export const roleServicesCreateRole = <ThrowOnError extends boolean = false>(
  options: Options<RoleServicesCreateRoleData, ThrowOnError>,
): RequestResult<
  RoleServicesCreateRoleResponses,
  RoleServicesCreateRoleErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RoleServicesCreateRoleResponses,
    RoleServicesCreateRoleErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/permissions/roles/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get roles by company
 */
export const roleServicesGetCompanyRoles = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RoleServicesGetCompanyRolesData, ThrowOnError>,
): RequestResult<
  RoleServicesGetCompanyRolesResponses,
  RoleServicesGetCompanyRolesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    RoleServicesGetCompanyRolesResponses,
    RoleServicesGetCompanyRolesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/permissions/roles/company/{companyId}',
    ...options,
  });

/**
 * Assign permission to role
 */
export const roleServicesAssignPermissionToRole = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RoleServicesAssignPermissionToRoleData, ThrowOnError>,
): RequestResult<
  RoleServicesAssignPermissionToRoleResponses,
  RoleServicesAssignPermissionToRoleErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RoleServicesAssignPermissionToRoleResponses,
    RoleServicesAssignPermissionToRoleErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/permissions/roles/permissions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get system default roles
 */
export const roleServicesGetSystemDefaultRoles = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<RoleServicesGetSystemDefaultRolesData, ThrowOnError>,
): RequestResult<
  RoleServicesGetSystemDefaultRolesResponses,
  RoleServicesGetSystemDefaultRolesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    RoleServicesGetSystemDefaultRolesResponses,
    RoleServicesGetSystemDefaultRolesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/permissions/roles/system-defaults',
    ...options,
  });

/**
 * Delete role
 */
export const roleServicesDeleteRole = <ThrowOnError extends boolean = false>(
  options: Options<RoleServicesDeleteRoleData, ThrowOnError>,
): RequestResult<
  RoleServicesDeleteRoleResponses,
  RoleServicesDeleteRoleErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    RoleServicesDeleteRoleResponses,
    RoleServicesDeleteRoleErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/permissions/roles/{id}',
    ...options,
  });

/**
 * Get role by ID
 */
export const roleServicesGetRole = <ThrowOnError extends boolean = false>(
  options: Options<RoleServicesGetRoleData, ThrowOnError>,
): RequestResult<
  RoleServicesGetRoleResponses,
  RoleServicesGetRoleErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    RoleServicesGetRoleResponses,
    RoleServicesGetRoleErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/permissions/roles/{id}',
    ...options,
  });

/**
 * Update role
 */
export const roleServicesUpdateRole = <ThrowOnError extends boolean = false>(
  options: Options<RoleServicesUpdateRoleData, ThrowOnError>,
): RequestResult<
  RoleServicesUpdateRoleResponses,
  RoleServicesUpdateRoleErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    RoleServicesUpdateRoleResponses,
    RoleServicesUpdateRoleErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/permissions/roles/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get role permissions
 */
export const roleServicesGetRolePermissions = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RoleServicesGetRolePermissionsData, ThrowOnError>,
): RequestResult<
  RoleServicesGetRolePermissionsResponses,
  RoleServicesGetRolePermissionsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    RoleServicesGetRolePermissionsResponses,
    RoleServicesGetRolePermissionsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/permissions/roles/{roleId}/permissions',
    ...options,
  });

/**
 * Revoke permission from role
 */
export const roleServicesRevokePermissionFromRole = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RoleServicesRevokePermissionFromRoleData, ThrowOnError>,
): RequestResult<
  RoleServicesRevokePermissionFromRoleResponses,
  RoleServicesRevokePermissionFromRoleErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    RoleServicesRevokePermissionFromRoleResponses,
    RoleServicesRevokePermissionFromRoleErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/permissions/roles/{roleId}/permissions/{permissionId}',
    ...options,
  });

/**
 * Delete permission
 */
export const permissionServicesDeletePermission = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PermissionServicesDeletePermissionData, ThrowOnError>,
): RequestResult<
  PermissionServicesDeletePermissionResponses,
  PermissionServicesDeletePermissionErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    PermissionServicesDeletePermissionResponses,
    PermissionServicesDeletePermissionErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/permissions/{id}',
    ...options,
  });

/**
 * Update permission
 */
export const permissionServicesUpdatePermission = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PermissionServicesUpdatePermissionData, ThrowOnError>,
): RequestResult<
  PermissionServicesUpdatePermissionResponses,
  PermissionServicesUpdatePermissionErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PermissionServicesUpdatePermissionResponses,
    PermissionServicesUpdatePermissionErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/permissions/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get all users
 */
export const userServicesGetUsers = <ThrowOnError extends boolean = false>(
  options?: Options<UserServicesGetUsersData, ThrowOnError>,
): RequestResult<
  UserServicesGetUsersResponses,
  UserServicesGetUsersErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    UserServicesGetUsersResponses,
    UserServicesGetUsersErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/users/',
    ...options,
  });

/**
 * Create new user
 */
export const userServicesCreateUser = <ThrowOnError extends boolean = false>(
  options: Options<UserServicesCreateUserData, ThrowOnError>,
): RequestResult<
  UserServicesCreateUserResponses,
  UserServicesCreateUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    UserServicesCreateUserResponses,
    UserServicesCreateUserErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/users/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete user
 */
export const userServicesDeleteUser = <ThrowOnError extends boolean = false>(
  options: Options<UserServicesDeleteUserData, ThrowOnError>,
): RequestResult<
  UserServicesDeleteUserResponses,
  UserServicesDeleteUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    UserServicesDeleteUserResponses,
    UserServicesDeleteUserErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/users/{id}',
    ...options,
  });

/**
 * Get user by ID
 */
export const userServicesGetUser = <ThrowOnError extends boolean = false>(
  options: Options<UserServicesGetUserData, ThrowOnError>,
): RequestResult<
  UserServicesGetUserResponses,
  UserServicesGetUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    UserServicesGetUserResponses,
    UserServicesGetUserErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/users/{id}',
    ...options,
  });

/**
 * Update user
 */
export const userServicesUpdateUser = <ThrowOnError extends boolean = false>(
  options: Options<UserServicesUpdateUserData, ThrowOnError>,
): RequestResult<
  UserServicesUpdateUserResponses,
  UserServicesUpdateUserErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UserServicesUpdateUserResponses,
    UserServicesUpdateUserErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/users/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
