// This file is auto-generated by @hey-api/openapi-ts

import type {
  AttendanceServicesCheckInResponse,
  AttendanceServicesCreateScheduleResponse,
  AttendanceServicesCreateSlotResponse,
  AttendanceServicesGetCompanyLogsResponse,
  AttendanceServicesGetMemberLogsResponse,
  AttendanceServicesGetScheduleByRoleResponse,
  AttendanceServicesGetSchedulesByCompanyResponse,
  AttendanceServicesGetSlotsByScheduleResponse,
  AttendanceServicesManualCheckInResponse,
  AttendanceServicesUpdateScheduleResponse,
  AttendanceServicesUpdateSlotResponse,
  CompanyServicesAddCompanyMemberResponse,
  CompanyServicesCreateCompanyBranchResponse,
  CompanyServicesCreateCompanyResponse,
  CompanyServicesGetCompaniesResponse,
  CompanyServicesGetCompanyBranchesResponse,
  CompanyServicesGetCompanyBranchResponse,
  CompanyServicesGetCompanyBySlugResponse,
  CompanyServicesGetCompanyMembersResponse,
  CompanyServicesGetCompanyResponse,
  CompanyServicesSwitchActiveCompanyResponse,
  CompanyServicesUpdateCompanyBranchResponse,
  CompanyServicesUpdateCompanyMemberResponse,
  CompanyServicesUpdateCompanyResponse,
  FeatureServicesAssignCompanyFeatureResponse,
  FeatureServicesAssignRoleFeatureResponse,
  FeatureServicesCreateFeatureResponse,
  FeatureServicesGetCompanyAvailableFeaturesResponse,
  FeatureServicesGetCompanyFeaturesResponse,
  FeatureServicesGetCompanyRoleFeaturesResponse,
  FeatureServicesGetFeatureResponse,
  FeatureServicesGetFeaturesResponse,
  FeatureServicesGetRoleFeaturesResponse,
  FeatureServicesToggleCompanyFeatureResponse,
  FeatureServicesToggleFeatureResponse,
  FeatureServicesToggleRoleFeatureResponse,
  FeatureServicesUpdateFeatureResponse,
  FormServicesAssignRolesResponse,
  FormServicesCloneResponse,
  FormServicesCreateFieldResponse,
  FormServicesCreateSectionResponse,
  FormServicesCreateTemplateResponse,
  FormServicesGetSubmissionResponse,
  FormServicesGetTemplateResponse,
  FormServicesListSubmissionsResponse,
  FormServicesListTemplatesByCompanyResponse,
  FormServicesPublishVersionResponse,
  FormServicesReviewResponse,
  FormServicesSaveDraftResponse,
  FormServicesStartSubmissionResponse,
  FormServicesSubmitResponse,
  FormServicesUpdateTemplateResponse,
  LeaveServicesCancelRequestResponse,
  LeaveServicesCreateQuotaResponse,
  LeaveServicesCreateTypeResponse,
  LeaveServicesGetCompanyRequestsResponse,
  LeaveServicesGetMemberRequestsResponse,
  LeaveServicesGetQuotasByMemberResponse,
  LeaveServicesGetTypesByCompanyResponse,
  LeaveServicesReviewRequestResponse,
  LeaveServicesSubmitRequestResponse,
  LeaveServicesUpdateQuotaResponse,
  LeaveServicesUpdateTypeResponse,
  PermissionServicesCreatePermissionResponse,
  PermissionServicesGetMyPermissionsResponse,
  PermissionServicesGetPermissionsResponse,
  PermissionServicesUpdatePermissionResponse,
  RoleServicesAssignPermissionToRoleResponse,
  RoleServicesCreateRoleResponse,
  RoleServicesGetCompanyRolesResponse,
  RoleServicesGetRolePermissionsResponse,
  RoleServicesGetRoleResponse,
  RoleServicesGetSystemDefaultRolesResponse,
  RoleServicesUpdateRoleResponse,
  UserServicesCreateUserResponse,
  UserServicesGetUserResponse,
  UserServicesGetUsersResponse,
  UserServicesUpdateUserResponse,
} from './types.gen';

const attendanceLogSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  if (data.checkedInAt) {
    data.checkedInAt = new Date(data.checkedInAt);
  }
  return data;
};

export const attendanceServicesCheckInResponseTransformer = async (
  data: any,
): Promise<AttendanceServicesCheckInResponse> => {
  if (data.data) {
    data.data = attendanceLogSchemaResponseTransformer(data.data);
  }
  return data;
};

export const attendanceServicesGetCompanyLogsResponseTransformer = async (
  data: any,
): Promise<AttendanceServicesGetCompanyLogsResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      attendanceLogSchemaResponseTransformer(item),
    );
  }
  return data;
};

const checkInScheduleSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const attendanceServicesGetSchedulesByCompanyResponseTransformer =
  async (
    data: any,
  ): Promise<AttendanceServicesGetSchedulesByCompanyResponse> => {
    if (data.data) {
      data.data = data.data.map((item: any) =>
        checkInScheduleSchemaResponseTransformer(item),
      );
    }
    return data;
  };

export const attendanceServicesManualCheckInResponseTransformer = async (
  data: any,
): Promise<AttendanceServicesManualCheckInResponse> => {
  if (data.data) {
    data.data = attendanceLogSchemaResponseTransformer(data.data);
  }
  return data;
};

export const attendanceServicesGetMemberLogsResponseTransformer = async (
  data: any,
): Promise<AttendanceServicesGetMemberLogsResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      attendanceLogSchemaResponseTransformer(item),
    );
  }
  return data;
};

export const attendanceServicesGetScheduleByRoleResponseTransformer = async (
  data: any,
): Promise<AttendanceServicesGetScheduleByRoleResponse> => {
  if (data.data) {
    data.data = checkInScheduleSchemaResponseTransformer(data.data);
  }
  return data;
};

export const attendanceServicesCreateScheduleResponseTransformer = async (
  data: any,
): Promise<AttendanceServicesCreateScheduleResponse> => {
  if (data.data) {
    data.data = checkInScheduleSchemaResponseTransformer(data.data);
  }
  return data;
};

export const attendanceServicesUpdateScheduleResponseTransformer = async (
  data: any,
): Promise<AttendanceServicesUpdateScheduleResponse> => {
  if (data.data) {
    data.data = checkInScheduleSchemaResponseTransformer(data.data);
  }
  return data;
};

const scheduleSlotSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const attendanceServicesGetSlotsByScheduleResponseTransformer = async (
  data: any,
): Promise<AttendanceServicesGetSlotsByScheduleResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      scheduleSlotSchemaResponseTransformer(item),
    );
  }
  return data;
};

export const attendanceServicesCreateSlotResponseTransformer = async (
  data: any,
): Promise<AttendanceServicesCreateSlotResponse> => {
  if (data.data) {
    data.data = scheduleSlotSchemaResponseTransformer(data.data);
  }
  return data;
};

export const attendanceServicesUpdateSlotResponseTransformer = async (
  data: any,
): Promise<AttendanceServicesUpdateSlotResponse> => {
  if (data.data) {
    data.data = scheduleSlotSchemaResponseTransformer(data.data);
  }
  return data;
};

const companySchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const companyServicesGetCompaniesResponseTransformer = async (
  data: any,
): Promise<CompanyServicesGetCompaniesResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      companySchemaResponseTransformer(item),
    );
  }
  return data;
};

export const companyServicesCreateCompanyResponseTransformer = async (
  data: any,
): Promise<CompanyServicesCreateCompanyResponse> => {
  if (data.data) {
    data.data = companySchemaResponseTransformer(data.data);
  }
  return data;
};

const companyBranchSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const companyServicesCreateCompanyBranchResponseTransformer = async (
  data: any,
): Promise<CompanyServicesCreateCompanyBranchResponse> => {
  if (data.data) {
    data.data = companyBranchSchemaResponseTransformer(data.data);
  }
  return data;
};

export const companyServicesGetCompanyBranchResponseTransformer = async (
  data: any,
): Promise<CompanyServicesGetCompanyBranchResponse> => {
  if (data.data) {
    data.data = companyBranchSchemaResponseTransformer(data.data);
  }
  return data;
};

export const companyServicesUpdateCompanyBranchResponseTransformer = async (
  data: any,
): Promise<CompanyServicesUpdateCompanyBranchResponse> => {
  if (data.data) {
    data.data = companyBranchSchemaResponseTransformer(data.data);
  }
  return data;
};

const companyMemberSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const companyServicesAddCompanyMemberResponseTransformer = async (
  data: any,
): Promise<CompanyServicesAddCompanyMemberResponse> => {
  if (data.data) {
    data.data = companyMemberSchemaResponseTransformer(data.data);
  }
  return data;
};

export const companyServicesUpdateCompanyMemberResponseTransformer = async (
  data: any,
): Promise<CompanyServicesUpdateCompanyMemberResponse> => {
  if (data.data) {
    data.data = companyMemberSchemaResponseTransformer(data.data);
  }
  return data;
};

export const companyServicesGetCompanyBySlugResponseTransformer = async (
  data: any,
): Promise<CompanyServicesGetCompanyBySlugResponse> => {
  if (data.data) {
    data.data = companySchemaResponseTransformer(data.data);
  }
  return data;
};

export const companyServicesGetCompanyBranchesResponseTransformer = async (
  data: any,
): Promise<CompanyServicesGetCompanyBranchesResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      companyBranchSchemaResponseTransformer(item),
    );
  }
  return data;
};

export const companyServicesGetCompanyMembersResponseTransformer = async (
  data: any,
): Promise<CompanyServicesGetCompanyMembersResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      companyMemberSchemaResponseTransformer(item),
    );
  }
  return data;
};

export const companyServicesGetCompanyResponseTransformer = async (
  data: any,
): Promise<CompanyServicesGetCompanyResponse> => {
  if (data.data) {
    data.data = companySchemaResponseTransformer(data.data);
  }
  return data;
};

export const companyServicesUpdateCompanyResponseTransformer = async (
  data: any,
): Promise<CompanyServicesUpdateCompanyResponse> => {
  if (data.data) {
    data.data = companySchemaResponseTransformer(data.data);
  }
  return data;
};

const switchActiveCompanyResponseSchemaResponseTransformer = (data: any) => {
  data.company = companySchemaResponseTransformer(data.company);
  return data;
};

export const companyServicesSwitchActiveCompanyResponseTransformer = async (
  data: any,
): Promise<CompanyServicesSwitchActiveCompanyResponse> => {
  if (data.data) {
    data.data = switchActiveCompanyResponseSchemaResponseTransformer(data.data);
  }
  return data;
};

const featureSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const featureServicesGetFeaturesResponseTransformer = async (
  data: any,
): Promise<FeatureServicesGetFeaturesResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      featureSchemaResponseTransformer(item),
    );
  }
  return data;
};

export const featureServicesCreateFeatureResponseTransformer = async (
  data: any,
): Promise<FeatureServicesCreateFeatureResponse> => {
  if (data.data) {
    data.data = featureSchemaResponseTransformer(data.data);
  }
  return data;
};

const companyFeatureSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  if (data.expiresAt) {
    data.expiresAt = new Date(data.expiresAt);
  }
  return data;
};

export const featureServicesGetCompanyFeaturesResponseTransformer = async (
  data: any,
): Promise<FeatureServicesGetCompanyFeaturesResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      companyFeatureSchemaResponseTransformer(item),
    );
  }
  return data;
};

export const featureServicesAssignCompanyFeatureResponseTransformer = async (
  data: any,
): Promise<FeatureServicesAssignCompanyFeatureResponse> => {
  if (data.data) {
    data.data = companyFeatureSchemaResponseTransformer(data.data);
  }
  return data;
};

export const featureServicesGetCompanyAvailableFeaturesResponseTransformer =
  async (
    data: any,
  ): Promise<FeatureServicesGetCompanyAvailableFeaturesResponse> => {
    if (data.data) {
      data.data = data.data.map((item: any) =>
        featureSchemaResponseTransformer(item),
      );
    }
    return data;
  };

const roleFeatureSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const featureServicesGetCompanyRoleFeaturesResponseTransformer = async (
  data: any,
): Promise<FeatureServicesGetCompanyRoleFeaturesResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      roleFeatureSchemaResponseTransformer(item),
    );
  }
  return data;
};

export const featureServicesToggleCompanyFeatureResponseTransformer = async (
  data: any,
): Promise<FeatureServicesToggleCompanyFeatureResponse> => {
  if (data.data) {
    data.data = companyFeatureSchemaResponseTransformer(data.data);
  }
  return data;
};

export const featureServicesGetRoleFeaturesResponseTransformer = async (
  data: any,
): Promise<FeatureServicesGetRoleFeaturesResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      featureSchemaResponseTransformer(item),
    );
  }
  return data;
};

export const featureServicesAssignRoleFeatureResponseTransformer = async (
  data: any,
): Promise<FeatureServicesAssignRoleFeatureResponse> => {
  if (data.data) {
    data.data = roleFeatureSchemaResponseTransformer(data.data);
  }
  return data;
};

export const featureServicesToggleRoleFeatureResponseTransformer = async (
  data: any,
): Promise<FeatureServicesToggleRoleFeatureResponse> => {
  if (data.data) {
    data.data = roleFeatureSchemaResponseTransformer(data.data);
  }
  return data;
};

export const featureServicesGetFeatureResponseTransformer = async (
  data: any,
): Promise<FeatureServicesGetFeatureResponse> => {
  if (data.data) {
    data.data = featureSchemaResponseTransformer(data.data);
  }
  return data;
};

export const featureServicesUpdateFeatureResponseTransformer = async (
  data: any,
): Promise<FeatureServicesUpdateFeatureResponse> => {
  if (data.data) {
    data.data = featureSchemaResponseTransformer(data.data);
  }
  return data;
};

export const featureServicesToggleFeatureResponseTransformer = async (
  data: any,
): Promise<FeatureServicesToggleFeatureResponse> => {
  if (data.data) {
    data.data = featureSchemaResponseTransformer(data.data);
  }
  return data;
};

const formTemplateSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const formServicesListTemplatesByCompanyResponseTransformer = async (
  data: any,
): Promise<FormServicesListTemplatesByCompanyResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      formTemplateSchemaResponseTransformer(item),
    );
  }
  return data;
};

const formSubmissionSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  data.startedAt = new Date(data.startedAt);
  if (data.submittedAt) {
    data.submittedAt = new Date(data.submittedAt);
  }
  return data;
};

export const formServicesListSubmissionsResponseTransformer = async (
  data: any,
): Promise<FormServicesListSubmissionsResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      formSubmissionSchemaResponseTransformer(item),
    );
  }
  return data;
};

export const formServicesStartSubmissionResponseTransformer = async (
  data: any,
): Promise<FormServicesStartSubmissionResponse> => {
  if (data.data) {
    data.data = formSubmissionSchemaResponseTransformer(data.data);
  }
  return data;
};

const formVersionSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  if (data.publishedAt) {
    data.publishedAt = new Date(data.publishedAt);
  }
  return data;
};

const formSectionSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

const formFieldSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

const formAnswerSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

const formSubmissionContributorSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

const submissionReviewSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

const formSubmissionDetailSchemaResponseTransformer = (data: any) => {
  data.submission = formSubmissionSchemaResponseTransformer(data.submission);
  if (data.template) {
    data.template = formTemplateSchemaResponseTransformer(data.template);
  }
  if (data.version) {
    data.version = formVersionSchemaResponseTransformer(data.version);
  }
  data.sections = data.sections.map((item: any) =>
    formSectionSchemaResponseTransformer(item),
  );
  data.fields = data.fields.map((item: any) =>
    formFieldSchemaResponseTransformer(item),
  );
  data.answers = data.answers.map((item: any) =>
    formAnswerSchemaResponseTransformer(item),
  );
  data.contributors = data.contributors.map((item: any) =>
    formSubmissionContributorSchemaResponseTransformer(item),
  );
  if (data.review) {
    data.review = submissionReviewSchemaResponseTransformer(data.review);
  }
  return data;
};

export const formServicesGetSubmissionResponseTransformer = async (
  data: any,
): Promise<FormServicesGetSubmissionResponse> => {
  if (data.data) {
    data.data = formSubmissionDetailSchemaResponseTransformer(data.data);
  }
  return data;
};

export const formServicesCloneResponseTransformer = async (
  data: any,
): Promise<FormServicesCloneResponse> => {
  if (data.data) {
    data.data = formSubmissionSchemaResponseTransformer(data.data);
  }
  return data;
};

export const formServicesSaveDraftResponseTransformer = async (
  data: any,
): Promise<FormServicesSaveDraftResponse> => {
  if (data.data) {
    data.data = formSubmissionSchemaResponseTransformer(data.data);
  }
  return data;
};

export const formServicesReviewResponseTransformer = async (
  data: any,
): Promise<FormServicesReviewResponse> => {
  if (data.data) {
    data.data = submissionReviewSchemaResponseTransformer(data.data);
  }
  return data;
};

export const formServicesSubmitResponseTransformer = async (
  data: any,
): Promise<FormServicesSubmitResponse> => {
  if (data.data) {
    data.data = formSubmissionSchemaResponseTransformer(data.data);
  }
  return data;
};

export const formServicesCreateTemplateResponseTransformer = async (
  data: any,
): Promise<FormServicesCreateTemplateResponse> => {
  if (data.data) {
    data.data = formTemplateSchemaResponseTransformer(data.data);
  }
  return data;
};

const formTemplateRoleSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

const formTemplateDetailSchemaResponseTransformer = (data: any) => {
  data.template = formTemplateSchemaResponseTransformer(data.template);
  if (data.activeVersion) {
    data.activeVersion = formVersionSchemaResponseTransformer(
      data.activeVersion,
    );
  }
  if (data.draftVersion) {
    data.draftVersion = formVersionSchemaResponseTransformer(data.draftVersion);
  }
  data.roles = data.roles.map((item: any) =>
    formTemplateRoleSchemaResponseTransformer(item),
  );
  data.sections = data.sections.map((item: any) =>
    formSectionSchemaResponseTransformer(item),
  );
  data.fields = data.fields.map((item: any) =>
    formFieldSchemaResponseTransformer(item),
  );
  return data;
};

export const formServicesGetTemplateResponseTransformer = async (
  data: any,
): Promise<FormServicesGetTemplateResponse> => {
  if (data.data) {
    data.data = formTemplateDetailSchemaResponseTransformer(data.data);
  }
  return data;
};

export const formServicesUpdateTemplateResponseTransformer = async (
  data: any,
): Promise<FormServicesUpdateTemplateResponse> => {
  if (data.data) {
    data.data = formTemplateSchemaResponseTransformer(data.data);
  }
  return data;
};

export const formServicesCreateFieldResponseTransformer = async (
  data: any,
): Promise<FormServicesCreateFieldResponse> => {
  if (data.data) {
    data.data = formFieldSchemaResponseTransformer(data.data);
  }
  return data;
};

export const formServicesPublishVersionResponseTransformer = async (
  data: any,
): Promise<FormServicesPublishVersionResponse> => {
  if (data.data) {
    data.data = formVersionSchemaResponseTransformer(data.data);
  }
  return data;
};

export const formServicesAssignRolesResponseTransformer = async (
  data: any,
): Promise<FormServicesAssignRolesResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      formTemplateRoleSchemaResponseTransformer(item),
    );
  }
  return data;
};

export const formServicesCreateSectionResponseTransformer = async (
  data: any,
): Promise<FormServicesCreateSectionResponse> => {
  if (data.data) {
    data.data = formSectionSchemaResponseTransformer(data.data);
  }
  return data;
};

const leaveRequestSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  if (data.reviewedAt) {
    data.reviewedAt = new Date(data.reviewedAt);
  }
  return data;
};

export const leaveServicesGetCompanyRequestsResponseTransformer = async (
  data: any,
): Promise<LeaveServicesGetCompanyRequestsResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      leaveRequestSchemaResponseTransformer(item),
    );
  }
  return data;
};

const leaveTypeSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const leaveServicesGetTypesByCompanyResponseTransformer = async (
  data: any,
): Promise<LeaveServicesGetTypesByCompanyResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      leaveTypeSchemaResponseTransformer(item),
    );
  }
  return data;
};

const leaveQuotaSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const leaveServicesGetQuotasByMemberResponseTransformer = async (
  data: any,
): Promise<LeaveServicesGetQuotasByMemberResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      leaveQuotaSchemaResponseTransformer(item),
    );
  }
  return data;
};

export const leaveServicesGetMemberRequestsResponseTransformer = async (
  data: any,
): Promise<LeaveServicesGetMemberRequestsResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      leaveRequestSchemaResponseTransformer(item),
    );
  }
  return data;
};

export const leaveServicesCreateQuotaResponseTransformer = async (
  data: any,
): Promise<LeaveServicesCreateQuotaResponse> => {
  if (data.data) {
    data.data = leaveQuotaSchemaResponseTransformer(data.data);
  }
  return data;
};

export const leaveServicesUpdateQuotaResponseTransformer = async (
  data: any,
): Promise<LeaveServicesUpdateQuotaResponse> => {
  if (data.data) {
    data.data = leaveQuotaSchemaResponseTransformer(data.data);
  }
  return data;
};

export const leaveServicesSubmitRequestResponseTransformer = async (
  data: any,
): Promise<LeaveServicesSubmitRequestResponse> => {
  if (data.data) {
    data.data = leaveRequestSchemaResponseTransformer(data.data);
  }
  return data;
};

export const leaveServicesCancelRequestResponseTransformer = async (
  data: any,
): Promise<LeaveServicesCancelRequestResponse> => {
  if (data.data) {
    data.data = leaveRequestSchemaResponseTransformer(data.data);
  }
  return data;
};

export const leaveServicesReviewRequestResponseTransformer = async (
  data: any,
): Promise<LeaveServicesReviewRequestResponse> => {
  if (data.data) {
    data.data = leaveRequestSchemaResponseTransformer(data.data);
  }
  return data;
};

export const leaveServicesCreateTypeResponseTransformer = async (
  data: any,
): Promise<LeaveServicesCreateTypeResponse> => {
  if (data.data) {
    data.data = leaveTypeSchemaResponseTransformer(data.data);
  }
  return data;
};

export const leaveServicesUpdateTypeResponseTransformer = async (
  data: any,
): Promise<LeaveServicesUpdateTypeResponse> => {
  if (data.data) {
    data.data = leaveTypeSchemaResponseTransformer(data.data);
  }
  return data;
};

const permissionSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const permissionServicesGetPermissionsResponseTransformer = async (
  data: any,
): Promise<PermissionServicesGetPermissionsResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      permissionSchemaResponseTransformer(item),
    );
  }
  return data;
};

export const permissionServicesCreatePermissionResponseTransformer = async (
  data: any,
): Promise<PermissionServicesCreatePermissionResponse> => {
  if (data.data) {
    data.data = permissionSchemaResponseTransformer(data.data);
  }
  return data;
};

export const permissionServicesGetMyPermissionsResponseTransformer = async (
  data: any,
): Promise<PermissionServicesGetMyPermissionsResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      permissionSchemaResponseTransformer(item),
    );
  }
  return data;
};

const roleSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const roleServicesCreateRoleResponseTransformer = async (
  data: any,
): Promise<RoleServicesCreateRoleResponse> => {
  if (data.data) {
    data.data = roleSchemaResponseTransformer(data.data);
  }
  return data;
};

export const roleServicesGetCompanyRolesResponseTransformer = async (
  data: any,
): Promise<RoleServicesGetCompanyRolesResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      roleSchemaResponseTransformer(item),
    );
  }
  return data;
};

const rolePermissionSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const roleServicesAssignPermissionToRoleResponseTransformer = async (
  data: any,
): Promise<RoleServicesAssignPermissionToRoleResponse> => {
  if (data.data) {
    data.data = rolePermissionSchemaResponseTransformer(data.data);
  }
  return data;
};

export const roleServicesGetSystemDefaultRolesResponseTransformer = async (
  data: any,
): Promise<RoleServicesGetSystemDefaultRolesResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      roleSchemaResponseTransformer(item),
    );
  }
  return data;
};

export const roleServicesGetRoleResponseTransformer = async (
  data: any,
): Promise<RoleServicesGetRoleResponse> => {
  if (data.data) {
    data.data = roleSchemaResponseTransformer(data.data);
  }
  return data;
};

export const roleServicesUpdateRoleResponseTransformer = async (
  data: any,
): Promise<RoleServicesUpdateRoleResponse> => {
  if (data.data) {
    data.data = roleSchemaResponseTransformer(data.data);
  }
  return data;
};

export const roleServicesGetRolePermissionsResponseTransformer = async (
  data: any,
): Promise<RoleServicesGetRolePermissionsResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      permissionSchemaResponseTransformer(item),
    );
  }
  return data;
};

export const permissionServicesUpdatePermissionResponseTransformer = async (
  data: any,
): Promise<PermissionServicesUpdatePermissionResponse> => {
  if (data.data) {
    data.data = permissionSchemaResponseTransformer(data.data);
  }
  return data;
};

const userSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  if (data.lastLogin) {
    data.lastLogin = new Date(data.lastLogin);
  }
  return data;
};

export const userServicesGetUsersResponseTransformer = async (
  data: any,
): Promise<UserServicesGetUsersResponse> => {
  if (data.data) {
    data.data = data.data.map((item: any) =>
      userSchemaResponseTransformer(item),
    );
  }
  return data;
};

export const userServicesCreateUserResponseTransformer = async (
  data: any,
): Promise<UserServicesCreateUserResponse> => {
  if (data.data) {
    data.data = userSchemaResponseTransformer(data.data);
  }
  return data;
};

export const userServicesGetUserResponseTransformer = async (
  data: any,
): Promise<UserServicesGetUserResponse> => {
  if (data.data) {
    data.data = userSchemaResponseTransformer(data.data);
  }
  return data;
};

export const userServicesUpdateUserResponseTransformer = async (
  data: any,
): Promise<UserServicesUpdateUserResponse> => {
  if (data.data) {
    data.data = userSchemaResponseTransformer(data.data);
  }
  return data;
};
