// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};

/**
 * Error response returned on failures
 */
export type ApiErrorResponse = {
  success: boolean;
  message: string;
  error?: string;
};

/**
 * 403 Forbidden — FORBIDDEN
 */
export type ApiForbiddenResponse = {
  body: ApiErrorResponse;
};

/**
 * 500 Internal Server Error — INTERNAL_ERROR
 */
export type ApiInternalErrorResponse = {
  body: ApiErrorResponse;
};

/**
 * Successful response without data payload
 */
export type BasicResponse = {
  success: boolean;
  message: string;
};

export type Company = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  name: string;
  slug: string;
  logo?: string | null;
  isActive: boolean;
};

export type CompanyBranch = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyId: string;
  name: string;
  address?: string | null;
  isActive: boolean;
};

export type CompanyMember = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyBranchId: string;
  companyId: string;
  userId: string;
  roleId: string;
  isActive: boolean;
};

/**
 * The template for omitting properties.
 */
export type CreateCompany = {
  name: string;
  slug: string;
  logo?: string | null;
  isActive: boolean;
};

/**
 * The template for omitting properties.
 */
export type CreateCompanyBranch = {
  companyId: string;
  name: string;
  address?: string | null;
  isActive: boolean;
};

export type CreateCompanyMember = {
  companyId: string;
  userId: string;
  roleId: string;
  isActive: boolean;
  companyBranchId?: string;
};

/**
 * The template for omitting properties.
 */
export type CreatePermission = {
  action: string;
  module: string;
  description?: string | null;
};

/**
 * The template for omitting properties.
 */
export type CreateRole = {
  companyId?: string | null;
  name: string;
  description?: string | null;
  roleType: DomainEntityRoleType;
  isSystemDefault: boolean;
};

/**
 * The template for omitting properties.
 */
export type CreateRolePermission = {
  roleId: string;
  permissionId: string;
};

/**
 * The template for omitting properties.
 */
export type CreateUser = {
  name: string;
  email: string;
  image?: string | null;
  isAdmin: boolean;
  isActive: boolean;
  password?: string;
};

export type DomainEntityRoleType =
  | 'SUPER_ADMIN'
  | 'OWNER'
  | 'ADMIN'
  | 'MEMBER'
  | 'VIEWER';

export type Permission = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  action: string;
  module: string;
  description?: string | null;
};

export type Role = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyId?: string | null;
  name: string;
  description?: string | null;
  roleType: DomainEntityRoleType;
  isSystemDefault: boolean;
};

export type RolePermission = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  roleId: string;
  permissionId: string;
};

/**
 * The template for adding optional properties.
 */
export type UpdateCompany = {
  name?: string;
  slug?: string;
  logo?: string | null;
  isActive?: boolean;
};

/**
 * The template for adding optional properties.
 */
export type UpdateCompanyBranch = {
  companyId?: string;
  name?: string;
  address?: string | null;
  isActive?: boolean;
};

/**
 * The template for adding optional properties.
 */
export type UpdateCompanyMember = {
  companyBranchId?: string;
  companyId?: string;
  userId?: string;
  roleId?: string;
  isActive?: boolean;
};

/**
 * The template for adding optional properties.
 */
export type UpdatePermission = {
  action?: string;
  module?: string;
  description?: string | null;
};

/**
 * The template for adding optional properties.
 */
export type UpdateRole = {
  companyId?: string | null;
  name?: string;
  description?: string | null;
  roleType?: DomainEntityRoleType;
  isSystemDefault?: boolean;
};

/**
 * The template for adding optional properties.
 */
export type UpdateUser = {
  name?: string;
  email?: string;
  emailVerified?: boolean;
  image?: string | null;
  isAdmin?: boolean;
  isActive?: boolean;
  lastLogin?: Date | null;
};

export type User = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  name: string;
  email: string;
  emailVerified: boolean;
  image?: string | null;
  isAdmin: boolean;
  isActive: boolean;
  lastLogin?: Date | null;
};

export type CompanyServicesGetCompaniesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/companies/';
};

export type CompanyServicesGetCompaniesErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type CompanyServicesGetCompaniesError =
  CompanyServicesGetCompaniesErrors[keyof CompanyServicesGetCompaniesErrors];

export type CompanyServicesGetCompaniesResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<Company>;
  };
};

export type CompanyServicesGetCompaniesResponse =
  CompanyServicesGetCompaniesResponses[keyof CompanyServicesGetCompaniesResponses];

export type CompanyServicesCreateCompanyData = {
  body: CreateCompany;
  path?: never;
  query?: never;
  url: '/companies/';
};

export type CompanyServicesCreateCompanyErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type CompanyServicesCreateCompanyError =
  CompanyServicesCreateCompanyErrors[keyof CompanyServicesCreateCompanyErrors];

export type CompanyServicesCreateCompanyResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: Company;
  };
};

export type CompanyServicesCreateCompanyResponse =
  CompanyServicesCreateCompanyResponses[keyof CompanyServicesCreateCompanyResponses];

export type CompanyServicesCreateCompanyBranchData = {
  body: CreateCompanyBranch;
  path?: never;
  query?: never;
  url: '/companies/branches';
};

export type CompanyServicesCreateCompanyBranchErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type CompanyServicesCreateCompanyBranchError =
  CompanyServicesCreateCompanyBranchErrors[keyof CompanyServicesCreateCompanyBranchErrors];

export type CompanyServicesCreateCompanyBranchResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: CompanyBranch;
  };
};

export type CompanyServicesCreateCompanyBranchResponse =
  CompanyServicesCreateCompanyBranchResponses[keyof CompanyServicesCreateCompanyBranchResponses];

export type CompanyServicesDeleteCompanyBranchData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    companyId?: string;
  };
  url: '/companies/branches/{id}';
};

export type CompanyServicesDeleteCompanyBranchErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesDeleteCompanyBranchError =
  CompanyServicesDeleteCompanyBranchErrors[keyof CompanyServicesDeleteCompanyBranchErrors];

export type CompanyServicesDeleteCompanyBranchResponses = {
  /**
   * 200 OK without data
   */
  200: BasicResponse;
};

export type CompanyServicesDeleteCompanyBranchResponse =
  CompanyServicesDeleteCompanyBranchResponses[keyof CompanyServicesDeleteCompanyBranchResponses];

export type CompanyServicesGetCompanyBranchData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/companies/branches/{id}';
};

export type CompanyServicesGetCompanyBranchErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesGetCompanyBranchError =
  CompanyServicesGetCompanyBranchErrors[keyof CompanyServicesGetCompanyBranchErrors];

export type CompanyServicesGetCompanyBranchResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: CompanyBranch;
  };
};

export type CompanyServicesGetCompanyBranchResponse =
  CompanyServicesGetCompanyBranchResponses[keyof CompanyServicesGetCompanyBranchResponses];

export type CompanyServicesUpdateCompanyBranchData = {
  body: UpdateCompanyBranch;
  path: {
    id: string;
  };
  query?: never;
  url: '/companies/branches/{id}';
};

export type CompanyServicesUpdateCompanyBranchErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesUpdateCompanyBranchError =
  CompanyServicesUpdateCompanyBranchErrors[keyof CompanyServicesUpdateCompanyBranchErrors];

export type CompanyServicesUpdateCompanyBranchResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: CompanyBranch;
  };
};

export type CompanyServicesUpdateCompanyBranchResponse =
  CompanyServicesUpdateCompanyBranchResponses[keyof CompanyServicesUpdateCompanyBranchResponses];

export type CompanyServicesAddCompanyMemberData = {
  body: CreateCompanyMember;
  path?: never;
  query?: never;
  url: '/companies/members';
};

export type CompanyServicesAddCompanyMemberErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type CompanyServicesAddCompanyMemberError =
  CompanyServicesAddCompanyMemberErrors[keyof CompanyServicesAddCompanyMemberErrors];

export type CompanyServicesAddCompanyMemberResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: CompanyMember;
  };
};

export type CompanyServicesAddCompanyMemberResponse =
  CompanyServicesAddCompanyMemberResponses[keyof CompanyServicesAddCompanyMemberResponses];

export type CompanyServicesRemoveCompanyMemberData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/companies/members/{id}';
};

export type CompanyServicesRemoveCompanyMemberErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesRemoveCompanyMemberError =
  CompanyServicesRemoveCompanyMemberErrors[keyof CompanyServicesRemoveCompanyMemberErrors];

export type CompanyServicesRemoveCompanyMemberResponses = {
  /**
   * 200 OK without data
   */
  200: BasicResponse;
};

export type CompanyServicesRemoveCompanyMemberResponse =
  CompanyServicesRemoveCompanyMemberResponses[keyof CompanyServicesRemoveCompanyMemberResponses];

export type CompanyServicesUpdateCompanyMemberData = {
  body: UpdateCompanyMember;
  path: {
    id: string;
  };
  query?: never;
  url: '/companies/members/{id}';
};

export type CompanyServicesUpdateCompanyMemberErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesUpdateCompanyMemberError =
  CompanyServicesUpdateCompanyMemberErrors[keyof CompanyServicesUpdateCompanyMemberErrors];

export type CompanyServicesUpdateCompanyMemberResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: CompanyMember;
  };
};

export type CompanyServicesUpdateCompanyMemberResponse =
  CompanyServicesUpdateCompanyMemberResponses[keyof CompanyServicesUpdateCompanyMemberResponses];

export type CompanyServicesGetCompanyBySlugData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/companies/slug/{slug}';
};

export type CompanyServicesGetCompanyBySlugErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesGetCompanyBySlugError =
  CompanyServicesGetCompanyBySlugErrors[keyof CompanyServicesGetCompanyBySlugErrors];

export type CompanyServicesGetCompanyBySlugResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Company;
  };
};

export type CompanyServicesGetCompanyBySlugResponse =
  CompanyServicesGetCompanyBySlugResponses[keyof CompanyServicesGetCompanyBySlugResponses];

export type CompanyServicesGetCompanyBranchesData = {
  body?: never;
  path: {
    companyId: string;
  };
  query?: never;
  url: '/companies/{companyId}/branches';
};

export type CompanyServicesGetCompanyBranchesErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesGetCompanyBranchesError =
  CompanyServicesGetCompanyBranchesErrors[keyof CompanyServicesGetCompanyBranchesErrors];

export type CompanyServicesGetCompanyBranchesResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<CompanyBranch>;
  };
};

export type CompanyServicesGetCompanyBranchesResponse =
  CompanyServicesGetCompanyBranchesResponses[keyof CompanyServicesGetCompanyBranchesResponses];

export type CompanyServicesGetCompanyMembersData = {
  body?: never;
  path: {
    companyId: string;
  };
  query?: never;
  url: '/companies/{companyId}/members';
};

export type CompanyServicesGetCompanyMembersErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesGetCompanyMembersError =
  CompanyServicesGetCompanyMembersErrors[keyof CompanyServicesGetCompanyMembersErrors];

export type CompanyServicesGetCompanyMembersResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<CompanyMember>;
  };
};

export type CompanyServicesGetCompanyMembersResponse =
  CompanyServicesGetCompanyMembersResponses[keyof CompanyServicesGetCompanyMembersResponses];

export type CompanyServicesDeleteCompanyData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/companies/{id}';
};

export type CompanyServicesDeleteCompanyErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesDeleteCompanyError =
  CompanyServicesDeleteCompanyErrors[keyof CompanyServicesDeleteCompanyErrors];

export type CompanyServicesDeleteCompanyResponses = {
  /**
   * 200 OK without data
   */
  200: BasicResponse;
};

export type CompanyServicesDeleteCompanyResponse =
  CompanyServicesDeleteCompanyResponses[keyof CompanyServicesDeleteCompanyResponses];

export type CompanyServicesGetCompanyData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/companies/{id}';
};

export type CompanyServicesGetCompanyErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesGetCompanyError =
  CompanyServicesGetCompanyErrors[keyof CompanyServicesGetCompanyErrors];

export type CompanyServicesGetCompanyResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Company;
  };
};

export type CompanyServicesGetCompanyResponse =
  CompanyServicesGetCompanyResponses[keyof CompanyServicesGetCompanyResponses];

export type CompanyServicesUpdateCompanyData = {
  body: UpdateCompany;
  path: {
    id: string;
  };
  query?: never;
  url: '/companies/{id}';
};

export type CompanyServicesUpdateCompanyErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesUpdateCompanyError =
  CompanyServicesUpdateCompanyErrors[keyof CompanyServicesUpdateCompanyErrors];

export type CompanyServicesUpdateCompanyResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Company;
  };
};

export type CompanyServicesUpdateCompanyResponse =
  CompanyServicesUpdateCompanyResponses[keyof CompanyServicesUpdateCompanyResponses];

export type PermissionServicesGetPermissionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/permissions/';
};

export type PermissionServicesGetPermissionsErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type PermissionServicesGetPermissionsError =
  PermissionServicesGetPermissionsErrors[keyof PermissionServicesGetPermissionsErrors];

export type PermissionServicesGetPermissionsResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<Permission>;
  };
};

export type PermissionServicesGetPermissionsResponse =
  PermissionServicesGetPermissionsResponses[keyof PermissionServicesGetPermissionsResponses];

export type PermissionServicesCreatePermissionData = {
  body: CreatePermission;
  path?: never;
  query?: never;
  url: '/permissions/';
};

export type PermissionServicesCreatePermissionErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type PermissionServicesCreatePermissionError =
  PermissionServicesCreatePermissionErrors[keyof PermissionServicesCreatePermissionErrors];

export type PermissionServicesCreatePermissionResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: Permission;
  };
};

export type PermissionServicesCreatePermissionResponse =
  PermissionServicesCreatePermissionResponses[keyof PermissionServicesCreatePermissionResponses];

export type PermissionServicesGetMyPermissionsData = {
  body?: never;
  path?: never;
  query?: {
    companyId?: string;
  };
  url: '/permissions/me';
};

export type PermissionServicesGetMyPermissionsErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type PermissionServicesGetMyPermissionsError =
  PermissionServicesGetMyPermissionsErrors[keyof PermissionServicesGetMyPermissionsErrors];

export type PermissionServicesGetMyPermissionsResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<Permission>;
  };
};

export type PermissionServicesGetMyPermissionsResponse =
  PermissionServicesGetMyPermissionsResponses[keyof PermissionServicesGetMyPermissionsResponses];

export type RoleServicesCreateRoleData = {
  body: CreateRole;
  path?: never;
  query?: never;
  url: '/permissions/roles/';
};

export type RoleServicesCreateRoleErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type RoleServicesCreateRoleError =
  RoleServicesCreateRoleErrors[keyof RoleServicesCreateRoleErrors];

export type RoleServicesCreateRoleResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: Role;
  };
};

export type RoleServicesCreateRoleResponse =
  RoleServicesCreateRoleResponses[keyof RoleServicesCreateRoleResponses];

export type RoleServicesGetCompanyRolesData = {
  body?: never;
  path: {
    companyId: string;
  };
  query?: never;
  url: '/permissions/roles/company/{companyId}';
};

export type RoleServicesGetCompanyRolesErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type RoleServicesGetCompanyRolesError =
  RoleServicesGetCompanyRolesErrors[keyof RoleServicesGetCompanyRolesErrors];

export type RoleServicesGetCompanyRolesResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<Role>;
  };
};

export type RoleServicesGetCompanyRolesResponse =
  RoleServicesGetCompanyRolesResponses[keyof RoleServicesGetCompanyRolesResponses];

export type RoleServicesAssignPermissionToRoleData = {
  body: CreateRolePermission;
  path?: never;
  query?: never;
  url: '/permissions/roles/permissions';
};

export type RoleServicesAssignPermissionToRoleErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type RoleServicesAssignPermissionToRoleError =
  RoleServicesAssignPermissionToRoleErrors[keyof RoleServicesAssignPermissionToRoleErrors];

export type RoleServicesAssignPermissionToRoleResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: RolePermission;
  };
};

export type RoleServicesAssignPermissionToRoleResponse =
  RoleServicesAssignPermissionToRoleResponses[keyof RoleServicesAssignPermissionToRoleResponses];

export type RoleServicesGetSystemDefaultRolesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/permissions/roles/system-defaults';
};

export type RoleServicesGetSystemDefaultRolesErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type RoleServicesGetSystemDefaultRolesError =
  RoleServicesGetSystemDefaultRolesErrors[keyof RoleServicesGetSystemDefaultRolesErrors];

export type RoleServicesGetSystemDefaultRolesResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<Role>;
  };
};

export type RoleServicesGetSystemDefaultRolesResponse =
  RoleServicesGetSystemDefaultRolesResponses[keyof RoleServicesGetSystemDefaultRolesResponses];

export type RoleServicesDeleteRoleData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/permissions/roles/{id}';
};

export type RoleServicesDeleteRoleErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type RoleServicesDeleteRoleError =
  RoleServicesDeleteRoleErrors[keyof RoleServicesDeleteRoleErrors];

export type RoleServicesDeleteRoleResponses = {
  /**
   * 200 OK without data
   */
  200: BasicResponse;
};

export type RoleServicesDeleteRoleResponse =
  RoleServicesDeleteRoleResponses[keyof RoleServicesDeleteRoleResponses];

export type RoleServicesGetRoleData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/permissions/roles/{id}';
};

export type RoleServicesGetRoleErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type RoleServicesGetRoleError =
  RoleServicesGetRoleErrors[keyof RoleServicesGetRoleErrors];

export type RoleServicesGetRoleResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Role;
  };
};

export type RoleServicesGetRoleResponse =
  RoleServicesGetRoleResponses[keyof RoleServicesGetRoleResponses];

export type RoleServicesUpdateRoleData = {
  body: UpdateRole;
  path: {
    id: string;
  };
  query?: never;
  url: '/permissions/roles/{id}';
};

export type RoleServicesUpdateRoleErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type RoleServicesUpdateRoleError =
  RoleServicesUpdateRoleErrors[keyof RoleServicesUpdateRoleErrors];

export type RoleServicesUpdateRoleResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Role;
  };
};

export type RoleServicesUpdateRoleResponse =
  RoleServicesUpdateRoleResponses[keyof RoleServicesUpdateRoleResponses];

export type RoleServicesGetRolePermissionsData = {
  body?: never;
  path: {
    roleId: string;
  };
  query?: never;
  url: '/permissions/roles/{roleId}/permissions';
};

export type RoleServicesGetRolePermissionsErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type RoleServicesGetRolePermissionsError =
  RoleServicesGetRolePermissionsErrors[keyof RoleServicesGetRolePermissionsErrors];

export type RoleServicesGetRolePermissionsResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<Permission>;
  };
};

export type RoleServicesGetRolePermissionsResponse =
  RoleServicesGetRolePermissionsResponses[keyof RoleServicesGetRolePermissionsResponses];

export type RoleServicesRevokePermissionFromRoleData = {
  body?: never;
  path: {
    roleId: string;
    permissionId: string;
  };
  query?: never;
  url: '/permissions/roles/{roleId}/permissions/{permissionId}';
};

export type RoleServicesRevokePermissionFromRoleErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type RoleServicesRevokePermissionFromRoleError =
  RoleServicesRevokePermissionFromRoleErrors[keyof RoleServicesRevokePermissionFromRoleErrors];

export type RoleServicesRevokePermissionFromRoleResponses = {
  /**
   * 200 OK without data
   */
  200: BasicResponse;
};

export type RoleServicesRevokePermissionFromRoleResponse =
  RoleServicesRevokePermissionFromRoleResponses[keyof RoleServicesRevokePermissionFromRoleResponses];

export type PermissionServicesDeletePermissionData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/permissions/{id}';
};

export type PermissionServicesDeletePermissionErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type PermissionServicesDeletePermissionError =
  PermissionServicesDeletePermissionErrors[keyof PermissionServicesDeletePermissionErrors];

export type PermissionServicesDeletePermissionResponses = {
  /**
   * 200 OK without data
   */
  200: BasicResponse;
};

export type PermissionServicesDeletePermissionResponse =
  PermissionServicesDeletePermissionResponses[keyof PermissionServicesDeletePermissionResponses];

export type PermissionServicesUpdatePermissionData = {
  body: UpdatePermission;
  path: {
    id: string;
  };
  query?: never;
  url: '/permissions/{id}';
};

export type PermissionServicesUpdatePermissionErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type PermissionServicesUpdatePermissionError =
  PermissionServicesUpdatePermissionErrors[keyof PermissionServicesUpdatePermissionErrors];

export type PermissionServicesUpdatePermissionResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Permission;
  };
};

export type PermissionServicesUpdatePermissionResponse =
  PermissionServicesUpdatePermissionResponses[keyof PermissionServicesUpdatePermissionResponses];

export type UserServicesGetUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/users/';
};

export type UserServicesGetUsersErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type UserServicesGetUsersError =
  UserServicesGetUsersErrors[keyof UserServicesGetUsersErrors];

export type UserServicesGetUsersResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<User>;
  };
};

export type UserServicesGetUsersResponse =
  UserServicesGetUsersResponses[keyof UserServicesGetUsersResponses];

export type UserServicesCreateUserData = {
  body: CreateUser;
  path?: never;
  query?: never;
  url: '/users/';
};

export type UserServicesCreateUserErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type UserServicesCreateUserError =
  UserServicesCreateUserErrors[keyof UserServicesCreateUserErrors];

export type UserServicesCreateUserResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: User;
  };
};

export type UserServicesCreateUserResponse =
  UserServicesCreateUserResponses[keyof UserServicesCreateUserResponses];

export type UserServicesDeleteUserData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/users/{id}';
};

export type UserServicesDeleteUserErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type UserServicesDeleteUserError =
  UserServicesDeleteUserErrors[keyof UserServicesDeleteUserErrors];

export type UserServicesDeleteUserResponses = {
  /**
   * 200 OK without data
   */
  200: BasicResponse;
};

export type UserServicesDeleteUserResponse =
  UserServicesDeleteUserResponses[keyof UserServicesDeleteUserResponses];

export type UserServicesGetUserData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/users/{id}';
};

export type UserServicesGetUserErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type UserServicesGetUserError =
  UserServicesGetUserErrors[keyof UserServicesGetUserErrors];

export type UserServicesGetUserResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: User;
  };
};

export type UserServicesGetUserResponse =
  UserServicesGetUserResponses[keyof UserServicesGetUserResponses];

export type UserServicesUpdateUserData = {
  body: UpdateUser;
  path: {
    id: string;
  };
  query?: never;
  url: '/users/{id}';
};

export type UserServicesUpdateUserErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type UserServicesUpdateUserError =
  UserServicesUpdateUserErrors[keyof UserServicesUpdateUserErrors];

export type UserServicesUpdateUserResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: User;
  };
};

export type UserServicesUpdateUserResponse =
  UserServicesUpdateUserResponses[keyof UserServicesUpdateUserResponses];
