// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};

export type AnswerInput = {
  fieldId: string;
  value?: unknown;
};

/**
 * Error response returned on failures
 */
export type ApiErrorResponse = {
  success: boolean;
  message: string;
  error?: string;
};

/**
 * 403 Forbidden — FORBIDDEN
 */
export type ApiForbiddenResponse = {
  body: ApiErrorResponse;
};

/**
 * 500 Internal Server Error — INTERNAL_ERROR
 */
export type ApiInternalErrorResponse = {
  body: ApiErrorResponse;
};

export type AssignFormRolesRequest = {
  roleIds: Array<string>;
};

export type AttendanceLog = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyMemberId: string;
  scheduleSlotId: string;
  workDate: string;
  checkedInAt?: Date | null;
  status: DomainEntityAttendanceStatus;
  note?: string | null;
  recordedBy?: string | null;
};

/**
 * Successful response without data payload
 */
export type BasicResponse = {
  success: boolean;
  message: string;
};

export type CheckInRequest = {
  companyMemberId: string;
  scheduleSlotId?: string;
  note?: string;
};

export type CheckInSchedule = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  roleId: string;
  companyId: string;
  name: string;
  isActive: boolean;
};

export type CloneFormSubmissionRequest = {
  memberId: string;
};

export type Company = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  name: string;
  slug: string;
  logo?: string | null;
  isActive: boolean;
};

export type CompanyBranch = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyId: string;
  name: string;
  address?: string | null;
  isActive: boolean;
};

export type CompanyFeature = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyId: string;
  featureId: string;
  isEnabled: boolean;
  assignedBy?: string | null;
  expiresAt?: Date | null;
};

export type CompanyMember = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyBranchId: string;
  companyId: string;
  userId: string;
  roleId: string;
  isActive: boolean;
};

/**
 * The template for picking properties.
 */
export type CompanyToggleFeatureRequest = {
  featureId: string;
  isEnabled: boolean;
};

/**
 * The template for omitting properties.
 */
export type CreateAttendanceLog = {
  companyMemberId: string;
  scheduleSlotId: string;
  workDate: string;
  checkedInAt?: Date | null;
  status: DomainEntityAttendanceStatus;
  note?: string | null;
  recordedBy?: string | null;
};

/**
 * The template for omitting properties.
 */
export type CreateCheckInSchedule = {
  roleId: string;
  companyId: string;
  name: string;
  isActive: boolean;
};

/**
 * The template for omitting properties.
 */
export type CreateCompany = {
  name: string;
  slug: string;
  logo?: string | null;
  isActive: boolean;
};

/**
 * The template for omitting properties.
 */
export type CreateCompanyBranch = {
  companyId: string;
  name: string;
  address?: string | null;
  isActive: boolean;
};

/**
 * The template for omitting properties.
 */
export type CreateCompanyFeature = {
  companyId: string;
  featureId: string;
  isEnabled: boolean;
  assignedBy?: string | null;
  expiresAt?: Date | null;
};

export type CreateCompanyMember = {
  companyId: string;
  userId: string;
  roleId: string;
  isActive: boolean;
  companyBranchId?: string | null;
};

/**
 * The template for omitting properties.
 */
export type CreateFeature = {
  code: string;
  name: string;
  description?: string | null;
  category: string;
  isActive: boolean;
};

/**
 * The template for omitting properties.
 */
export type CreateFormField = {
  companyId: string;
  formVersionId: string;
  formSectionId: string;
  type: DomainEntityFormFieldType;
  label: string;
  description?: string | null;
  isRequired: boolean;
  sortOrder: number;
  config: {
    [key: string]: unknown;
  };
};

/**
 * The template for omitting properties.
 */
export type CreateFormSection = {
  companyId: string;
  formVersionId: string;
  title: string;
  description?: string | null;
  sortOrder: number;
};

/**
 * The template for omitting properties.
 */
export type CreateFormTemplate = {
  companyId: string;
  name: string;
  description?: string | null;
  isActive: boolean;
  createdBy: string;
};

/**
 * The template for omitting properties.
 */
export type CreateLeaveQuota = {
  companyMemberId: string;
  leaveTypeId: string;
  year: number;
  totalDays: number;
  usedDays: number;
};

/**
 * The template for omitting properties.
 */
export type CreateLeaveRequest = {
  companyMemberId: string;
  leaveTypeId: string;
  startDate: string;
  endDate: string;
  totalDays: number;
  unit: DomainEntityLeaveUnit;
  reason: string;
  proofUrl?: string | null;
};

/**
 * The template for omitting properties.
 */
export type CreateLeaveType = {
  companyId: string;
  name: string;
  description?: string | null;
  unit: DomainEntityLeaveUnit;
  requiresProof: boolean;
  maxDaysPerYear?: number | null;
  isPaid: boolean;
  isActive: boolean;
};

/**
 * The template for omitting properties.
 */
export type CreatePermission = {
  featureId?: string | null;
  action: string;
  module: string;
  description?: string | null;
};

/**
 * The template for omitting properties.
 */
export type CreateRole = {
  companyId?: string | null;
  name: string;
  description?: string | null;
  roleType: DomainEntityRoleType;
  isSystemDefault: boolean;
};

/**
 * The template for omitting properties.
 */
export type CreateRoleFeature = {
  companyId: string;
  roleId: string;
  featureId: string;
  isEnabled: boolean;
};

/**
 * The template for omitting properties.
 */
export type CreateRolePermission = {
  roleId: string;
  permissionId: string;
};

/**
 * The template for omitting properties.
 */
export type CreateScheduleSlot = {
  checkInScheduleId: string;
  slotOrder: number;
  label: string;
  windowStart: string;
  windowEnd: string;
  isRequired: boolean;
};

/**
 * The template for omitting properties.
 */
export type CreateUser = {
  name: string;
  email: string;
  image?: string | null;
  isAdmin: boolean;
  isActive: boolean;
  password?: string | null;
};

export type DomainEntityAttendanceStatus =
  | 'present'
  | 'absent'
  | 'late'
  | 'excused';

export type DomainEntityFormFieldType =
  | 'TEXT'
  | 'NUMBER'
  | 'SELECT'
  | 'BOOLEAN'
  | 'DATE'
  | 'IMAGE'
  | 'FILE';

export type DomainEntityFormSubmissionStatus =
  | 'DRAFT'
  | 'SUBMITTED'
  | 'APPROVED'
  | 'REJECTED';

export type DomainEntityFormVersionStatus = 'DRAFT' | 'PUBLISHED' | 'ARCHIVED';

export type DomainEntityLeaveRequestStatus =
  | 'pending'
  | 'approved'
  | 'rejected'
  | 'cancelled';

export type DomainEntityLeaveUnit = 'day' | 'half_day' | 'hour';

export type DomainEntityRoleType =
  | 'SUPER_ADMIN'
  | 'OWNER'
  | 'ADMIN'
  | 'MEMBER'
  | 'VIEWER';

export type DomainEntitySubmissionReviewAction = 'APPROVE' | 'REJECT';

export type Feature = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  code: string;
  name: string;
  description?: string | null;
  category: string;
  isActive: boolean;
};

export type FeatureAccessResponse = {
  hasAccess: boolean;
};

export type FormAnswer = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyId: string;
  formVersionId: string;
  submissionId: string;
  fieldId: string;
  value?: unknown;
  updatedBy: string;
};

export type FormAnswerAttachment = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyId: string;
  answerId: string;
  storageKey: string;
  originalName: string;
  mimeType: string;
  sizeBytes: number;
  sortOrder: number;
  uploadedBy: string;
};

export type FormField = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyId: string;
  formVersionId: string;
  formSectionId: string;
  type: DomainEntityFormFieldType;
  label: string;
  description?: string | null;
  isRequired: boolean;
  sortOrder: number;
  config: {
    [key: string]: unknown;
  };
};

export type FormSection = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyId: string;
  formVersionId: string;
  title: string;
  description?: string | null;
  sortOrder: number;
};

export type FormSubmission = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyId: string;
  formTemplateId: string;
  formVersionId: string;
  roleId: string;
  startedBy: string;
  submittedBy?: string | null;
  revision: number;
  supersedesSubmissionId?: string | null;
  status: DomainEntityFormSubmissionStatus;
  startedAt: Date;
  submittedAt?: Date | null;
};

export type FormSubmissionContributor = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyId: string;
  submissionId: string;
  memberId: string;
};

export type FormSubmissionDetail = {
  submission: FormSubmission;
  template: FormTemplate | null;
  version: FormVersion | null;
  sections: Array<FormSection>;
  fields: Array<FormField>;
  answers: Array<FormAnswer>;
  contributors: Array<FormSubmissionContributor>;
  review: SubmissionReview | null;
};

export type FormTemplate = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyId: string;
  name: string;
  description?: string | null;
  isActive: boolean;
  createdBy: string;
};

export type FormTemplateDetail = {
  template: FormTemplate;
  activeVersion: FormVersion | null;
  draftVersion: FormVersion | null;
  roles: Array<FormTemplateRole>;
  sections: Array<FormSection>;
  fields: Array<FormField>;
};

export type FormTemplateRole = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyId: string;
  formTemplateId: string;
  roleId: string;
  isEnabled: boolean;
};

export type FormVersion = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyId: string;
  formTemplateId: string;
  version: number;
  status: DomainEntityFormVersionStatus;
  title: string;
  description?: string | null;
  createdBy: string;
  publishedBy?: string | null;
  publishedAt?: Date | null;
};

export type LeaveQuota = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyMemberId: string;
  leaveTypeId: string;
  year: number;
  totalDays: number;
  usedDays: number;
};

export type LeaveRequest = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyMemberId: string;
  leaveTypeId: string;
  startDate: string;
  endDate: string;
  totalDays: number;
  unit: DomainEntityLeaveUnit;
  reason: string;
  proofUrl?: string | null;
  status: DomainEntityLeaveRequestStatus;
  reviewedBy?: string | null;
  reviewedAt?: Date | null;
  reviewNote?: string | null;
};

export type LeaveType = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyId: string;
  name: string;
  description?: string | null;
  unit: DomainEntityLeaveUnit;
  requiresProof: boolean;
  maxDaysPerYear?: number | null;
  isPaid: boolean;
  isActive: boolean;
};

export type Permission = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  featureId?: string | null;
  action: string;
  module: string;
  description?: string | null;
};

export type PublishFormVersionRequest = {
  memberId: string;
};

export type ReviewFormSubmissionRequest = {
  memberId: string;
  action: DomainEntitySubmissionReviewAction;
  note?: string;
};

export type ReviewLeaveRequestRequest = {
  action: 'approved' | 'rejected';
  reviewNote?: string;
};

export type Role = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyId?: string | null;
  name: string;
  description?: string | null;
  roleType: DomainEntityRoleType;
  isSystemDefault: boolean;
};

export type RoleFeature = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyId: string;
  roleId: string;
  featureId: string;
  isEnabled: boolean;
};

export type RolePermission = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  roleId: string;
  permissionId: string;
};

/**
 * The template for picking properties.
 */
export type RoleToggleFeatureRequest = {
  companyId: string;
  featureId: string;
  isEnabled: boolean;
};

export type SaveFormSubmissionDraftRequest = {
  memberId: string;
  expectedRevision: number;
  answers: Array<AnswerInput>;
};

export type ScheduleSlot = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  checkInScheduleId: string;
  slotOrder: number;
  label: string;
  windowStart: string;
  windowEnd: string;
  isRequired: boolean;
};

export type StartFormSubmissionRequest = {
  formTemplateId: string;
  roleId: string;
  memberId: string;
};

export type SubmissionReview = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  companyId: string;
  submissionId: string;
  reviewedBy: string;
  action: DomainEntitySubmissionReviewAction;
  note?: string | null;
};

export type SubmitFormSubmissionRequest = {
  memberId: string;
  expectedRevision: number;
};

export type SwitchActiveCompanyResponse = {
  activeCompanyId: string;
  company: Company;
};

/**
 * The template for picking properties.
 */
export type ToggleFeatureRequest = {
  isActive: boolean;
};

/**
 * The template for adding optional properties.
 */
export type UpdateAttendanceLog = {
  companyMemberId?: string;
  scheduleSlotId?: string;
  workDate?: string;
  checkedInAt?: Date | null;
  status?: DomainEntityAttendanceStatus;
  note?: string | null;
  recordedBy?: string | null;
};

/**
 * The template for adding optional properties.
 */
export type UpdateCheckInSchedule = {
  roleId?: string;
  companyId?: string;
  name?: string;
  isActive?: boolean;
};

/**
 * The template for adding optional properties.
 */
export type UpdateCompany = {
  name?: string;
  slug?: string;
  logo?: string | null;
  isActive?: boolean;
};

/**
 * The template for adding optional properties.
 */
export type UpdateCompanyBranch = {
  companyId?: string;
  name?: string;
  address?: string | null;
  isActive?: boolean;
};

/**
 * The template for adding optional properties.
 */
export type UpdateCompanyMember = {
  companyBranchId?: string;
  companyId?: string;
  userId?: string;
  roleId?: string;
  isActive?: boolean;
};

/**
 * The template for adding optional properties.
 */
export type UpdateFeature = {
  code?: string;
  name?: string;
  description?: string | null;
  category?: string;
  isActive?: boolean;
};

/**
 * The template for adding optional properties.
 */
export type UpdateFormTemplate = {
  companyId?: string;
  name?: string;
  description?: string | null;
  isActive?: boolean;
  createdBy?: string;
};

/**
 * The template for adding optional properties.
 */
export type UpdateLeaveQuota = {
  companyMemberId?: string;
  leaveTypeId?: string;
  year?: number;
  totalDays?: number;
  usedDays?: number;
};

/**
 * The template for adding optional properties.
 */
export type UpdateLeaveType = {
  companyId?: string;
  name?: string;
  description?: string | null;
  unit?: DomainEntityLeaveUnit;
  requiresProof?: boolean;
  maxDaysPerYear?: number | null;
  isPaid?: boolean;
  isActive?: boolean;
};

/**
 * The template for adding optional properties.
 */
export type UpdatePermission = {
  featureId?: string | null;
  action?: string;
  module?: string;
  description?: string | null;
};

/**
 * The template for adding optional properties.
 */
export type UpdateRole = {
  companyId?: string | null;
  name?: string;
  description?: string | null;
  roleType?: DomainEntityRoleType;
  isSystemDefault?: boolean;
};

/**
 * The template for adding optional properties.
 */
export type UpdateScheduleSlot = {
  checkInScheduleId?: string;
  slotOrder?: number;
  label?: string;
  windowStart?: string;
  windowEnd?: string;
  isRequired?: boolean;
};

/**
 * The template for adding optional properties.
 */
export type UpdateUser = {
  name?: string;
  email?: string;
  emailVerified?: boolean;
  image?: string | null;
  isAdmin?: boolean;
  isActive?: boolean;
  lastLogin?: Date | null;
};

export type User = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  name: string;
  email: string;
  emailVerified: boolean;
  image?: string | null;
  isAdmin: boolean;
  isActive: boolean;
  lastLogin?: Date | null;
};

export type AttendanceServicesCheckInData = {
  body: CheckInRequest;
  path?: never;
  query?: never;
  url: '/attendances/check-in';
};

export type AttendanceServicesCheckInErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type AttendanceServicesCheckInError =
  AttendanceServicesCheckInErrors[keyof AttendanceServicesCheckInErrors];

export type AttendanceServicesCheckInResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: AttendanceLog;
  };
};

export type AttendanceServicesCheckInResponse =
  AttendanceServicesCheckInResponses[keyof AttendanceServicesCheckInResponses];

export type AttendanceServicesGetCompanyLogsData = {
  body?: never;
  path: {
    companyId: string;
  };
  query: {
    startDate: string;
    endDate: string;
  };
  url: '/attendances/companies/{companyId}/logs';
};

export type AttendanceServicesGetCompanyLogsErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type AttendanceServicesGetCompanyLogsError =
  AttendanceServicesGetCompanyLogsErrors[keyof AttendanceServicesGetCompanyLogsErrors];

export type AttendanceServicesGetCompanyLogsResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<AttendanceLog>;
  };
};

export type AttendanceServicesGetCompanyLogsResponse =
  AttendanceServicesGetCompanyLogsResponses[keyof AttendanceServicesGetCompanyLogsResponses];

export type AttendanceServicesGetSchedulesByCompanyData = {
  body?: never;
  path: {
    companyId: string;
  };
  query?: never;
  url: '/attendances/companies/{companyId}/schedules';
};

export type AttendanceServicesGetSchedulesByCompanyErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type AttendanceServicesGetSchedulesByCompanyError =
  AttendanceServicesGetSchedulesByCompanyErrors[keyof AttendanceServicesGetSchedulesByCompanyErrors];

export type AttendanceServicesGetSchedulesByCompanyResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<CheckInSchedule>;
  };
};

export type AttendanceServicesGetSchedulesByCompanyResponse =
  AttendanceServicesGetSchedulesByCompanyResponses[keyof AttendanceServicesGetSchedulesByCompanyResponses];

export type AttendanceServicesManualCheckInData = {
  body: CreateAttendanceLog;
  path?: never;
  query?: never;
  url: '/attendances/manual-check-in';
};

export type AttendanceServicesManualCheckInErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type AttendanceServicesManualCheckInError =
  AttendanceServicesManualCheckInErrors[keyof AttendanceServicesManualCheckInErrors];

export type AttendanceServicesManualCheckInResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: AttendanceLog;
  };
};

export type AttendanceServicesManualCheckInResponse =
  AttendanceServicesManualCheckInResponses[keyof AttendanceServicesManualCheckInResponses];

export type AttendanceServicesGetMemberLogsData = {
  body?: never;
  path: {
    memberId: string;
  };
  query?: {
    workDate?: string;
    startDate?: string;
    endDate?: string;
  };
  url: '/attendances/members/{memberId}/logs';
};

export type AttendanceServicesGetMemberLogsErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type AttendanceServicesGetMemberLogsError =
  AttendanceServicesGetMemberLogsErrors[keyof AttendanceServicesGetMemberLogsErrors];

export type AttendanceServicesGetMemberLogsResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<AttendanceLog>;
  };
};

export type AttendanceServicesGetMemberLogsResponse =
  AttendanceServicesGetMemberLogsResponses[keyof AttendanceServicesGetMemberLogsResponses];

export type AttendanceServicesGetScheduleByRoleData = {
  body?: never;
  path: {
    roleId: string;
  };
  query?: never;
  url: '/attendances/roles/{roleId}/schedule';
};

export type AttendanceServicesGetScheduleByRoleErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type AttendanceServicesGetScheduleByRoleError =
  AttendanceServicesGetScheduleByRoleErrors[keyof AttendanceServicesGetScheduleByRoleErrors];

export type AttendanceServicesGetScheduleByRoleResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: CheckInSchedule;
  };
};

export type AttendanceServicesGetScheduleByRoleResponse =
  AttendanceServicesGetScheduleByRoleResponses[keyof AttendanceServicesGetScheduleByRoleResponses];

export type AttendanceServicesCreateScheduleData = {
  body: CreateCheckInSchedule;
  path?: never;
  query?: never;
  url: '/attendances/schedules';
};

export type AttendanceServicesCreateScheduleErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type AttendanceServicesCreateScheduleError =
  AttendanceServicesCreateScheduleErrors[keyof AttendanceServicesCreateScheduleErrors];

export type AttendanceServicesCreateScheduleResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: CheckInSchedule;
  };
};

export type AttendanceServicesCreateScheduleResponse =
  AttendanceServicesCreateScheduleResponses[keyof AttendanceServicesCreateScheduleResponses];

export type AttendanceServicesUpdateScheduleData = {
  body: UpdateCheckInSchedule;
  path: {
    id: string;
  };
  query?: never;
  url: '/attendances/schedules/{id}';
};

export type AttendanceServicesUpdateScheduleErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type AttendanceServicesUpdateScheduleError =
  AttendanceServicesUpdateScheduleErrors[keyof AttendanceServicesUpdateScheduleErrors];

export type AttendanceServicesUpdateScheduleResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: CheckInSchedule;
  };
};

export type AttendanceServicesUpdateScheduleResponse =
  AttendanceServicesUpdateScheduleResponses[keyof AttendanceServicesUpdateScheduleResponses];

export type AttendanceServicesGetSlotsByScheduleData = {
  body?: never;
  path: {
    scheduleId: string;
  };
  query?: never;
  url: '/attendances/schedules/{scheduleId}/slots';
};

export type AttendanceServicesGetSlotsByScheduleErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type AttendanceServicesGetSlotsByScheduleError =
  AttendanceServicesGetSlotsByScheduleErrors[keyof AttendanceServicesGetSlotsByScheduleErrors];

export type AttendanceServicesGetSlotsByScheduleResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<ScheduleSlot>;
  };
};

export type AttendanceServicesGetSlotsByScheduleResponse =
  AttendanceServicesGetSlotsByScheduleResponses[keyof AttendanceServicesGetSlotsByScheduleResponses];

export type AttendanceServicesCreateSlotData = {
  body: CreateScheduleSlot;
  path: {
    scheduleId: string;
  };
  query?: never;
  url: '/attendances/schedules/{scheduleId}/slots';
};

export type AttendanceServicesCreateSlotErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type AttendanceServicesCreateSlotError =
  AttendanceServicesCreateSlotErrors[keyof AttendanceServicesCreateSlotErrors];

export type AttendanceServicesCreateSlotResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: ScheduleSlot;
  };
};

export type AttendanceServicesCreateSlotResponse =
  AttendanceServicesCreateSlotResponses[keyof AttendanceServicesCreateSlotResponses];

export type AttendanceServicesDeleteSlotData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/attendances/slots/{id}';
};

export type AttendanceServicesDeleteSlotErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type AttendanceServicesDeleteSlotError =
  AttendanceServicesDeleteSlotErrors[keyof AttendanceServicesDeleteSlotErrors];

export type AttendanceServicesDeleteSlotResponses = {
  /**
   * 200 OK without data
   */
  200: BasicResponse;
};

export type AttendanceServicesDeleteSlotResponse =
  AttendanceServicesDeleteSlotResponses[keyof AttendanceServicesDeleteSlotResponses];

export type AttendanceServicesUpdateSlotData = {
  body: UpdateScheduleSlot;
  path: {
    id: string;
  };
  query?: never;
  url: '/attendances/slots/{id}';
};

export type AttendanceServicesUpdateSlotErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type AttendanceServicesUpdateSlotError =
  AttendanceServicesUpdateSlotErrors[keyof AttendanceServicesUpdateSlotErrors];

export type AttendanceServicesUpdateSlotResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: ScheduleSlot;
  };
};

export type AttendanceServicesUpdateSlotResponse =
  AttendanceServicesUpdateSlotResponses[keyof AttendanceServicesUpdateSlotResponses];

export type CompanyServicesGetCompaniesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/companies/';
};

export type CompanyServicesGetCompaniesErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type CompanyServicesGetCompaniesError =
  CompanyServicesGetCompaniesErrors[keyof CompanyServicesGetCompaniesErrors];

export type CompanyServicesGetCompaniesResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<Company>;
  };
};

export type CompanyServicesGetCompaniesResponse =
  CompanyServicesGetCompaniesResponses[keyof CompanyServicesGetCompaniesResponses];

export type CompanyServicesCreateCompanyData = {
  body: CreateCompany;
  path?: never;
  query?: never;
  url: '/companies/';
};

export type CompanyServicesCreateCompanyErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type CompanyServicesCreateCompanyError =
  CompanyServicesCreateCompanyErrors[keyof CompanyServicesCreateCompanyErrors];

export type CompanyServicesCreateCompanyResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: Company;
  };
};

export type CompanyServicesCreateCompanyResponse =
  CompanyServicesCreateCompanyResponses[keyof CompanyServicesCreateCompanyResponses];

export type CompanyServicesCreateCompanyBranchData = {
  body: CreateCompanyBranch;
  path?: never;
  query?: never;
  url: '/companies/branches';
};

export type CompanyServicesCreateCompanyBranchErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type CompanyServicesCreateCompanyBranchError =
  CompanyServicesCreateCompanyBranchErrors[keyof CompanyServicesCreateCompanyBranchErrors];

export type CompanyServicesCreateCompanyBranchResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: CompanyBranch;
  };
};

export type CompanyServicesCreateCompanyBranchResponse =
  CompanyServicesCreateCompanyBranchResponses[keyof CompanyServicesCreateCompanyBranchResponses];

export type CompanyServicesDeleteCompanyBranchData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    companyId?: string;
  };
  url: '/companies/branches/{id}';
};

export type CompanyServicesDeleteCompanyBranchErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesDeleteCompanyBranchError =
  CompanyServicesDeleteCompanyBranchErrors[keyof CompanyServicesDeleteCompanyBranchErrors];

export type CompanyServicesDeleteCompanyBranchResponses = {
  /**
   * 200 OK without data
   */
  200: BasicResponse;
};

export type CompanyServicesDeleteCompanyBranchResponse =
  CompanyServicesDeleteCompanyBranchResponses[keyof CompanyServicesDeleteCompanyBranchResponses];

export type CompanyServicesGetCompanyBranchData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/companies/branches/{id}';
};

export type CompanyServicesGetCompanyBranchErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesGetCompanyBranchError =
  CompanyServicesGetCompanyBranchErrors[keyof CompanyServicesGetCompanyBranchErrors];

export type CompanyServicesGetCompanyBranchResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: CompanyBranch;
  };
};

export type CompanyServicesGetCompanyBranchResponse =
  CompanyServicesGetCompanyBranchResponses[keyof CompanyServicesGetCompanyBranchResponses];

export type CompanyServicesUpdateCompanyBranchData = {
  body: UpdateCompanyBranch;
  path: {
    id: string;
  };
  query?: never;
  url: '/companies/branches/{id}';
};

export type CompanyServicesUpdateCompanyBranchErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesUpdateCompanyBranchError =
  CompanyServicesUpdateCompanyBranchErrors[keyof CompanyServicesUpdateCompanyBranchErrors];

export type CompanyServicesUpdateCompanyBranchResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: CompanyBranch;
  };
};

export type CompanyServicesUpdateCompanyBranchResponse =
  CompanyServicesUpdateCompanyBranchResponses[keyof CompanyServicesUpdateCompanyBranchResponses];

export type CompanyServicesAddCompanyMemberData = {
  body: CreateCompanyMember;
  path?: never;
  query?: never;
  url: '/companies/members';
};

export type CompanyServicesAddCompanyMemberErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type CompanyServicesAddCompanyMemberError =
  CompanyServicesAddCompanyMemberErrors[keyof CompanyServicesAddCompanyMemberErrors];

export type CompanyServicesAddCompanyMemberResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: CompanyMember;
  };
};

export type CompanyServicesAddCompanyMemberResponse =
  CompanyServicesAddCompanyMemberResponses[keyof CompanyServicesAddCompanyMemberResponses];

export type CompanyServicesRemoveCompanyMemberData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/companies/members/{id}';
};

export type CompanyServicesRemoveCompanyMemberErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesRemoveCompanyMemberError =
  CompanyServicesRemoveCompanyMemberErrors[keyof CompanyServicesRemoveCompanyMemberErrors];

export type CompanyServicesRemoveCompanyMemberResponses = {
  /**
   * 200 OK without data
   */
  200: BasicResponse;
};

export type CompanyServicesRemoveCompanyMemberResponse =
  CompanyServicesRemoveCompanyMemberResponses[keyof CompanyServicesRemoveCompanyMemberResponses];

export type CompanyServicesUpdateCompanyMemberData = {
  body: UpdateCompanyMember;
  path: {
    id: string;
  };
  query?: never;
  url: '/companies/members/{id}';
};

export type CompanyServicesUpdateCompanyMemberErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesUpdateCompanyMemberError =
  CompanyServicesUpdateCompanyMemberErrors[keyof CompanyServicesUpdateCompanyMemberErrors];

export type CompanyServicesUpdateCompanyMemberResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: CompanyMember;
  };
};

export type CompanyServicesUpdateCompanyMemberResponse =
  CompanyServicesUpdateCompanyMemberResponses[keyof CompanyServicesUpdateCompanyMemberResponses];

export type CompanyServicesGetCompanyBySlugData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/companies/slug/{slug}';
};

export type CompanyServicesGetCompanyBySlugErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesGetCompanyBySlugError =
  CompanyServicesGetCompanyBySlugErrors[keyof CompanyServicesGetCompanyBySlugErrors];

export type CompanyServicesGetCompanyBySlugResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Company;
  };
};

export type CompanyServicesGetCompanyBySlugResponse =
  CompanyServicesGetCompanyBySlugResponses[keyof CompanyServicesGetCompanyBySlugResponses];

export type CompanyServicesGetCompanyBranchesData = {
  body?: never;
  path: {
    companyId: string;
  };
  query?: never;
  url: '/companies/{companyId}/branches';
};

export type CompanyServicesGetCompanyBranchesErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesGetCompanyBranchesError =
  CompanyServicesGetCompanyBranchesErrors[keyof CompanyServicesGetCompanyBranchesErrors];

export type CompanyServicesGetCompanyBranchesResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<CompanyBranch>;
  };
};

export type CompanyServicesGetCompanyBranchesResponse =
  CompanyServicesGetCompanyBranchesResponses[keyof CompanyServicesGetCompanyBranchesResponses];

export type CompanyServicesGetCompanyMembersData = {
  body?: never;
  path: {
    companyId: string;
  };
  query?: never;
  url: '/companies/{companyId}/members';
};

export type CompanyServicesGetCompanyMembersErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesGetCompanyMembersError =
  CompanyServicesGetCompanyMembersErrors[keyof CompanyServicesGetCompanyMembersErrors];

export type CompanyServicesGetCompanyMembersResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<CompanyMember>;
  };
};

export type CompanyServicesGetCompanyMembersResponse =
  CompanyServicesGetCompanyMembersResponses[keyof CompanyServicesGetCompanyMembersResponses];

export type CompanyServicesDeleteCompanyData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/companies/{id}';
};

export type CompanyServicesDeleteCompanyErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesDeleteCompanyError =
  CompanyServicesDeleteCompanyErrors[keyof CompanyServicesDeleteCompanyErrors];

export type CompanyServicesDeleteCompanyResponses = {
  /**
   * 200 OK without data
   */
  200: BasicResponse;
};

export type CompanyServicesDeleteCompanyResponse =
  CompanyServicesDeleteCompanyResponses[keyof CompanyServicesDeleteCompanyResponses];

export type CompanyServicesGetCompanyData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/companies/{id}';
};

export type CompanyServicesGetCompanyErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesGetCompanyError =
  CompanyServicesGetCompanyErrors[keyof CompanyServicesGetCompanyErrors];

export type CompanyServicesGetCompanyResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Company;
  };
};

export type CompanyServicesGetCompanyResponse =
  CompanyServicesGetCompanyResponses[keyof CompanyServicesGetCompanyResponses];

export type CompanyServicesUpdateCompanyData = {
  body: UpdateCompany;
  path: {
    id: string;
  };
  query?: never;
  url: '/companies/{id}';
};

export type CompanyServicesUpdateCompanyErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesUpdateCompanyError =
  CompanyServicesUpdateCompanyErrors[keyof CompanyServicesUpdateCompanyErrors];

export type CompanyServicesUpdateCompanyResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Company;
  };
};

export type CompanyServicesUpdateCompanyResponse =
  CompanyServicesUpdateCompanyResponses[keyof CompanyServicesUpdateCompanyResponses];

export type CompanyServicesSwitchActiveCompanyData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/companies/{id}/switch';
};

export type CompanyServicesSwitchActiveCompanyErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type CompanyServicesSwitchActiveCompanyError =
  CompanyServicesSwitchActiveCompanyErrors[keyof CompanyServicesSwitchActiveCompanyErrors];

export type CompanyServicesSwitchActiveCompanyResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: SwitchActiveCompanyResponse;
  };
};

export type CompanyServicesSwitchActiveCompanyResponse =
  CompanyServicesSwitchActiveCompanyResponses[keyof CompanyServicesSwitchActiveCompanyResponses];

export type FeatureServicesGetFeaturesData = {
  body?: never;
  path?: never;
  query?: {
    category?: string;
    isActive?: boolean;
  };
  url: '/features/';
};

export type FeatureServicesGetFeaturesErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type FeatureServicesGetFeaturesError =
  FeatureServicesGetFeaturesErrors[keyof FeatureServicesGetFeaturesErrors];

export type FeatureServicesGetFeaturesResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<Feature>;
  };
};

export type FeatureServicesGetFeaturesResponse =
  FeatureServicesGetFeaturesResponses[keyof FeatureServicesGetFeaturesResponses];

export type FeatureServicesCreateFeatureData = {
  body: CreateFeature;
  path?: never;
  query?: never;
  url: '/features/';
};

export type FeatureServicesCreateFeatureErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type FeatureServicesCreateFeatureError =
  FeatureServicesCreateFeatureErrors[keyof FeatureServicesCreateFeatureErrors];

export type FeatureServicesCreateFeatureResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: Feature;
  };
};

export type FeatureServicesCreateFeatureResponse =
  FeatureServicesCreateFeatureResponses[keyof FeatureServicesCreateFeatureResponses];

export type FeatureServicesGetCompanyFeaturesData = {
  body?: never;
  path: {
    companyId: string;
  };
  query?: {
    onlyEnabled?: boolean;
  };
  url: '/features/companies/{companyId}';
};

export type FeatureServicesGetCompanyFeaturesErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type FeatureServicesGetCompanyFeaturesError =
  FeatureServicesGetCompanyFeaturesErrors[keyof FeatureServicesGetCompanyFeaturesErrors];

export type FeatureServicesGetCompanyFeaturesResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<CompanyFeature>;
  };
};

export type FeatureServicesGetCompanyFeaturesResponse =
  FeatureServicesGetCompanyFeaturesResponses[keyof FeatureServicesGetCompanyFeaturesResponses];

export type FeatureServicesAssignCompanyFeatureData = {
  body: CreateCompanyFeature;
  path: {
    companyId: string;
  };
  query?: never;
  url: '/features/companies/{companyId}/assign';
};

export type FeatureServicesAssignCompanyFeatureErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type FeatureServicesAssignCompanyFeatureError =
  FeatureServicesAssignCompanyFeatureErrors[keyof FeatureServicesAssignCompanyFeatureErrors];

export type FeatureServicesAssignCompanyFeatureResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: CompanyFeature;
  };
};

export type FeatureServicesAssignCompanyFeatureResponse =
  FeatureServicesAssignCompanyFeatureResponses[keyof FeatureServicesAssignCompanyFeatureResponses];

export type FeatureServicesGetCompanyAvailableFeaturesData = {
  body?: never;
  path: {
    companyId: string;
  };
  query?: never;
  url: '/features/companies/{companyId}/available';
};

export type FeatureServicesGetCompanyAvailableFeaturesErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type FeatureServicesGetCompanyAvailableFeaturesError =
  FeatureServicesGetCompanyAvailableFeaturesErrors[keyof FeatureServicesGetCompanyAvailableFeaturesErrors];

export type FeatureServicesGetCompanyAvailableFeaturesResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<Feature>;
  };
};

export type FeatureServicesGetCompanyAvailableFeaturesResponse =
  FeatureServicesGetCompanyAvailableFeaturesResponses[keyof FeatureServicesGetCompanyAvailableFeaturesResponses];

export type FeatureServicesRemoveCompanyFeatureData = {
  body?: never;
  path: {
    companyId: string;
    featureId: string;
  };
  query?: never;
  url: '/features/companies/{companyId}/features/{featureId}';
};

export type FeatureServicesRemoveCompanyFeatureErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type FeatureServicesRemoveCompanyFeatureError =
  FeatureServicesRemoveCompanyFeatureErrors[keyof FeatureServicesRemoveCompanyFeatureErrors];

export type FeatureServicesRemoveCompanyFeatureResponses = {
  /**
   * 200 OK without data
   */
  200: BasicResponse;
};

export type FeatureServicesRemoveCompanyFeatureResponse =
  FeatureServicesRemoveCompanyFeatureResponses[keyof FeatureServicesRemoveCompanyFeatureResponses];

export type FeatureServicesGetCompanyRoleFeaturesData = {
  body?: never;
  path: {
    companyId: string;
  };
  query?: never;
  url: '/features/companies/{companyId}/roles';
};

export type FeatureServicesGetCompanyRoleFeaturesErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type FeatureServicesGetCompanyRoleFeaturesError =
  FeatureServicesGetCompanyRoleFeaturesErrors[keyof FeatureServicesGetCompanyRoleFeaturesErrors];

export type FeatureServicesGetCompanyRoleFeaturesResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<RoleFeature>;
  };
};

export type FeatureServicesGetCompanyRoleFeaturesResponse =
  FeatureServicesGetCompanyRoleFeaturesResponses[keyof FeatureServicesGetCompanyRoleFeaturesResponses];

export type FeatureServicesCheckRoleFeatureAccessData = {
  body?: never;
  path: {
    companyId: string;
    roleId: string;
    featureCode: string;
  };
  query?: never;
  url: '/features/companies/{companyId}/roles/{roleId}/access/{featureCode}';
};

export type FeatureServicesCheckRoleFeatureAccessErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type FeatureServicesCheckRoleFeatureAccessError =
  FeatureServicesCheckRoleFeatureAccessErrors[keyof FeatureServicesCheckRoleFeatureAccessErrors];

export type FeatureServicesCheckRoleFeatureAccessResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: FeatureAccessResponse;
  };
};

export type FeatureServicesCheckRoleFeatureAccessResponse =
  FeatureServicesCheckRoleFeatureAccessResponses[keyof FeatureServicesCheckRoleFeatureAccessResponses];

export type FeatureServicesToggleCompanyFeatureData = {
  body: CompanyToggleFeatureRequest;
  path: {
    companyId: string;
  };
  query?: never;
  url: '/features/companies/{companyId}/toggle';
};

export type FeatureServicesToggleCompanyFeatureErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type FeatureServicesToggleCompanyFeatureError =
  FeatureServicesToggleCompanyFeatureErrors[keyof FeatureServicesToggleCompanyFeatureErrors];

export type FeatureServicesToggleCompanyFeatureResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: CompanyFeature;
  };
};

export type FeatureServicesToggleCompanyFeatureResponse =
  FeatureServicesToggleCompanyFeatureResponses[keyof FeatureServicesToggleCompanyFeatureResponses];

export type FeatureServicesGetRoleFeaturesData = {
  body?: never;
  path: {
    roleId: string;
  };
  query?: never;
  url: '/features/roles/{roleId}';
};

export type FeatureServicesGetRoleFeaturesErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type FeatureServicesGetRoleFeaturesError =
  FeatureServicesGetRoleFeaturesErrors[keyof FeatureServicesGetRoleFeaturesErrors];

export type FeatureServicesGetRoleFeaturesResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<Feature>;
  };
};

export type FeatureServicesGetRoleFeaturesResponse =
  FeatureServicesGetRoleFeaturesResponses[keyof FeatureServicesGetRoleFeaturesResponses];

export type FeatureServicesAssignRoleFeatureData = {
  body: CreateRoleFeature;
  path: {
    roleId: string;
  };
  query?: never;
  url: '/features/roles/{roleId}/assign';
};

export type FeatureServicesAssignRoleFeatureErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type FeatureServicesAssignRoleFeatureError =
  FeatureServicesAssignRoleFeatureErrors[keyof FeatureServicesAssignRoleFeatureErrors];

export type FeatureServicesAssignRoleFeatureResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: RoleFeature;
  };
};

export type FeatureServicesAssignRoleFeatureResponse =
  FeatureServicesAssignRoleFeatureResponses[keyof FeatureServicesAssignRoleFeatureResponses];

export type FeatureServicesRevokeRoleFeatureData = {
  body?: never;
  path: {
    roleId: string;
    featureId: string;
  };
  query?: {
    companyId?: string;
  };
  url: '/features/roles/{roleId}/features/{featureId}';
};

export type FeatureServicesRevokeRoleFeatureErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type FeatureServicesRevokeRoleFeatureError =
  FeatureServicesRevokeRoleFeatureErrors[keyof FeatureServicesRevokeRoleFeatureErrors];

export type FeatureServicesRevokeRoleFeatureResponses = {
  /**
   * 200 OK without data
   */
  200: BasicResponse;
};

export type FeatureServicesRevokeRoleFeatureResponse =
  FeatureServicesRevokeRoleFeatureResponses[keyof FeatureServicesRevokeRoleFeatureResponses];

export type FeatureServicesToggleRoleFeatureData = {
  body: RoleToggleFeatureRequest;
  path: {
    roleId: string;
  };
  query?: never;
  url: '/features/roles/{roleId}/toggle';
};

export type FeatureServicesToggleRoleFeatureErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type FeatureServicesToggleRoleFeatureError =
  FeatureServicesToggleRoleFeatureErrors[keyof FeatureServicesToggleRoleFeatureErrors];

export type FeatureServicesToggleRoleFeatureResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: RoleFeature;
  };
};

export type FeatureServicesToggleRoleFeatureResponse =
  FeatureServicesToggleRoleFeatureResponses[keyof FeatureServicesToggleRoleFeatureResponses];

export type FeatureServicesGetFeatureData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/features/{id}';
};

export type FeatureServicesGetFeatureErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type FeatureServicesGetFeatureError =
  FeatureServicesGetFeatureErrors[keyof FeatureServicesGetFeatureErrors];

export type FeatureServicesGetFeatureResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Feature;
  };
};

export type FeatureServicesGetFeatureResponse =
  FeatureServicesGetFeatureResponses[keyof FeatureServicesGetFeatureResponses];

export type FeatureServicesUpdateFeatureData = {
  body: UpdateFeature;
  path: {
    id: string;
  };
  query?: never;
  url: '/features/{id}';
};

export type FeatureServicesUpdateFeatureErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type FeatureServicesUpdateFeatureError =
  FeatureServicesUpdateFeatureErrors[keyof FeatureServicesUpdateFeatureErrors];

export type FeatureServicesUpdateFeatureResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Feature;
  };
};

export type FeatureServicesUpdateFeatureResponse =
  FeatureServicesUpdateFeatureResponses[keyof FeatureServicesUpdateFeatureResponses];

export type FeatureServicesToggleFeatureData = {
  body: ToggleFeatureRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/features/{id}/toggle';
};

export type FeatureServicesToggleFeatureErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type FeatureServicesToggleFeatureError =
  FeatureServicesToggleFeatureErrors[keyof FeatureServicesToggleFeatureErrors];

export type FeatureServicesToggleFeatureResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Feature;
  };
};

export type FeatureServicesToggleFeatureResponse =
  FeatureServicesToggleFeatureResponses[keyof FeatureServicesToggleFeatureResponses];

export type FormServicesListTemplatesByCompanyData = {
  body?: never;
  path: {
    companyId: string;
  };
  query?: never;
  url: '/forms/companies/{companyId}/templates';
};

export type FormServicesListTemplatesByCompanyErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type FormServicesListTemplatesByCompanyError =
  FormServicesListTemplatesByCompanyErrors[keyof FormServicesListTemplatesByCompanyErrors];

export type FormServicesListTemplatesByCompanyResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<FormTemplate>;
  };
};

export type FormServicesListTemplatesByCompanyResponse =
  FormServicesListTemplatesByCompanyResponses[keyof FormServicesListTemplatesByCompanyResponses];

export type FormServicesListSubmissionsData = {
  body?: never;
  path?: never;
  query?: {
    companyId?: string;
    roleId?: string;
    formTemplateId?: string;
  };
  url: '/forms/submissions';
};

export type FormServicesListSubmissionsErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type FormServicesListSubmissionsError =
  FormServicesListSubmissionsErrors[keyof FormServicesListSubmissionsErrors];

export type FormServicesListSubmissionsResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<FormSubmission>;
  };
};

export type FormServicesListSubmissionsResponse =
  FormServicesListSubmissionsResponses[keyof FormServicesListSubmissionsResponses];

export type FormServicesStartSubmissionData = {
  body: StartFormSubmissionRequest;
  path?: never;
  query?: never;
  url: '/forms/submissions';
};

export type FormServicesStartSubmissionErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type FormServicesStartSubmissionError =
  FormServicesStartSubmissionErrors[keyof FormServicesStartSubmissionErrors];

export type FormServicesStartSubmissionResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: FormSubmission;
  };
};

export type FormServicesStartSubmissionResponse =
  FormServicesStartSubmissionResponses[keyof FormServicesStartSubmissionResponses];

export type FormServicesGetSubmissionData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/forms/submissions/{id}';
};

export type FormServicesGetSubmissionErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type FormServicesGetSubmissionError =
  FormServicesGetSubmissionErrors[keyof FormServicesGetSubmissionErrors];

export type FormServicesGetSubmissionResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: FormSubmissionDetail;
  };
};

export type FormServicesGetSubmissionResponse =
  FormServicesGetSubmissionResponses[keyof FormServicesGetSubmissionResponses];

export type FormServicesCloneData = {
  body: CloneFormSubmissionRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/forms/submissions/{id}/clone';
};

export type FormServicesCloneErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type FormServicesCloneError =
  FormServicesCloneErrors[keyof FormServicesCloneErrors];

export type FormServicesCloneResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: FormSubmission;
  };
};

export type FormServicesCloneResponse =
  FormServicesCloneResponses[keyof FormServicesCloneResponses];

export type FormServicesSaveDraftData = {
  body: SaveFormSubmissionDraftRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/forms/submissions/{id}/draft';
};

export type FormServicesSaveDraftErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type FormServicesSaveDraftError =
  FormServicesSaveDraftErrors[keyof FormServicesSaveDraftErrors];

export type FormServicesSaveDraftResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: FormSubmission;
  };
};

export type FormServicesSaveDraftResponse =
  FormServicesSaveDraftResponses[keyof FormServicesSaveDraftResponses];

export type FormServicesReviewData = {
  body: ReviewFormSubmissionRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/forms/submissions/{id}/review';
};

export type FormServicesReviewErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type FormServicesReviewError =
  FormServicesReviewErrors[keyof FormServicesReviewErrors];

export type FormServicesReviewResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: SubmissionReview;
  };
};

export type FormServicesReviewResponse =
  FormServicesReviewResponses[keyof FormServicesReviewResponses];

export type FormServicesSubmitData = {
  body: SubmitFormSubmissionRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/forms/submissions/{id}/submit';
};

export type FormServicesSubmitErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type FormServicesSubmitError =
  FormServicesSubmitErrors[keyof FormServicesSubmitErrors];

export type FormServicesSubmitResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: FormSubmission;
  };
};

export type FormServicesSubmitResponse =
  FormServicesSubmitResponses[keyof FormServicesSubmitResponses];

export type FormServicesCreateTemplateData = {
  body: CreateFormTemplate;
  path?: never;
  query?: never;
  url: '/forms/templates';
};

export type FormServicesCreateTemplateErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type FormServicesCreateTemplateError =
  FormServicesCreateTemplateErrors[keyof FormServicesCreateTemplateErrors];

export type FormServicesCreateTemplateResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: FormTemplate;
  };
};

export type FormServicesCreateTemplateResponse =
  FormServicesCreateTemplateResponses[keyof FormServicesCreateTemplateResponses];

export type FormServicesGetTemplateData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/forms/templates/{id}';
};

export type FormServicesGetTemplateErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type FormServicesGetTemplateError =
  FormServicesGetTemplateErrors[keyof FormServicesGetTemplateErrors];

export type FormServicesGetTemplateResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: FormTemplateDetail;
  };
};

export type FormServicesGetTemplateResponse =
  FormServicesGetTemplateResponses[keyof FormServicesGetTemplateResponses];

export type FormServicesUpdateTemplateData = {
  body: UpdateFormTemplate;
  path: {
    id: string;
  };
  query?: never;
  url: '/forms/templates/{id}';
};

export type FormServicesUpdateTemplateErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type FormServicesUpdateTemplateError =
  FormServicesUpdateTemplateErrors[keyof FormServicesUpdateTemplateErrors];

export type FormServicesUpdateTemplateResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: FormTemplate;
  };
};

export type FormServicesUpdateTemplateResponse =
  FormServicesUpdateTemplateResponses[keyof FormServicesUpdateTemplateResponses];

export type FormServicesCreateFieldData = {
  body: CreateFormField;
  path: {
    id: string;
  };
  query?: never;
  url: '/forms/templates/{id}/fields';
};

export type FormServicesCreateFieldErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type FormServicesCreateFieldError =
  FormServicesCreateFieldErrors[keyof FormServicesCreateFieldErrors];

export type FormServicesCreateFieldResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: FormField;
  };
};

export type FormServicesCreateFieldResponse =
  FormServicesCreateFieldResponses[keyof FormServicesCreateFieldResponses];

export type FormServicesPublishVersionData = {
  body: PublishFormVersionRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/forms/templates/{id}/publish';
};

export type FormServicesPublishVersionErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type FormServicesPublishVersionError =
  FormServicesPublishVersionErrors[keyof FormServicesPublishVersionErrors];

export type FormServicesPublishVersionResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: FormVersion;
  };
};

export type FormServicesPublishVersionResponse =
  FormServicesPublishVersionResponses[keyof FormServicesPublishVersionResponses];

export type FormServicesAssignRolesData = {
  body: AssignFormRolesRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/forms/templates/{id}/roles';
};

export type FormServicesAssignRolesErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type FormServicesAssignRolesError =
  FormServicesAssignRolesErrors[keyof FormServicesAssignRolesErrors];

export type FormServicesAssignRolesResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<FormTemplateRole>;
  };
};

export type FormServicesAssignRolesResponse =
  FormServicesAssignRolesResponses[keyof FormServicesAssignRolesResponses];

export type FormServicesCreateSectionData = {
  body: CreateFormSection;
  path: {
    id: string;
  };
  query?: never;
  url: '/forms/templates/{id}/sections';
};

export type FormServicesCreateSectionErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type FormServicesCreateSectionError =
  FormServicesCreateSectionErrors[keyof FormServicesCreateSectionErrors];

export type FormServicesCreateSectionResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: FormSection;
  };
};

export type FormServicesCreateSectionResponse =
  FormServicesCreateSectionResponses[keyof FormServicesCreateSectionResponses];

export type LeaveServicesGetCompanyRequestsData = {
  body?: never;
  path: {
    companyId: string;
  };
  query?: {
    status?: string;
  };
  url: '/leaves/companies/{companyId}/requests';
};

export type LeaveServicesGetCompanyRequestsErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type LeaveServicesGetCompanyRequestsError =
  LeaveServicesGetCompanyRequestsErrors[keyof LeaveServicesGetCompanyRequestsErrors];

export type LeaveServicesGetCompanyRequestsResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<LeaveRequest>;
  };
};

export type LeaveServicesGetCompanyRequestsResponse =
  LeaveServicesGetCompanyRequestsResponses[keyof LeaveServicesGetCompanyRequestsResponses];

export type LeaveServicesGetTypesByCompanyData = {
  body?: never;
  path: {
    companyId: string;
  };
  query?: {
    onlyActive?: boolean;
  };
  url: '/leaves/companies/{companyId}/types';
};

export type LeaveServicesGetTypesByCompanyErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type LeaveServicesGetTypesByCompanyError =
  LeaveServicesGetTypesByCompanyErrors[keyof LeaveServicesGetTypesByCompanyErrors];

export type LeaveServicesGetTypesByCompanyResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<LeaveType>;
  };
};

export type LeaveServicesGetTypesByCompanyResponse =
  LeaveServicesGetTypesByCompanyResponses[keyof LeaveServicesGetTypesByCompanyResponses];

export type LeaveServicesGetQuotasByMemberData = {
  body?: never;
  path: {
    memberId: string;
    year: number;
  };
  query?: never;
  url: '/leaves/members/{memberId}/quotas/{year}';
};

export type LeaveServicesGetQuotasByMemberErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type LeaveServicesGetQuotasByMemberError =
  LeaveServicesGetQuotasByMemberErrors[keyof LeaveServicesGetQuotasByMemberErrors];

export type LeaveServicesGetQuotasByMemberResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<LeaveQuota>;
  };
};

export type LeaveServicesGetQuotasByMemberResponse =
  LeaveServicesGetQuotasByMemberResponses[keyof LeaveServicesGetQuotasByMemberResponses];

export type LeaveServicesGetMemberRequestsData = {
  body?: never;
  path: {
    memberId: string;
  };
  query?: never;
  url: '/leaves/members/{memberId}/requests';
};

export type LeaveServicesGetMemberRequestsErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type LeaveServicesGetMemberRequestsError =
  LeaveServicesGetMemberRequestsErrors[keyof LeaveServicesGetMemberRequestsErrors];

export type LeaveServicesGetMemberRequestsResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<LeaveRequest>;
  };
};

export type LeaveServicesGetMemberRequestsResponse =
  LeaveServicesGetMemberRequestsResponses[keyof LeaveServicesGetMemberRequestsResponses];

export type LeaveServicesCreateQuotaData = {
  body: CreateLeaveQuota;
  path?: never;
  query?: never;
  url: '/leaves/quotas';
};

export type LeaveServicesCreateQuotaErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type LeaveServicesCreateQuotaError =
  LeaveServicesCreateQuotaErrors[keyof LeaveServicesCreateQuotaErrors];

export type LeaveServicesCreateQuotaResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: LeaveQuota;
  };
};

export type LeaveServicesCreateQuotaResponse =
  LeaveServicesCreateQuotaResponses[keyof LeaveServicesCreateQuotaResponses];

export type LeaveServicesUpdateQuotaData = {
  body: UpdateLeaveQuota;
  path: {
    id: string;
  };
  query?: never;
  url: '/leaves/quotas/{id}';
};

export type LeaveServicesUpdateQuotaErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type LeaveServicesUpdateQuotaError =
  LeaveServicesUpdateQuotaErrors[keyof LeaveServicesUpdateQuotaErrors];

export type LeaveServicesUpdateQuotaResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: LeaveQuota;
  };
};

export type LeaveServicesUpdateQuotaResponse =
  LeaveServicesUpdateQuotaResponses[keyof LeaveServicesUpdateQuotaResponses];

export type LeaveServicesSubmitRequestData = {
  body: CreateLeaveRequest;
  path?: never;
  query?: never;
  url: '/leaves/requests';
};

export type LeaveServicesSubmitRequestErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type LeaveServicesSubmitRequestError =
  LeaveServicesSubmitRequestErrors[keyof LeaveServicesSubmitRequestErrors];

export type LeaveServicesSubmitRequestResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: LeaveRequest;
  };
};

export type LeaveServicesSubmitRequestResponse =
  LeaveServicesSubmitRequestResponses[keyof LeaveServicesSubmitRequestResponses];

export type LeaveServicesCancelRequestData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/leaves/requests/{id}/cancel';
};

export type LeaveServicesCancelRequestErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type LeaveServicesCancelRequestError =
  LeaveServicesCancelRequestErrors[keyof LeaveServicesCancelRequestErrors];

export type LeaveServicesCancelRequestResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: LeaveRequest;
  };
};

export type LeaveServicesCancelRequestResponse =
  LeaveServicesCancelRequestResponses[keyof LeaveServicesCancelRequestResponses];

export type LeaveServicesReviewRequestData = {
  body: ReviewLeaveRequestRequest;
  path: {
    id: string;
  };
  query?: never;
  url: '/leaves/requests/{id}/review';
};

export type LeaveServicesReviewRequestErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type LeaveServicesReviewRequestError =
  LeaveServicesReviewRequestErrors[keyof LeaveServicesReviewRequestErrors];

export type LeaveServicesReviewRequestResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: LeaveRequest;
  };
};

export type LeaveServicesReviewRequestResponse =
  LeaveServicesReviewRequestResponses[keyof LeaveServicesReviewRequestResponses];

export type LeaveServicesCreateTypeData = {
  body: CreateLeaveType;
  path?: never;
  query?: never;
  url: '/leaves/types';
};

export type LeaveServicesCreateTypeErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type LeaveServicesCreateTypeError =
  LeaveServicesCreateTypeErrors[keyof LeaveServicesCreateTypeErrors];

export type LeaveServicesCreateTypeResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: LeaveType;
  };
};

export type LeaveServicesCreateTypeResponse =
  LeaveServicesCreateTypeResponses[keyof LeaveServicesCreateTypeResponses];

export type LeaveServicesUpdateTypeData = {
  body: UpdateLeaveType;
  path: {
    id: string;
  };
  query?: never;
  url: '/leaves/types/{id}';
};

export type LeaveServicesUpdateTypeErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type LeaveServicesUpdateTypeError =
  LeaveServicesUpdateTypeErrors[keyof LeaveServicesUpdateTypeErrors];

export type LeaveServicesUpdateTypeResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: LeaveType;
  };
};

export type LeaveServicesUpdateTypeResponse =
  LeaveServicesUpdateTypeResponses[keyof LeaveServicesUpdateTypeResponses];

export type PermissionServicesGetPermissionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/permissions/';
};

export type PermissionServicesGetPermissionsErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type PermissionServicesGetPermissionsError =
  PermissionServicesGetPermissionsErrors[keyof PermissionServicesGetPermissionsErrors];

export type PermissionServicesGetPermissionsResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<Permission>;
  };
};

export type PermissionServicesGetPermissionsResponse =
  PermissionServicesGetPermissionsResponses[keyof PermissionServicesGetPermissionsResponses];

export type PermissionServicesCreatePermissionData = {
  body: CreatePermission;
  path?: never;
  query?: never;
  url: '/permissions/';
};

export type PermissionServicesCreatePermissionErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type PermissionServicesCreatePermissionError =
  PermissionServicesCreatePermissionErrors[keyof PermissionServicesCreatePermissionErrors];

export type PermissionServicesCreatePermissionResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: Permission;
  };
};

export type PermissionServicesCreatePermissionResponse =
  PermissionServicesCreatePermissionResponses[keyof PermissionServicesCreatePermissionResponses];

export type PermissionServicesGetMyPermissionsData = {
  body?: never;
  path?: never;
  query?: {
    companyId?: string;
  };
  url: '/permissions/me';
};

export type PermissionServicesGetMyPermissionsErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type PermissionServicesGetMyPermissionsError =
  PermissionServicesGetMyPermissionsErrors[keyof PermissionServicesGetMyPermissionsErrors];

export type PermissionServicesGetMyPermissionsResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<Permission>;
  };
};

export type PermissionServicesGetMyPermissionsResponse =
  PermissionServicesGetMyPermissionsResponses[keyof PermissionServicesGetMyPermissionsResponses];

export type RoleServicesCreateRoleData = {
  body: CreateRole;
  path?: never;
  query?: never;
  url: '/permissions/roles/';
};

export type RoleServicesCreateRoleErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type RoleServicesCreateRoleError =
  RoleServicesCreateRoleErrors[keyof RoleServicesCreateRoleErrors];

export type RoleServicesCreateRoleResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: Role;
  };
};

export type RoleServicesCreateRoleResponse =
  RoleServicesCreateRoleResponses[keyof RoleServicesCreateRoleResponses];

export type RoleServicesGetCompanyRolesData = {
  body?: never;
  path: {
    companyId: string;
  };
  query?: never;
  url: '/permissions/roles/company/{companyId}';
};

export type RoleServicesGetCompanyRolesErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type RoleServicesGetCompanyRolesError =
  RoleServicesGetCompanyRolesErrors[keyof RoleServicesGetCompanyRolesErrors];

export type RoleServicesGetCompanyRolesResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<Role>;
  };
};

export type RoleServicesGetCompanyRolesResponse =
  RoleServicesGetCompanyRolesResponses[keyof RoleServicesGetCompanyRolesResponses];

export type RoleServicesAssignPermissionToRoleData = {
  body: CreateRolePermission;
  path?: never;
  query?: never;
  url: '/permissions/roles/permissions';
};

export type RoleServicesAssignPermissionToRoleErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type RoleServicesAssignPermissionToRoleError =
  RoleServicesAssignPermissionToRoleErrors[keyof RoleServicesAssignPermissionToRoleErrors];

export type RoleServicesAssignPermissionToRoleResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: RolePermission;
  };
};

export type RoleServicesAssignPermissionToRoleResponse =
  RoleServicesAssignPermissionToRoleResponses[keyof RoleServicesAssignPermissionToRoleResponses];

export type RoleServicesGetSystemDefaultRolesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/permissions/roles/system-defaults';
};

export type RoleServicesGetSystemDefaultRolesErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type RoleServicesGetSystemDefaultRolesError =
  RoleServicesGetSystemDefaultRolesErrors[keyof RoleServicesGetSystemDefaultRolesErrors];

export type RoleServicesGetSystemDefaultRolesResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<Role>;
  };
};

export type RoleServicesGetSystemDefaultRolesResponse =
  RoleServicesGetSystemDefaultRolesResponses[keyof RoleServicesGetSystemDefaultRolesResponses];

export type RoleServicesDeleteRoleData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/permissions/roles/{id}';
};

export type RoleServicesDeleteRoleErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type RoleServicesDeleteRoleError =
  RoleServicesDeleteRoleErrors[keyof RoleServicesDeleteRoleErrors];

export type RoleServicesDeleteRoleResponses = {
  /**
   * 200 OK without data
   */
  200: BasicResponse;
};

export type RoleServicesDeleteRoleResponse =
  RoleServicesDeleteRoleResponses[keyof RoleServicesDeleteRoleResponses];

export type RoleServicesGetRoleData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/permissions/roles/{id}';
};

export type RoleServicesGetRoleErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type RoleServicesGetRoleError =
  RoleServicesGetRoleErrors[keyof RoleServicesGetRoleErrors];

export type RoleServicesGetRoleResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Role;
  };
};

export type RoleServicesGetRoleResponse =
  RoleServicesGetRoleResponses[keyof RoleServicesGetRoleResponses];

export type RoleServicesUpdateRoleData = {
  body: UpdateRole;
  path: {
    id: string;
  };
  query?: never;
  url: '/permissions/roles/{id}';
};

export type RoleServicesUpdateRoleErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type RoleServicesUpdateRoleError =
  RoleServicesUpdateRoleErrors[keyof RoleServicesUpdateRoleErrors];

export type RoleServicesUpdateRoleResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Role;
  };
};

export type RoleServicesUpdateRoleResponse =
  RoleServicesUpdateRoleResponses[keyof RoleServicesUpdateRoleResponses];

export type RoleServicesGetRolePermissionsData = {
  body?: never;
  path: {
    roleId: string;
  };
  query?: never;
  url: '/permissions/roles/{roleId}/permissions';
};

export type RoleServicesGetRolePermissionsErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type RoleServicesGetRolePermissionsError =
  RoleServicesGetRolePermissionsErrors[keyof RoleServicesGetRolePermissionsErrors];

export type RoleServicesGetRolePermissionsResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<Permission>;
  };
};

export type RoleServicesGetRolePermissionsResponse =
  RoleServicesGetRolePermissionsResponses[keyof RoleServicesGetRolePermissionsResponses];

export type RoleServicesRevokePermissionFromRoleData = {
  body?: never;
  path: {
    roleId: string;
    permissionId: string;
  };
  query?: never;
  url: '/permissions/roles/{roleId}/permissions/{permissionId}';
};

export type RoleServicesRevokePermissionFromRoleErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type RoleServicesRevokePermissionFromRoleError =
  RoleServicesRevokePermissionFromRoleErrors[keyof RoleServicesRevokePermissionFromRoleErrors];

export type RoleServicesRevokePermissionFromRoleResponses = {
  /**
   * 200 OK without data
   */
  200: BasicResponse;
};

export type RoleServicesRevokePermissionFromRoleResponse =
  RoleServicesRevokePermissionFromRoleResponses[keyof RoleServicesRevokePermissionFromRoleResponses];

export type PermissionServicesDeletePermissionData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/permissions/{id}';
};

export type PermissionServicesDeletePermissionErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type PermissionServicesDeletePermissionError =
  PermissionServicesDeletePermissionErrors[keyof PermissionServicesDeletePermissionErrors];

export type PermissionServicesDeletePermissionResponses = {
  /**
   * 200 OK without data
   */
  200: BasicResponse;
};

export type PermissionServicesDeletePermissionResponse =
  PermissionServicesDeletePermissionResponses[keyof PermissionServicesDeletePermissionResponses];

export type PermissionServicesUpdatePermissionData = {
  body: UpdatePermission;
  path: {
    id: string;
  };
  query?: never;
  url: '/permissions/{id}';
};

export type PermissionServicesUpdatePermissionErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type PermissionServicesUpdatePermissionError =
  PermissionServicesUpdatePermissionErrors[keyof PermissionServicesUpdatePermissionErrors];

export type PermissionServicesUpdatePermissionResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Permission;
  };
};

export type PermissionServicesUpdatePermissionResponse =
  PermissionServicesUpdatePermissionResponses[keyof PermissionServicesUpdatePermissionResponses];

export type UserServicesGetUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/users/';
};

export type UserServicesGetUsersErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type UserServicesGetUsersError =
  UserServicesGetUsersErrors[keyof UserServicesGetUsersErrors];

export type UserServicesGetUsersResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: Array<User>;
  };
};

export type UserServicesGetUsersResponse =
  UserServicesGetUsersResponses[keyof UserServicesGetUsersResponses];

export type UserServicesCreateUserData = {
  body: CreateUser;
  path?: never;
  query?: never;
  url: '/users/';
};

export type UserServicesCreateUserErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
};

export type UserServicesCreateUserError =
  UserServicesCreateUserErrors[keyof UserServicesCreateUserErrors];

export type UserServicesCreateUserResponses = {
  /**
   * Successful response wrapping data payload
   */
  201: {
    success: boolean;
    message: string;
    data?: User;
  };
};

export type UserServicesCreateUserResponse =
  UserServicesCreateUserResponses[keyof UserServicesCreateUserResponses];

export type UserServicesDeleteUserData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/users/{id}';
};

export type UserServicesDeleteUserErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type UserServicesDeleteUserError =
  UserServicesDeleteUserErrors[keyof UserServicesDeleteUserErrors];

export type UserServicesDeleteUserResponses = {
  /**
   * 200 OK without data
   */
  200: BasicResponse;
};

export type UserServicesDeleteUserResponse =
  UserServicesDeleteUserResponses[keyof UserServicesDeleteUserResponses];

export type UserServicesGetUserData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/users/{id}';
};

export type UserServicesGetUserErrors = {
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type UserServicesGetUserError =
  UserServicesGetUserErrors[keyof UserServicesGetUserErrors];

export type UserServicesGetUserResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: User;
  };
};

export type UserServicesGetUserResponse =
  UserServicesGetUserResponses[keyof UserServicesGetUserResponses];

export type UserServicesUpdateUserData = {
  body: UpdateUser;
  path: {
    id: string;
  };
  query?: never;
  url: '/users/{id}';
};

export type UserServicesUpdateUserErrors = {
  /**
   * 400 Bad Request — INVALID_DATA
   */
  400: ApiErrorResponse;
  /**
   * 401 Unauthorized — UNAUTHORIZED
   */
  401: ApiErrorResponse;
  /**
   * 404 Not Found — NOT_FOUND
   */
  404: ApiErrorResponse;
};

export type UserServicesUpdateUserError =
  UserServicesUpdateUserErrors[keyof UserServicesUpdateUserErrors];

export type UserServicesUpdateUserResponses = {
  /**
   * Successful response wrapping data payload
   */
  200: {
    success: boolean;
    message: string;
    data?: User;
  };
};

export type UserServicesUpdateUserResponse =
  UserServicesUpdateUserResponses[keyof UserServicesUpdateUserResponses];
