import { FEATURE_CODES, type FeatureCode } from './features';

/** Built-in actions currently enforced by application use cases. */
export const PERMISSION_ACTIONS = {
  ATTENDANCE_CHECK_IN: 'attendance:check_in',
  ATTENDANCE_MANAGE: 'attendance:manage',
  ATTENDANCE_READ: 'attendance:read',
  ATTENDANCE_SCHEDULE_MANAGE: 'attendance_schedule:manage',
  ATTENDANCE_SCHEDULE_READ: 'attendance_schedule:read',
  ORGANIZATION_CREATE: 'organization:create',
  ORGANIZATION_DELETE: 'organization:delete',
  ORGANIZATION_READ: 'organization:read',
  ORGANIZATION_UPDATE: 'organization:update',
  SITE_CREATE: 'site:create',
  SITE_DELETE: 'site:delete',
  SITE_READ: 'site:read',
  SITE_UPDATE: 'site:update',
  ORGANIZATION_FEATURE_CREATE: 'organization_feature:create',
  ORGANIZATION_FEATURE_DELETE: 'organization_feature:delete',
  ORGANIZATION_FEATURE_READ: 'organization_feature:read',
  ORGANIZATION_FEATURE_TOGGLE: 'organization_feature:toggle',
  ORGANIZATION_MEMBER_CREATE: 'organization_member:create',
  ORGANIZATION_MEMBER_DELETE: 'organization_member:delete',
  ORGANIZATION_MEMBER_READ: 'organization_member:read',
  ORGANIZATION_MEMBER_UPDATE: 'organization_member:update',
  FEATURE_CREATE: 'feature:create',
  FEATURE_READ: 'feature:read',
  FEATURE_TOGGLE: 'feature:toggle',
  FEATURE_UPDATE: 'feature:update',
  FORM_PLAN_MANAGE: 'form_plan:manage',
  FORM_PLAN_READ: 'form_plan:read',
  FORM_REVIEW_ANSWER: 'form_review:answer',
  FORM_REVIEW_FINALIZE: 'form_review:finalize',
  FORM_REVIEW_READ: 'form_review:read',
  FORM_REVIEW_SECTION: 'form_review:section',
  FORM_REVIEW_SELF: 'form_review:self',
  FORM_SUBMISSION_CREATE: 'form_submission:create',
  FORM_SUBMISSION_READ: 'form_submission:read',
  FORM_SUBMISSION_REVIEW: 'form_submission:review',
  FORM_SUBMISSION_SUBMIT: 'form_submission:submit',
  FORM_SUBMISSION_UPDATE: 'form_submission:update',
  FORM_TEMPLATE_CREATE: 'form_template:create',
  FORM_TEMPLATE_MANAGE: 'form_template:manage',
  FORM_TEMPLATE_PUBLISH: 'form_template:publish',
  FORM_TEMPLATE_READ: 'form_template:read',
  FORM_TEMPLATE_UPDATE: 'form_template:update',
  LEAVE_QUOTA_MANAGE: 'leave_quota:manage',
  LEAVE_QUOTA_READ: 'leave_quota:read',
  LEAVE_REQUEST_APPROVE: 'leave_request:approve',
  LEAVE_REQUEST_CANCEL: 'leave_request:cancel',
  LEAVE_REQUEST_CREATE: 'leave_request:create',
  LEAVE_REQUEST_READ: 'leave_request:read',
  LEAVE_TYPE_MANAGE: 'leave_type:manage',
  LEAVE_TYPE_READ: 'leave_type:read',
  LOCATION_MANAGE: 'location:manage',
  LOCATION_READ: 'location:read',
  PERMISSION_ASSIGN: 'permission:assign',
  PERMISSION_CREATE: 'permission:create',
  PERMISSION_DELETE: 'permission:delete',
  PERMISSION_READ: 'permission:read',
  PERMISSION_REVOKE: 'permission:revoke',
  PERMISSION_UPDATE: 'permission:update',
  ROLE_CREATE: 'role:create',
  ROLE_DELETE: 'role:delete',
  ROLE_READ: 'role:read',
  ROLE_UPDATE: 'role:update',
  ROLE_FEATURE_CHECK: 'role_feature:check',
  ROLE_FEATURE_CREATE: 'role_feature:create',
  ROLE_FEATURE_DELETE: 'role_feature:delete',
  ROLE_FEATURE_READ: 'role_feature:read',
  ROLE_FEATURE_TOGGLE: 'role_feature:toggle',
  USER_CREATE: 'user:create',
  USER_DELETE: 'user:delete',
  USER_READ: 'user:read',
  USER_UPDATE: 'user:update',
} as const;

export type SystemPermissionAction =
  (typeof PERMISSION_ACTIONS)[keyof typeof PERMISSION_ACTIONS];

export const SYSTEM_PERMISSIONS = [
  {
    action: PERMISSION_ACTIONS.ATTENDANCE_CHECK_IN,
    module: 'attendance',
    description: 'attendance check in',
    featureCode: FEATURE_CODES.ATTENDANCE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ATTENDANCE_MANAGE,
    module: 'attendance',
    description: 'attendance manage',
    featureCode: FEATURE_CODES.ATTENDANCE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ATTENDANCE_READ,
    module: 'attendance',
    description: 'attendance read',
    featureCode: FEATURE_CODES.ATTENDANCE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ATTENDANCE_SCHEDULE_MANAGE,
    module: 'attendance_schedule',
    description: 'attendance schedule manage',
    featureCode: FEATURE_CODES.ATTENDANCE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ATTENDANCE_SCHEDULE_READ,
    module: 'attendance_schedule',
    description: 'attendance schedule read',
    featureCode: FEATURE_CODES.ATTENDANCE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ORGANIZATION_CREATE,
    module: 'organization',
    description: 'organization create',
    featureCode: FEATURE_CODES.ORGANIZATION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ORGANIZATION_DELETE,
    module: 'organization',
    description: 'organization delete',
    featureCode: FEATURE_CODES.ORGANIZATION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ORGANIZATION_READ,
    module: 'organization',
    description: 'organization read',
    featureCode: FEATURE_CODES.ORGANIZATION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ORGANIZATION_UPDATE,
    module: 'organization',
    description: 'organization update',
    featureCode: FEATURE_CODES.ORGANIZATION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.SITE_CREATE,
    module: 'site',
    description: 'site create',
    featureCode: FEATURE_CODES.ORGANIZATION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.SITE_DELETE,
    module: 'site',
    description: 'site delete',
    featureCode: FEATURE_CODES.ORGANIZATION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.SITE_READ,
    module: 'site',
    description: 'site read',
    featureCode: FEATURE_CODES.ORGANIZATION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.SITE_UPDATE,
    module: 'site',
    description: 'site update',
    featureCode: FEATURE_CODES.ORGANIZATION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ORGANIZATION_FEATURE_CREATE,
    module: 'organization_feature',
    description: 'organization feature create',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ORGANIZATION_FEATURE_DELETE,
    module: 'organization_feature',
    description: 'organization feature delete',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ORGANIZATION_FEATURE_READ,
    module: 'organization_feature',
    description: 'organization feature read',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ORGANIZATION_FEATURE_TOGGLE,
    module: 'organization_feature',
    description: 'organization feature toggle',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ORGANIZATION_MEMBER_CREATE,
    module: 'organization_member',
    description: 'organization member create',
    featureCode: FEATURE_CODES.EMPLOYEE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ORGANIZATION_MEMBER_DELETE,
    module: 'organization_member',
    description: 'organization member delete',
    featureCode: FEATURE_CODES.EMPLOYEE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ORGANIZATION_MEMBER_READ,
    module: 'organization_member',
    description: 'organization member read',
    featureCode: FEATURE_CODES.EMPLOYEE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ORGANIZATION_MEMBER_UPDATE,
    module: 'organization_member',
    description: 'organization member update',
    featureCode: FEATURE_CODES.EMPLOYEE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FEATURE_CREATE,
    module: 'feature',
    description: 'feature create',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FEATURE_READ,
    module: 'feature',
    description: 'feature read',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FEATURE_TOGGLE,
    module: 'feature',
    description: 'feature toggle',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FEATURE_UPDATE,
    module: 'feature',
    description: 'feature update',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_PLAN_MANAGE,
    module: 'form_plan',
    description: 'Create and manage form plans and schedules',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_PLAN_READ,
    module: 'form_plan',
    description: 'View form plans and occurrences',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_REVIEW_ANSWER,
    module: 'form_review',
    description: 'Review individual answers (PASS/NEEDS_CHANGES)',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_REVIEW_FINALIZE,
    module: 'form_review',
    description: 'Finalize submission review (APPROVE/RETURN)',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_REVIEW_READ,
    module: 'form_review',
    description: 'View review entries and history',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_REVIEW_SECTION,
    module: 'form_review',
    description: 'Review form sections (PASS/NEEDS_CHANGES)',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_REVIEW_SELF,
    module: 'form_review',
    description:
      'Allow reviewing own submissions (requires another review permission)',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_SUBMISSION_CREATE,
    module: 'form_submission',
    description: 'form submission create',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_SUBMISSION_READ,
    module: 'form_submission',
    description: 'form submission read',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_SUBMISSION_REVIEW,
    module: 'form_submission',
    description: 'form submission review',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_SUBMISSION_SUBMIT,
    module: 'form_submission',
    description: 'form submission submit',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_SUBMISSION_UPDATE,
    module: 'form_submission',
    description: 'form submission update',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_TEMPLATE_CREATE,
    module: 'form_template',
    description: 'form template create',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_TEMPLATE_MANAGE,
    module: 'form_template',
    description: 'Manage form templates (edit, archive, publish)',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_TEMPLATE_PUBLISH,
    module: 'form_template',
    description: 'form template publish',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_TEMPLATE_READ,
    module: 'form_template',
    description: 'form template read',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_TEMPLATE_UPDATE,
    module: 'form_template',
    description: 'form template update',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.LEAVE_QUOTA_MANAGE,
    module: 'leave',
    description: 'leave quota manage',
    featureCode: FEATURE_CODES.LEAVE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.LEAVE_QUOTA_READ,
    module: 'leave',
    description: 'leave quota read',
    featureCode: FEATURE_CODES.LEAVE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.LEAVE_REQUEST_APPROVE,
    module: 'leave',
    description: 'leave request approve',
    featureCode: FEATURE_CODES.LEAVE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.LEAVE_REQUEST_CANCEL,
    module: 'leave',
    description: 'leave request cancel',
    featureCode: FEATURE_CODES.LEAVE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.LEAVE_REQUEST_CREATE,
    module: 'leave',
    description: 'leave request create',
    featureCode: FEATURE_CODES.LEAVE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.LEAVE_REQUEST_READ,
    module: 'leave',
    description: 'leave request read',
    featureCode: FEATURE_CODES.LEAVE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.LEAVE_TYPE_MANAGE,
    module: 'leave',
    description: 'leave type manage',
    featureCode: FEATURE_CODES.LEAVE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.LEAVE_TYPE_READ,
    module: 'leave',
    description: 'leave type read',
    featureCode: FEATURE_CODES.LEAVE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.LOCATION_MANAGE,
    module: 'location',
    description: 'location manage',
    featureCode: FEATURE_CODES.ATTENDANCE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.LOCATION_READ,
    module: 'location',
    description: 'location read',
    featureCode: FEATURE_CODES.ATTENDANCE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.PERMISSION_ASSIGN,
    module: 'permission',
    description: 'permission assign',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.PERMISSION_CREATE,
    module: 'permission',
    description: 'permission create',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.PERMISSION_DELETE,
    module: 'permission',
    description: 'permission delete',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.PERMISSION_READ,
    module: 'permission',
    description: 'permission read',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.PERMISSION_REVOKE,
    module: 'permission',
    description: 'permission revoke',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.PERMISSION_UPDATE,
    module: 'permission',
    description: 'permission update',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ROLE_CREATE,
    module: 'role',
    description: 'role create',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ROLE_DELETE,
    module: 'role',
    description: 'role delete',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ROLE_READ,
    module: 'role',
    description: 'role read',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ROLE_UPDATE,
    module: 'role',
    description: 'role update',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ROLE_FEATURE_CHECK,
    module: 'role_feature',
    description: 'role feature check',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ROLE_FEATURE_CREATE,
    module: 'role_feature',
    description: 'role feature create',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ROLE_FEATURE_DELETE,
    module: 'role_feature',
    description: 'role feature delete',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ROLE_FEATURE_READ,
    module: 'role_feature',
    description: 'role feature read',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ROLE_FEATURE_TOGGLE,
    module: 'role_feature',
    description: 'role feature toggle',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.USER_CREATE,
    module: 'user',
    description: 'user create',
    featureCode: FEATURE_CODES.EMPLOYEE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.USER_DELETE,
    module: 'user',
    description: 'user delete',
    featureCode: FEATURE_CODES.EMPLOYEE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.USER_READ,
    module: 'user',
    description: 'user read',
    featureCode: FEATURE_CODES.EMPLOYEE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.USER_UPDATE,
    module: 'user',
    description: 'user update',
    featureCode: FEATURE_CODES.EMPLOYEE_MANAGEMENT,
  },
] as const satisfies readonly {
  action: SystemPermissionAction;
  module: string;
  description: string;
  featureCode: FeatureCode;
}[];
