import { FEATURE_CODES, type FeatureCode } from './features';

/** Built-in actions currently enforced by application use cases. */
export const PERMISSION_ACTIONS = {
  ATTENDANCE_CHECK_IN: 'attendance:check_in',
  ATTENDANCE_MANAGE: 'attendance:manage',
  ATTENDANCE_READ: 'attendance:read',
  ATTENDANCE_SCHEDULE_MANAGE: 'attendance_schedule:manage',
  ATTENDANCE_SCHEDULE_READ: 'attendance_schedule:read',
  COMPANY_CREATE: 'company:create',
  COMPANY_DELETE: 'company:delete',
  COMPANY_READ: 'company:read',
  COMPANY_UPDATE: 'company:update',
  COMPANY_BRANCH_CREATE: 'company_branch:create',
  COMPANY_BRANCH_DELETE: 'company_branch:delete',
  COMPANY_BRANCH_READ: 'company_branch:read',
  COMPANY_BRANCH_UPDATE: 'company_branch:update',
  COMPANY_FEATURE_CREATE: 'company_feature:create',
  COMPANY_FEATURE_DELETE: 'company_feature:delete',
  COMPANY_FEATURE_READ: 'company_feature:read',
  COMPANY_FEATURE_TOGGLE: 'company_feature:toggle',
  COMPANY_MEMBER_CREATE: 'company_member:create',
  COMPANY_MEMBER_DELETE: 'company_member:delete',
  COMPANY_MEMBER_READ: 'company_member:read',
  COMPANY_MEMBER_UPDATE: 'company_member:update',
  FEATURE_CREATE: 'feature:create',
  FEATURE_READ: 'feature:read',
  FEATURE_TOGGLE: 'feature:toggle',
  FEATURE_UPDATE: 'feature:update',
  FORM_SUBMISSION_CREATE: 'form_submission:create',
  FORM_SUBMISSION_READ: 'form_submission:read',
  FORM_SUBMISSION_REVIEW: 'form_submission:review',
  FORM_SUBMISSION_SUBMIT: 'form_submission:submit',
  FORM_SUBMISSION_UPDATE: 'form_submission:update',
  FORM_TEMPLATE_CREATE: 'form_template:create',
  FORM_TEMPLATE_PUBLISH: 'form_template:publish',
  FORM_TEMPLATE_READ: 'form_template:read',
  FORM_TEMPLATE_UPDATE: 'form_template:update',
  LEAVE_QUOTA_MANAGE: 'leave_quota:manage',
  LEAVE_QUOTA_READ: 'leave_quota:read',
  LEAVE_REQUEST_APPROVE: 'leave_request:approve',
  LEAVE_REQUEST_CANCEL: 'leave_request:cancel',
  LEAVE_REQUEST_CREATE: 'leave_request:create',
  LEAVE_REQUEST_READ: 'leave_request:read',
  LEAVE_TYPE_MANAGE: 'leave_type:manage',
  LEAVE_TYPE_READ: 'leave_type:read',
  PERMISSION_ASSIGN: 'permission:assign',
  PERMISSION_CREATE: 'permission:create',
  PERMISSION_DELETE: 'permission:delete',
  PERMISSION_READ: 'permission:read',
  PERMISSION_REVOKE: 'permission:revoke',
  PERMISSION_UPDATE: 'permission:update',
  ROLE_CREATE: 'role:create',
  ROLE_DELETE: 'role:delete',
  ROLE_READ: 'role:read',
  ROLE_UPDATE: 'role:update',
  ROLE_FEATURE_CHECK: 'role_feature:check',
  ROLE_FEATURE_CREATE: 'role_feature:create',
  ROLE_FEATURE_DELETE: 'role_feature:delete',
  ROLE_FEATURE_READ: 'role_feature:read',
  ROLE_FEATURE_TOGGLE: 'role_feature:toggle',
  USER_CREATE: 'user:create',
  USER_DELETE: 'user:delete',
  USER_READ: 'user:read',
  USER_UPDATE: 'user:update',
} as const;

export type SystemPermissionAction =
  (typeof PERMISSION_ACTIONS)[keyof typeof PERMISSION_ACTIONS];

export const SYSTEM_PERMISSIONS = [
  {
    action: PERMISSION_ACTIONS.ATTENDANCE_CHECK_IN,
    module: 'attendance',
    description: 'attendance check in',
    featureCode: FEATURE_CODES.ATTENDANCE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ATTENDANCE_MANAGE,
    module: 'attendance',
    description: 'attendance manage',
    featureCode: FEATURE_CODES.ATTENDANCE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ATTENDANCE_READ,
    module: 'attendance',
    description: 'attendance read',
    featureCode: FEATURE_CODES.ATTENDANCE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ATTENDANCE_SCHEDULE_MANAGE,
    module: 'attendance_schedule',
    description: 'attendance schedule manage',
    featureCode: FEATURE_CODES.ATTENDANCE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ATTENDANCE_SCHEDULE_READ,
    module: 'attendance_schedule',
    description: 'attendance schedule read',
    featureCode: FEATURE_CODES.ATTENDANCE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.COMPANY_CREATE,
    module: 'company',
    description: 'company create',
    featureCode: FEATURE_CODES.COMPANY_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.COMPANY_DELETE,
    module: 'company',
    description: 'company delete',
    featureCode: FEATURE_CODES.COMPANY_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.COMPANY_READ,
    module: 'company',
    description: 'company read',
    featureCode: FEATURE_CODES.COMPANY_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.COMPANY_UPDATE,
    module: 'company',
    description: 'company update',
    featureCode: FEATURE_CODES.COMPANY_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.COMPANY_BRANCH_CREATE,
    module: 'company_branch',
    description: 'company branch create',
    featureCode: FEATURE_CODES.COMPANY_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.COMPANY_BRANCH_DELETE,
    module: 'company_branch',
    description: 'company branch delete',
    featureCode: FEATURE_CODES.COMPANY_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.COMPANY_BRANCH_READ,
    module: 'company_branch',
    description: 'company branch read',
    featureCode: FEATURE_CODES.COMPANY_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.COMPANY_BRANCH_UPDATE,
    module: 'company_branch',
    description: 'company branch update',
    featureCode: FEATURE_CODES.COMPANY_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.COMPANY_FEATURE_CREATE,
    module: 'company_feature',
    description: 'company feature create',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.COMPANY_FEATURE_DELETE,
    module: 'company_feature',
    description: 'company feature delete',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.COMPANY_FEATURE_READ,
    module: 'company_feature',
    description: 'company feature read',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.COMPANY_FEATURE_TOGGLE,
    module: 'company_feature',
    description: 'company feature toggle',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.COMPANY_MEMBER_CREATE,
    module: 'company_member',
    description: 'company member create',
    featureCode: FEATURE_CODES.EMPLOYEE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.COMPANY_MEMBER_DELETE,
    module: 'company_member',
    description: 'company member delete',
    featureCode: FEATURE_CODES.EMPLOYEE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.COMPANY_MEMBER_READ,
    module: 'company_member',
    description: 'company member read',
    featureCode: FEATURE_CODES.EMPLOYEE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.COMPANY_MEMBER_UPDATE,
    module: 'company_member',
    description: 'company member update',
    featureCode: FEATURE_CODES.EMPLOYEE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FEATURE_CREATE,
    module: 'feature',
    description: 'feature create',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FEATURE_READ,
    module: 'feature',
    description: 'feature read',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FEATURE_TOGGLE,
    module: 'feature',
    description: 'feature toggle',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FEATURE_UPDATE,
    module: 'feature',
    description: 'feature update',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_SUBMISSION_CREATE,
    module: 'form_submission',
    description: 'form submission create',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_SUBMISSION_READ,
    module: 'form_submission',
    description: 'form submission read',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_SUBMISSION_REVIEW,
    module: 'form_submission',
    description: 'form submission review',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_SUBMISSION_SUBMIT,
    module: 'form_submission',
    description: 'form submission submit',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_SUBMISSION_UPDATE,
    module: 'form_submission',
    description: 'form submission update',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_TEMPLATE_CREATE,
    module: 'form_template',
    description: 'form template create',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_TEMPLATE_PUBLISH,
    module: 'form_template',
    description: 'form template publish',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_TEMPLATE_READ,
    module: 'form_template',
    description: 'form template read',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.FORM_TEMPLATE_UPDATE,
    module: 'form_template',
    description: 'form template update',
    featureCode: FEATURE_CODES.FORM_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.LEAVE_QUOTA_MANAGE,
    module: 'leave',
    description: 'leave quota manage',
    featureCode: FEATURE_CODES.LEAVE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.LEAVE_QUOTA_READ,
    module: 'leave',
    description: 'leave quota read',
    featureCode: FEATURE_CODES.LEAVE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.LEAVE_REQUEST_APPROVE,
    module: 'leave',
    description: 'leave request approve',
    featureCode: FEATURE_CODES.LEAVE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.LEAVE_REQUEST_CANCEL,
    module: 'leave',
    description: 'leave request cancel',
    featureCode: FEATURE_CODES.LEAVE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.LEAVE_REQUEST_CREATE,
    module: 'leave',
    description: 'leave request create',
    featureCode: FEATURE_CODES.LEAVE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.LEAVE_REQUEST_READ,
    module: 'leave',
    description: 'leave request read',
    featureCode: FEATURE_CODES.LEAVE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.LEAVE_TYPE_MANAGE,
    module: 'leave',
    description: 'leave type manage',
    featureCode: FEATURE_CODES.LEAVE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.LEAVE_TYPE_READ,
    module: 'leave',
    description: 'leave type read',
    featureCode: FEATURE_CODES.LEAVE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.PERMISSION_ASSIGN,
    module: 'permission',
    description: 'permission assign',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.PERMISSION_CREATE,
    module: 'permission',
    description: 'permission create',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.PERMISSION_DELETE,
    module: 'permission',
    description: 'permission delete',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.PERMISSION_READ,
    module: 'permission',
    description: 'permission read',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.PERMISSION_REVOKE,
    module: 'permission',
    description: 'permission revoke',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.PERMISSION_UPDATE,
    module: 'permission',
    description: 'permission update',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ROLE_CREATE,
    module: 'role',
    description: 'role create',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ROLE_DELETE,
    module: 'role',
    description: 'role delete',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ROLE_READ,
    module: 'role',
    description: 'role read',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ROLE_UPDATE,
    module: 'role',
    description: 'role update',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ROLE_FEATURE_CHECK,
    module: 'role_feature',
    description: 'role feature check',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ROLE_FEATURE_CREATE,
    module: 'role_feature',
    description: 'role feature create',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ROLE_FEATURE_DELETE,
    module: 'role_feature',
    description: 'role feature delete',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ROLE_FEATURE_READ,
    module: 'role_feature',
    description: 'role feature read',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.ROLE_FEATURE_TOGGLE,
    module: 'role_feature',
    description: 'role feature toggle',
    featureCode: FEATURE_CODES.ROLE_PERMISSION_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.USER_CREATE,
    module: 'user',
    description: 'user create',
    featureCode: FEATURE_CODES.EMPLOYEE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.USER_DELETE,
    module: 'user',
    description: 'user delete',
    featureCode: FEATURE_CODES.EMPLOYEE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.USER_READ,
    module: 'user',
    description: 'user read',
    featureCode: FEATURE_CODES.EMPLOYEE_MANAGEMENT,
  },
  {
    action: PERMISSION_ACTIONS.USER_UPDATE,
    module: 'user',
    description: 'user update',
    featureCode: FEATURE_CODES.EMPLOYEE_MANAGEMENT,
  },
] as const satisfies readonly {
  action: SystemPermissionAction;
  module: string;
  description: string;
  featureCode: FeatureCode;
}[];
